In [1]:
import numpy as np
import pandas as pd
import os
from datetime import datetime, date
from statsmodels.tsa.vector_ar.var_model import VAR
from statsmodels.tsa.vector_ar.vecm import VECM, coint_johansen
import scipy.linalg as la
from scipy.linalg import eig
from statsmodels.tsa.vector_ar.var_model import VAR
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller
import matplotlib.pyplot as plt
print(f"modules have been imported.")

modules have been imported.

In [2]:
# Step 1: Lets grab the historical time series from Mohaddes first. 
# Question should we grab it by economies first? if yes then lets take the 'Country Data'
print(os.getcwd())
target_filename = "Country Data (1979Q2-2023Q3).xls"
target_file_path = os.getcwd() + "\\" + "GVAR Database (1979Q2-2023Q3)\\" + target_filename
print(f"target_file_path is: {target_file_path}")
# dataframe the country data
countries_df = pd.read_excel(target_file_path, sheet_name = None)
countries_df.keys()

C:\Users\benchee
target_file_path is: C:\Users\benchee\GVAR Database (1979Q2-2023Q3)\Country Data (1979Q2-2023Q3).xls

dict_keys(['ARGENTINA', 'AUSTRALIA', 'BRAZIL', 'CANADA', 'CHINA', 'CHILE', 'EURO', 'INDIA', 'INDONESIA', 'JAPAN', 'KOREA', 'MALAYSIA', 'MEXICO', 'NORWAY', 'NEW ZEALAND', 'PERU', 'PHILIPPINES', 'SOUTH AFRICA', 'SAUDI ARABIA', 'SINGAPORE', 'SWEDEN', 'SWITZERLAND', 'THAILAND', 'TURKEY', 'UNITED KINGDOM', 'USA'])

In [3]:
us_df = countries_df['USA']
sg_df = countries_df['SINGAPORE']
cn_df = countries_df['CHINA']
eu_df = countries_df['EURO']
# convert the date into datetime format 
# ie: 1979Q2 is 30-Jun-1979.
us_df['date_2'] = pd.PeriodIndex(us_df['date'], freq = 'Q').to_timestamp(how = "end").date
sg_df['date_2'] = pd.PeriodIndex(sg_df['date'], freq = 'Q').to_timestamp(how = "end").date
cn_df['date_2'] = pd.PeriodIndex(cn_df['date'], freq = 'Q').to_timestamp(how = "end").date
eu_df['date_2'] = pd.PeriodIndex(eu_df['date'], freq = 'Q').to_timestamp(how = "end").date

us_target_cols = [col for col in us_df.columns if 'date' not in col]
us_target_cols = ['date_2'] + us_target_cols 

sg_target_cols = [col for col in sg_df.columns if 'date' not in col]
sg_target_cols = ['date_2'] + sg_target_cols 

cn_target_cols = [col for col in cn_df.columns if 'date' not in col]
cn_target_cols = ['date_2'] + cn_target_cols 

eu_target_cols = [col for col in eu_df.columns if 'date' not in col]
eu_target_cols = ['date_2'] + eu_target_cols 

print(us_target_cols)

us_df = us_df[us_target_cols]
us_df = us_df.rename(columns={'date_2': 'date'})
us_df

sg_df = sg_df[sg_target_cols]
sg_df = sg_df.rename(columns={'date_2': 'date'})
sg_df

cn_df = cn_df[cn_target_cols]
cn_df = cn_df.rename(columns={'date_2': 'date'})
cn_df

eu_df = eu_df[eu_target_cols]
eu_df = eu_df.rename(columns={'date_2': 'date'})
eu_df

['date_2', 'y', 'Dp', 'eq', 'r', 'lr', 'ys', 'Dps', 'eps', 'poil', 'pmat', 'pmetal']

,date,y,Dp,eq,ep,r,lr,ys,Dps,eqs,rs,lrs,poil,pmat,pmetal
0,1979-06-30,4.151148,0.022753,0.701674,-4.156059,0.020858,0.023323,3.763988,0.032185,0.977932,0.022302,0.023070,3.433544,4.148960,4.200168
1,1979-09-30,4.156398,0.025299,0.723492,-4.217551,0.022919,0.024231,3.771680,0.043473,0.956643,0.023587,0.023496,3.576322,4.272871,4.198063
2,1979-12-31,4.166828,0.026988,0.662959,-4.257434,0.025633,0.025393,3.785490,0.034167,0.922622,0.025699,0.026133,3.696729,4.220098,4.305733
3,1980-03-31,4.176844,0.032215,0.672845,-4.271255,0.027541,0.027575,3.793602,0.045573,0.923275,0.027895,0.028130,3.661658,4.311326,4.431295
4,1980-06-30,4.171065,0.024655,0.649555,-4.298715,0.029884,0.028336,3.787795,0.040089,0.916227,0.026489,0.026966,3.643353,4.207531,4.284341
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,2022-09-30,4.815708,0.020158,1.990970,-5.561242,0.000891,0.005307,5.337170,0.018444,2.696272,0.009416,0.006349,4.613407,4.814593,5.240803
174,2022-12-31,4.810953,0.021251,2.095719,-5.569188,0.003811,0.007124,5.338953,0.014712,2.736946,0.011651,0.007851,4.485170,4.719217,5.244402
175,2023-03-31,4.813094,0.009064,2.195740,-5.528113,0.006374,0.007455,5.347404,0.014027,2.764883,0.012978,0.007611,4.397714,4.696997,5.416306
176,2023-06-30,4.821536,0.007371,2.201635,-5.520525,0.007670,0.007590,5.356329,0.011225,2.781942,0.014519,0.007856,4.361766,4.674107,5.315188
177,2023-09-30,4.819876,0.009212,2.159652,-5.530479,0.008936,0.008025,5.361675,0.017968,2.763763,0.015821,0.008800,4.462956,4.678431,5.289791

In [4]:
# 1. We first and foremostly must do is to do the ADF (augmented dickey fuller) test to check on its unit root testing. 
## 2. We need to do the AIC and BIC test to find out the lags that are most optimal for the VARX
## 3. This is to test the weak exogeneity for each variable components in the us_df table. 

def run_gvar_stationary_check(country, dataframe, significance_level = 0.05):
    adf_results = []
    # 2. Automated ADF testing loop function
    for column in dataframe.columns:
        if column not in 'date':
            
            # --- TEST 1: Check Raw Levels ---
            # autolag = 'AIC' lets the module find the best lag length to remove serial autocorrelation.
            # regression = 'c' includes a constant intercept in the test equation.
            # let significance_level = 0.05
            level_res = adfuller(dataframe[column], autolag = 'AIC', regression = 'c')
            level_pvalue = level_res[1]
            level_stationary = level_pvalue < significance_level
            
#            print(f"--- Results for the US {column} ---")
#            print(f"level_res is: {level_res}")
#            print(f"level_pvalue is: {level_pvalue}")
#            print(f"level_stationary is: {level_stationary}")
            
            # Determine Integration Order Classification
            if not level_stationary:
                classification = "I(1) - Perfect for VECM"
            elif level_stationary:
                classification = "I(0) - Already Stationary"
            else:
                classification = "I(2) or Higher/ Explosive"
            
            adf_results.append({
                'country' : country,
                'variable' : column,
                'level_pvalue' : round(level_pvalue, 4),
                'level_stationary' : level_stationary,
                'classification' : classification,
            })
        
    return pd.DataFrame(adf_results)

us_adfuller_df = run_gvar_stationary_check("US", us_df, significance_level = 0.05)
sg_adfuller_df = run_gvar_stationary_check("SG", sg_df, significance_level = 0.05)
cn_adfuller_df = run_gvar_stationary_check("CN", cn_df, significance_level = 0.05)
eu_adfuller_df = run_gvar_stationary_check("EU", eu_df, significance_level = 0.05)

all_adfuller_df = us_adfuller_df.copy()
all_adfuller_df = pd.concat([all_adfuller_df, sg_adfuller_df, cn_adfuller_df, eu_adfuller_df], axis = 0)

display(all_adfuller_df)

   country variable  level_pvalue  level_stationary             classification
0       US        y        0.6722             False    I(1) - Perfect for VECM
1       US       Dp        0.0000              True  I(0) - Already Stationary
2       US       eq        0.7832             False    I(1) - Perfect for VECM
3       US        r        0.0901             False    I(1) - Perfect for VECM
4       US       lr        0.5487             False    I(1) - Perfect for VECM
5       US       ys        0.3974             False    I(1) - Perfect for VECM
6       US      Dps        0.6558             False    I(1) - Perfect for VECM
7       US      eps        0.8429             False    I(1) - Perfect for VECM
8       US     poil        0.6556             False    I(1) - Perfect for VECM
9       US     pmat        0.1268             False    I(1) - Perfect for VECM
10      US   pmetal        0.6214             False    I(1) - Perfect for VECM
0       SG        y        0.0528             False    I(1) - Perfect for VECM
1       SG       Dp        0.0157              True  I(0) - Already Stationary
2       SG       eq        0.0045              True  I(0) - Already Stationary
3       SG       ep        0.6665             False    I(1) - Perfect for VECM
4       SG        r        0.2567             False    I(1) - Perfect for VECM
5       SG       ys        0.2081             False    I(1) - Perfect for VECM
6       SG      Dps        0.0231              True  I(0) - Already Stationary
7       SG      eqs        0.4500             False    I(1) - Perfect for VECM
8       SG       rs        0.6985             False    I(1) - Perfect for VECM
9       SG      lrs        0.3304             False    I(1) - Perfect for VECM
10      SG     poil        0.6556             False    I(1) - Perfect for VECM
11      SG     pmat        0.1268             False    I(1) - Perfect for VECM
12      SG   pmetal        0.6214             False    I(1) - Perfect for VECM
0       CN        y        0.5476             False    I(1) - Perfect for VECM
1       CN       Dp        0.0939             False    I(1) - Perfect for VECM
2       CN       ep        0.8468             False    I(1) - Perfect for VECM
3       CN        r        0.6219             False    I(1) - Perfect for VECM
4       CN       ys        0.2093             False    I(1) - Perfect for VECM
5       CN      Dps        0.0938             False    I(1) - Perfect for VECM
6       CN      eqs        0.4541             False    I(1) - Perfect for VECM
7       CN       rs        0.5591             False    I(1) - Perfect for VECM
8       CN      lrs        0.3659             False    I(1) - Perfect for VECM
9       CN     poil        0.6556             False    I(1) - Perfect for VECM
10      CN     pmat        0.1268             False    I(1) - Perfect for VECM
11      CN   pmetal        0.6214             False    I(1) - Perfect for VECM
0       EU        y        0.4192             False    I(1) - Perfect for VECM
1       EU       Dp        0.0093              True  I(0) - Already Stationary
2       EU       eq        0.2806             False    I(1) - Perfect for VECM
3       EU       ep        0.8295             False    I(1) - Perfect for VECM
4       EU        r        0.4866             False    I(1) - Perfect for VECM
5       EU       lr        0.6039             False    I(1) - Perfect for VECM
6       EU       ys        0.5987             False    I(1) - Perfect for VECM
7       EU      Dps        0.1025             False    I(1) - Perfect for VECM
8       EU      eqs        0.4435             False    I(1) - Perfect for VECM
9       EU       rs        0.6108             False    I(1) - Perfect for VECM
10      EU      lrs        0.5413             False    I(1) - Perfect for VECM
11      EU     poil        0.6556             False    I(1) - Perfect for VECM
12      EU     pmat        0.1268             False    I(1) - Perfect for VECM
13      EU   pmetal        0.6214             False    I(1) - Perfect for VECM

# The code below is supposed to be a module to find the best lag order based on AIC, BIC and HQIC. 
# However, seeing that we need to see the results of the VECMX. I will get back to this when i can have a better picture on how the lags p, q = 2,2 works.

In [5]:
# this code block will be used for the AIC, BIC and HQIC

endog_vars = ['y', 'Dp', 'eq', 'r', 'lr', 'poil', 'pmat', 'pmetal']
exog_vars = ['ys', 'Dps']

us_endog_df = us_df[endog_vars]
us_exog_df = us_df[exog_vars]

display(us_endog_df)
display(us_exog_df)

# define variables
exog_df = us_exog_df
endog_df = us_endog_df
#display(exog_df)
#print(f"endog_df is: \n {display(endog_df)}")

# Grid parameters
max_p = 3 # for domestic/ endog vars
max_q = 2 # for foreign/ exog vars
max_lag = max(max_p, max_q)

results = []

# 2. High level optimization loop using statsmodels internals. 
for p in range(1, max_p + 1):
    for q in range(0, max_q + 1):
        
        print(f"p,q are: ({p},{q})")
        # Construct foreign variables lag columns
        exog_list = []
        for lag in range(0, q + 1):
            print(f"lag (q) now is: {lag}")
            target_exog_df = exog_df.shift(lag)
            if lag >= 1:
                target_exog_df.columns = [f"{col}_lag{q}" for col in target_exog_df.columns]

            exog_list.append(target_exog_df) # shift the lag based on q variable.      
        
        X_exog = pd.concat(exog_list, axis = 1).dropna() # to concatenate by columns. 
#        print(f"X_exog is:\n {display(X_exog)}")
#        print(f"X_exog.index is:\n {display(X_exog.index)}")

        # Align endog target dataframe to match exogenous shift row losses.
        Y_target = endog_df.loc[X_exog.index]
#        print(f"Y_target is:\n {display(Y_target)}")

        # CRUCIAL GVAR TRIMMING: Ensure ALL lag combinations run on the exact same time window. 
        # This keeps the comparison mathematically fair across the loops. 
        X_exog_clean = X_exog.iloc[(max_lag - p):] # max_lag = 3, p = 1, ans = 2 
        Y_target_clean = Y_target.iloc[(max_lag - p):] # max_lag = 3, p = 1, ans = 2

#        print(f"X_exog_clean is:\n {display(X_exog_clean)}")
        print(f"X_exog_clean shape is:\n {(X_exog_clean.shape)}")
#        print(f"Y_target_clean is:\n {display(Y_target_clean)}")
        print(f"Y_target_clean shape is:\n {(Y_target_clean.shape)}")

        # 3. Call the built-in statsmodels VAR function with exog parameters
        # maxlags = p forces the engine to fit exactly 'p' for domestic lags
        model = VAR(endog = Y_target_clean, exog = X_exog_clean)
        results_fitted = model.fit(maxlags=p)

        # 4. Pull the native optimized AIC/BIC/HQIC calculations from the results object.
        results.append({
            'p' : p,
            'q' : q,
            'AIC' : results_fitted.aic,
            'BIC' : results_fitted.bic,
            'HQIC' : results_fitted.hqic,
        })
        
#        if q == 1: 
#            print(f"lets look at the results first.")
#            break

# 5. Display the final score sheet.
df_scores = pd.DataFrame(results)
print("--- Statsmodels Evaluated Scores ---")
print(f"df_scores is: \n {display(df_scores)}")
print(df_scores.to_string(index=False))

# Extract the winning combinations
print(f"\nWinning Architecture by AIC: P={df_scores.loc[df_scores['AIC'].idxmin(), 'p']}, Q = {df_scores.loc[df_scores['AIC'].idxmin(), 'q']}")
print(f"\nWinning Architecture by BIC: P={df_scores.loc[df_scores['BIC'].idxmin(), 'p']}, Q = {df_scores.loc[df_scores['BIC'].idxmin(), 'q']}")
print(f"\nWinning Architecture by HQIC: P={df_scores.loc[df_scores['HQIC'].idxmin(), 'p']}, Q = {df_scores.loc[df_scores['HQIC'].idxmin(), 'q']}")

,y,Dp,eq,r,lr,poil,pmat,pmetal
0,3.960503,0.033730,0.684670,0.022407,0.021804,3.433544,4.148960,4.200168
1,3.967677,0.032477,0.699070,0.023084,0.021781,3.576322,4.272871,4.198063
2,3.970622,0.028823,0.640953,0.027982,0.024841,3.696729,4.220098,4.305733
3,3.973806,0.038217,0.615193,0.031335,0.028302,3.661658,4.311326,4.431295
4,3.953413,0.035451,0.609975,0.022955,0.024909,3.643353,4.207531,4.284341
...,...,...,...,...,...,...,...,...
173,5.008861,0.014444,2.906448,0.006571,0.007648,4.613407,4.814593,5.240803
174,5.015219,0.009122,2.961698,0.009901,0.009396,4.485170,4.719217,5.244402
175,5.018379,0.010911,3.020958,0.011307,0.008954,4.397714,4.696997,5.416306
176,5.029266,0.004715,3.095903,0.012372,0.008826,4.361766,4.674107,5.315188
177,5.041832,0.009635,3.051312,0.012887,0.010165,4.462956,4.678431,5.289791

           ys       Dps
0    3.723439  0.027880
1    3.736803  0.029817
2    3.755427  0.029535
3    3.766682  0.040626
4    3.768565  0.033697
..        ...       ...
173  5.331930  0.014947
174  5.332679  0.011538
175  5.343477  0.008314
176  5.352381  0.007976
177  5.356727  0.010715

[178 rows x 2 columns]

p,q are: (1,0)
lag (q) now is: 0
X_exog_clean shape is:
 (176, 2)
Y_target_clean shape is:
 (176, 8)
p,q are: (1,1)
lag (q) now is: 0
lag (q) now is: 1
X_exog_clean shape is:
 (175, 4)
Y_target_clean shape is:
 (175, 8)
p,q are: (1,2)
lag (q) now is: 0
lag (q) now is: 1
lag (q) now is: 2
X_exog_clean shape is:
 (174, 6)
Y_target_clean shape is:
 (174, 8)
p,q are: (2,0)
lag (q) now is: 0
X_exog_clean shape is:
 (177, 2)
Y_target_clean shape is:
 (177, 8)
p,q are: (2,1)
lag (q) now is: 0
lag (q) now is: 1
X_exog_clean shape is:
 (176, 4)
Y_target_clean shape is:
 (176, 8)
p,q are: (2,2)
lag (q) now is: 0
lag (q) now is: 1
lag (q) now is: 2
X_exog_clean shape is:
 (175, 6)
Y_target_clean shape is:
 (175, 8)
p,q are: (3,0)
lag (q) now is: 0
X_exog_clean shape is:
 (178, 2)
Y_target_clean shape is:
 (178, 8)
p,q are: (3,1)
lag (q) now is: 0
lag (q) now is: 1
X_exog_clean shape is:
 (177, 4)
Y_target_clean shape is:
 (177, 8)
p,q are: (3,2)
lag (q) now is: 0
lag (q) now is: 1
lag (q) now is: 2
X_exog_clean shape is:
 (176, 6)
Y_target_clean shape is:
 (176, 8)
--- Statsmodels Evaluated Scores ---

   p  q        AIC        BIC       HQIC
0  1  0 -67.836095 -66.244659 -67.190563
1  1  1 -69.152206 -67.264035 -68.386248
2  1  2 -69.424765 -67.237511 -68.537409
3  2  0 -68.243021 -65.494179 -67.128013
4  2  1 -69.267610 -66.217488 -68.030293
5  2  2 -69.620710 -66.266920 -68.260098
6  3  0 -68.192103 -64.285853 -66.607616
7  3  1 -69.262275 -65.050201 -67.553599
8  3  2 -69.663047 -65.142721 -67.829178

df_scores is:
 None
 p  q        AIC        BIC       HQIC
 1  0 -67.836095 -66.244659 -67.190563
 1  1 -69.152206 -67.264035 -68.386248
 1  2 -69.424765 -67.237511 -68.537409
 2  0 -68.243021 -65.494179 -67.128013
 2  1 -69.267610 -66.217488 -68.030293
 2  2 -69.620710 -66.266920 -68.260098
 3  0 -68.192103 -64.285853 -66.607616
 3  1 -69.262275 -65.050201 -67.553599
 3  2 -69.663047 -65.142721 -67.829178

Winning Architecture by AIC: P=3, Q = 2

Winning Architecture by BIC: P=1, Q = 1

Winning Architecture by HQIC: P=1, Q = 2

$ \Large\text{We are working on the VECMX* (1,1) based from the VARX(2,2)} $

$ \Large\text{Here is the formula below so that we can understand which formulas we are going to keep as levels (contemporary and lagged) and change in variables (contemporary and lagged.)} $

$ \Large\text{VARX* is:  } x_{i,t} = a_{i,0} + \Phi_{i,1} x_{i, t-1} + \Phi_{i,2} x_{i,t-2} + \Lambda_{i,0} x^*_{i,t} + \Lambda_{i,1} x^*_{i, t-1} + \Lambda_{i,2} x^*_{i,t-2} + \epsilon_{i,t} $

$ \Large\text{VECMX* is:  } \Delta x_{i,t} = a_{i,0} + \Gamma_{i,1} \Delta x_{i, t-1} + \Psi_{i,0} \Delta x^*_{i,t} + \Psi_{i,1} \Delta x_{i,t-1} + \Pi_{i} z_{i,t-1} + \epsilon_{i,t} $

$ \Large\text{where: } $

$ \Large\text{1. } \Delta x_{i,t} = x_{i,t} - x_{i,t-1} $

$ \Large\text{2. } \Delta x_{i,t-1} = x_{i,t-1} - x_{i,t-2} $

$ \Large\text{3. } \Delta z_{i,t-1} = \begin{bmatrix} y_{i,t-1} \\ x^*_{i,t-1} \end{bmatrix} $

In [6]:
# ok so for the US model below, lets follow the simple example of VARX(2,2) and VECMX(1,1)
# p, q = 2, 2

# Defining the variables for domestic vs. foreign.
endog_vars = ['y', 'Dp', 'eq', 'r', 'lr', 'poil', 'pmat', 'pmetal']
exog_vars = ['ys', 'Dps']

us_endog_df = us_df[endog_vars]
us_exog_df = us_df[exog_vars]

display(us_endog_df)
#display(us_exog_df)

# lets assume that our lags are as follows p_{domestic} = 2, q_{foreign} = 2
# so we are now finding for VAR(p, q) = VAR(2, 2)
# -- USER DEFINED PARAMETERS -- # 
# Once when we are done with the testing we can remove the user defined parameters and use the AIC test to indicate the lags
p, q = 2, 2

max_lag = max(p,q)

# to define the exog data here based on lags (defined by AIC/BIC/HQIC) and shifts (based on also lags?).
us_exog_contemp_df = us_exog_df.iloc[max_lag:] # align to match the loss of p domestic lags.
us_exog_lag1_df = us_exog_df.shift(1).iloc[max_lag:].add_suffix('_lag1') # lag levels of 1
us_exog_lag2_df = us_exog_df.shift(2).iloc[max_lag:].add_suffix('_lag2')  # lag levels of 2
print(f"us_exog_contemp_df is: \n {display(us_exog_contemp_df)}")
print(f"us_exog_lag1_df is: \n {display(us_exog_lag1_df)}")
print(f"us_exog_lag2_df is: \n {display(us_exog_lag2_df)}")

#print(f"us_exog_df shift(1) is: {display(us_exog_df.shift(1))}")
#print(f"us_exog_df shift(1).iloc[p:] is: {display(us_exog_df.shift(1).iloc[p:])}")
#print(f"us_exog_df shift(2) is: {display(us_exog_df.shift(2))}")
#print(f"us_exog_df shift(2).iloc[p:] is: {display(us_exog_df.shift(2).iloc[p:])}")

# Concatenate the exog data here with the shifts and lags. 
us_exog_final_df = pd.concat([us_exog_contemp_df, us_exog_lag1_df, us_exog_lag2_df], axis = 1)
print(f"us_exog_final_df is: {display(us_exog_final_df)}")

# Add in the constant from the exog data. 
us_exog_final_df = sm.add_constant(us_exog_final_df)
print(f"us_exog_final_df after including constant is: {display(us_exog_final_df)}")

# define us endogeneous data
us_endog_final_df = us_endog_df.iloc[p:]
print(f"us_endog_final_df is: \n {display(us_endog_final_df)}")

#--- VECMX Data Prep ---#
# This is where we switch it from VARX(2,2) = VECMX(1,1)
# lets compute the \delta x_{i,t} = x_{i,t} - x_{i,t-1} --> dependent variable 
us_endog_vecm_comtemp_df = us_df[endog_vars]
us_endog_vecm_lag1_df = us_df[endog_vars].shift(1).iloc[max_lag:].add_suffix('_lag1')
us_endog_vecm_lag2_df = us_df[endog_vars].shift(2).iloc[max_lag:].add_suffix('_lag2')
us_endog_vecm_diff1_df = us_df[endog_vars].diff().add_suffix('_diff1')
us_endog_vecm_diff2_df = us_df[endog_vars].shift(1).diff().add_suffix('_diff2')

print(f"us_endog_vecm_comtemp_df is: \n {display(us_endog_vecm_comtemp_df)}")
print(f"us_endog_vecm_lag1_df is: \n {display(us_endog_vecm_lag1_df)}")
print(f"us_endog_vecm_lag2_df is: \n {display(us_endog_vecm_lag2_df)}")
print(f"us_endog_vecm_diff1_df is: \n {display(us_endog_vecm_diff1_df)}")
print(f"us_endog_vecm_diff2_df is: \n {display(us_endog_vecm_diff2_df)}")

us_endog_vecm_final_df = pd.concat([us_endog_vecm_comtemp_df, us_endog_vecm_lag1_df, us_endog_vecm_lag2_df, us_endog_vecm_diff1_df, us_endog_vecm_diff2_df], axis = 1)
print(f"us_endog_vecm_df is: \n {display(us_endog_vecm_final_df)}")

us_exog_final_df = pd.concat([us_exog_contemp_df, us_exog_lag1_df, us_exog_lag2_df], axis = 1)

us_final_vecm_df = pd.concat([us_endog_vecm_final_df, us_exog_final_df], axis = 1).dropna()
print(f"us_final_vecm_df is: \n {display(us_final_vecm_df)}")

# sort the columns
us_final_vecm_df = us_final_vecm_df.sort_index(axis = 1)
print(f"us_final_vecm_df after sorting is: \n {display(us_final_vecm_df)}")

# ---- TO NOTE: WE DO NOT NEED TO RUN VARX FIRST, WE CAN GO AHEAD AND DO VECMX FIRST. ----- #
# Fit the level VARX model via statsmodels 
# we used maxlags = max(p,q) for the domestic variables and passing foreign vectors as exog.
varx_model = VAR(endog = us_endog_final_df, exog = us_exog_final_df)
varx_results = varx_model.fit(maxlags = p)

print(f"--- US VARX({p},{q}) Model Estimated Successfully ---")
print(f"Endogenous Matrix Dimensions (Variables): {us_endog_final_df.shape[1]}")
print(f"Exogenous Matrix Dimensions (Regressors): {us_exog_final_df.shape[1]}")
print(f"\nCoefficient Parameters shape for the US system:", varx_results.params.shape)
print(varx_results.summary())

,y,Dp,eq,r,lr,poil,pmat,pmetal
0,3.960503,0.033730,0.684670,0.022407,0.021804,3.433544,4.148960,4.200168
1,3.967677,0.032477,0.699070,0.023084,0.021781,3.576322,4.272871,4.198063
2,3.970622,0.028823,0.640953,0.027982,0.024841,3.696729,4.220098,4.305733
3,3.973806,0.038217,0.615193,0.031335,0.028302,3.661658,4.311326,4.431295
4,3.953413,0.035451,0.609975,0.022955,0.024909,3.643353,4.207531,4.284341
...,...,...,...,...,...,...,...,...
173,5.008861,0.014444,2.906448,0.006571,0.007648,4.613407,4.814593,5.240803
174,5.015219,0.009122,2.961698,0.009901,0.009396,4.485170,4.719217,5.244402
175,5.018379,0.010911,3.020958,0.011307,0.008954,4.397714,4.696997,5.416306
176,5.029266,0.004715,3.095903,0.012372,0.008826,4.361766,4.674107,5.315188
177,5.041832,0.009635,3.051312,0.012887,0.010165,4.462956,4.678431,5.289791

           ys       Dps
2    3.755427  0.029535
3    3.766682  0.040626
4    3.768565  0.033697
5    3.776422  0.032422
6    3.787429  0.032043
..        ...       ...
173  5.331930  0.014947
174  5.332679  0.011538
175  5.343477  0.008314
176  5.352381  0.007976
177  5.356727  0.010715

[176 rows x 2 columns]

us_exog_contemp_df is:
 None

      ys_lag1  Dps_lag1
2    3.736803  0.029817
3    3.755427  0.029535
4    3.766682  0.040626
5    3.768565  0.033697
6    3.776422  0.032422
..        ...       ...
173  5.320754  0.021158
174  5.331930  0.014947
175  5.332679  0.011538
176  5.343477  0.008314
177  5.352381  0.007976

[176 rows x 2 columns]

us_exog_lag1_df is:
 None

      ys_lag2  Dps_lag2
2    3.723439  0.027880
3    3.736803  0.029817
4    3.755427  0.029535
5    3.766682  0.040626
6    3.768565  0.033697
..        ...       ...
173  5.317501  0.016353
174  5.320754  0.021158
175  5.331930  0.014947
176  5.332679  0.011538
177  5.343477  0.008314

[176 rows x 2 columns]

us_exog_lag2_df is:
 None

           ys       Dps   ys_lag1  Dps_lag1   ys_lag2  Dps_lag2
2    3.755427  0.029535  3.736803  0.029817  3.723439  0.027880
3    3.766682  0.040626  3.755427  0.029535  3.736803  0.029817
4    3.768565  0.033697  3.766682  0.040626  3.755427  0.029535
5    3.776422  0.032422  3.768565  0.033697  3.766682  0.040626
6    3.787429  0.032043  3.776422  0.032422  3.768565  0.033697
..        ...       ...       ...       ...       ...       ...
173  5.331930  0.014947  5.320754  0.021158  5.317501  0.016353
174  5.332679  0.011538  5.331930  0.014947  5.320754  0.021158
175  5.343477  0.008314  5.332679  0.011538  5.331930  0.014947
176  5.352381  0.007976  5.343477  0.008314  5.332679  0.011538
177  5.356727  0.010715  5.352381  0.007976  5.343477  0.008314

[176 rows x 6 columns]

us_exog_final_df is: None

     const        ys       Dps   ys_lag1  Dps_lag1   ys_lag2  Dps_lag2
2      1.0  3.755427  0.029535  3.736803  0.029817  3.723439  0.027880
3      1.0  3.766682  0.040626  3.755427  0.029535  3.736803  0.029817
4      1.0  3.768565  0.033697  3.766682  0.040626  3.755427  0.029535
5      1.0  3.776422  0.032422  3.768565  0.033697  3.766682  0.040626
6      1.0  3.787429  0.032043  3.776422  0.032422  3.768565  0.033697
..     ...       ...       ...       ...       ...       ...       ...
173    1.0  5.331930  0.014947  5.320754  0.021158  5.317501  0.016353
174    1.0  5.332679  0.011538  5.331930  0.014947  5.320754  0.021158
175    1.0  5.343477  0.008314  5.332679  0.011538  5.331930  0.014947
176    1.0  5.352381  0.007976  5.343477  0.008314  5.332679  0.011538
177    1.0  5.356727  0.010715  5.352381  0.007976  5.343477  0.008314

[176 rows x 7 columns]

us_exog_final_df after including constant is: None

,y,Dp,eq,r,lr,poil,pmat,pmetal
2,3.970622,0.028823,0.640953,0.027982,0.024841,3.696729,4.220098,4.305733
3,3.973806,0.038217,0.615193,0.031335,0.028302,3.661658,4.311326,4.431295
4,3.953413,0.035451,0.609975,0.022955,0.024909,3.643353,4.207531,4.284341
5,3.951749,0.018735,0.694921,0.021896,0.025985,3.550055,4.289884,4.277811
6,3.970122,0.025836,0.724808,0.031908,0.029275,3.679337,4.284165,4.195716
...,...,...,...,...,...,...,...,...
173,5.008861,0.014444,2.906448,0.006571,0.007648,4.613407,4.814593,5.240803
174,5.015219,0.009122,2.961698,0.009901,0.009396,4.485170,4.719217,5.244402
175,5.018379,0.010911,3.020958,0.011307,0.008954,4.397714,4.696997,5.416306
176,5.029266,0.004715,3.095903,0.012372,0.008826,4.361766,4.674107,5.315188
177,5.041832,0.009635,3.051312,0.012887,0.010165,4.462956,4.678431,5.289791

us_endog_final_df is:
 None

,y,Dp,eq,r,lr,poil,pmat,pmetal
0,3.960503,0.033730,0.684670,0.022407,0.021804,3.433544,4.148960,4.200168
1,3.967677,0.032477,0.699070,0.023084,0.021781,3.576322,4.272871,4.198063
2,3.970622,0.028823,0.640953,0.027982,0.024841,3.696729,4.220098,4.305733
3,3.973806,0.038217,0.615193,0.031335,0.028302,3.661658,4.311326,4.431295
4,3.953413,0.035451,0.609975,0.022955,0.024909,3.643353,4.207531,4.284341
...,...,...,...,...,...,...,...,...
173,5.008861,0.014444,2.906448,0.006571,0.007648,4.613407,4.814593,5.240803
174,5.015219,0.009122,2.961698,0.009901,0.009396,4.485170,4.719217,5.244402
175,5.018379,0.010911,3.020958,0.011307,0.008954,4.397714,4.696997,5.416306
176,5.029266,0.004715,3.095903,0.012372,0.008826,4.361766,4.674107,5.315188
177,5.041832,0.009635,3.051312,0.012887,0.010165,4.462956,4.678431,5.289791

us_endog_vecm_comtemp_df is:
 None

,y_lag1,Dp_lag1,eq_lag1,r_lag1,lr_lag1,poil_lag1,pmat_lag1,pmetal_lag1
2,3.967677,0.032477,0.699070,0.023084,0.021781,3.576322,4.272871,4.198063
3,3.970622,0.028823,0.640953,0.027982,0.024841,3.696729,4.220098,4.305733
4,3.973806,0.038217,0.615193,0.031335,0.028302,3.661658,4.311326,4.431295
5,3.953413,0.035451,0.609975,0.022955,0.024909,3.643353,4.207531,4.284341
6,3.951749,0.018735,0.694921,0.021896,0.025985,3.550055,4.289884,4.277811
...,...,...,...,...,...,...,...,...
173,5.000886,0.021992,2.973145,0.002677,0.007220,4.733148,4.950379,5.461531
174,5.008861,0.014444,2.906448,0.006571,0.007648,4.613407,4.814593,5.240803
175,5.015219,0.009122,2.961698,0.009901,0.009396,4.485170,4.719217,5.244402
176,5.018379,0.010911,3.020958,0.011307,0.008954,4.397714,4.696997,5.416306
177,5.029266,0.004715,3.095903,0.012372,0.008826,4.361766,4.674107,5.315188

us_endog_vecm_lag1_df is:
 None

,y_lag2,Dp_lag2,eq_lag2,r_lag2,lr_lag2,poil_lag2,pmat_lag2,pmetal_lag2
2,3.960503,0.033730,0.684670,0.022407,0.021804,3.433544,4.148960,4.200168
3,3.967677,0.032477,0.699070,0.023084,0.021781,3.576322,4.272871,4.198063
4,3.970622,0.028823,0.640953,0.027982,0.024841,3.696729,4.220098,4.305733
5,3.973806,0.038217,0.615193,0.031335,0.028302,3.661658,4.311326,4.431295
6,3.953413,0.035451,0.609975,0.022955,0.024909,3.643353,4.207531,4.284341
...,...,...,...,...,...,...,...,...
173,5.002331,0.023214,3.182829,0.000765,0.004804,4.609229,4.892263,5.491054
174,5.000886,0.021992,2.973145,0.002677,0.007220,4.733148,4.950379,5.461531
175,5.008861,0.014444,2.906448,0.006571,0.007648,4.613407,4.814593,5.240803
176,5.015219,0.009122,2.961698,0.009901,0.009396,4.485170,4.719217,5.244402
177,5.018379,0.010911,3.020958,0.011307,0.008954,4.397714,4.696997,5.416306

us_endog_vecm_lag2_df is:
 None

,y_diff1,Dp_diff1,eq_diff1,r_diff1,lr_diff1,poil_diff1,pmat_diff1,pmetal_diff1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.007175,-0.001252,0.014400,0.000677,-0.000023,0.142778,0.123911,-0.002106
2,0.002945,-0.003654,-0.058117,0.004898,0.003059,0.120407,-0.052773,0.107670
3,0.003184,0.009394,-0.025760,0.003353,0.003462,-0.035071,0.091228,0.125562
4,-0.020394,-0.002766,-0.005218,-0.008380,-0.003394,-0.018305,-0.103795,-0.146954
...,...,...,...,...,...,...,...,...
173,0.007974,-0.007547,-0.066698,0.003894,0.000429,-0.119741,-0.135785,-0.220728
174,0.006358,-0.005322,0.055251,0.003330,0.001748,-0.128237,-0.095376,0.003599
175,0.003160,0.001789,0.059260,0.001406,-0.000442,-0.087456,-0.022220,0.171903
176,0.010887,-0.006196,0.074945,0.001065,-0.000129,-0.035948,-0.022890,-0.101118
177,0.012566,0.004920,-0.044590,0.000515,0.001340,0.101189,0.004324,-0.025397

us_endog_vecm_diff1_df is:
 None

,y_diff2,Dp_diff2,eq_diff2,r_diff2,lr_diff2,poil_diff2,pmat_diff2,pmetal_diff2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.007175,-0.001252,0.014400,0.000677,-0.000023,0.142778,0.123911,-0.002106
3,0.002945,-0.003654,-0.058117,0.004898,0.003059,0.120407,-0.052773,0.107670
4,0.003184,0.009394,-0.025760,0.003353,0.003462,-0.035071,0.091228,0.125562
...,...,...,...,...,...,...,...,...
173,-0.001445,-0.001222,-0.209684,0.001912,0.002416,0.123919,0.058115,-0.029523
174,0.007974,-0.007547,-0.066698,0.003894,0.000429,-0.119741,-0.135785,-0.220728
175,0.006358,-0.005322,0.055251,0.003330,0.001748,-0.128237,-0.095376,0.003599
176,0.003160,0.001789,0.059260,0.001406,-0.000442,-0.087456,-0.022220,0.171903
177,0.010887,-0.006196,0.074945,0.001065,-0.000129,-0.035948,-0.022890,-0.101118

us_endog_vecm_diff2_df is:
 None

,y,Dp,eq,r,lr,poil,pmat,pmetal,y_lag1,Dp_lag1,...,pmat_diff1,pmetal_diff1,y_diff2,Dp_diff2,eq_diff2,r_diff2,lr_diff2,poil_diff2,pmat_diff2,pmetal_diff2
0,3.960503,0.033730,0.684670,0.022407,0.021804,3.433544,4.148960,4.200168,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.967677,0.032477,0.699070,0.023084,0.021781,3.576322,4.272871,4.198063,NaN,NaN,...,0.123911,-0.002106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.970622,0.028823,0.640953,0.027982,0.024841,3.696729,4.220098,4.305733,3.967677,0.032477,...,-0.052773,0.107670,0.007175,-0.001252,0.014400,0.000677,-0.000023,0.142778,0.123911,-0.002106
3,3.973806,0.038217,0.615193,0.031335,0.028302,3.661658,4.311326,4.431295,3.970622,0.028823,...,0.091228,0.125562,0.002945,-0.003654,-0.058117,0.004898,0.003059,0.120407,-0.052773,0.107670
4,3.953413,0.035451,0.609975,0.022955,0.024909,3.643353,4.207531,4.284341,3.973806,0.038217,...,-0.103795,-0.146954,0.003184,0.009394,-0.025760,0.003353,0.003462,-0.035071,0.091228,0.125562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,5.008861,0.014444,2.906448,0.006571,0.007648,4.613407,4.814593,5.240803,5.000886,0.021992,...,-0.135785,-0.220728,-0.001445,-0.001222,-0.209684,0.001912,0.002416,0.123919,0.058115,-0.029523
174,5.015219,0.009122,2.961698,0.009901,0.009396,4.485170,4.719217,5.244402,5.008861,0.014444,...,-0.095376,0.003599,0.007974,-0.007547,-0.066698,0.003894,0.000429,-0.119741,-0.135785,-0.220728
175,5.018379,0.010911,3.020958,0.011307,0.008954,4.397714,4.696997,5.416306,5.015219,0.009122,...,-0.022220,0.171903,0.006358,-0.005322,0.055251,0.003330,0.001748,-0.128237,-0.095376,0.003599
176,5.029266,0.004715,3.095903,0.012372,0.008826,4.361766,4.674107,5.315188,5.018379,0.010911,...,-0.022890,-0.101118,0.003160,0.001789,0.059260,0.001406,-0.000442,-0.087456,-0.022220,0.171903
177,5.041832,0.009635,3.051312,0.012887,0.010165,4.462956,4.678431,5.289791,5.029266,0.004715,...,0.004324,-0.025397,0.010887,-0.006196,0.074945,0.001065,-0.000129,-0.035948,-0.022890,-0.101118

us_endog_vecm_df is:
 None

,y,Dp,eq,r,lr,poil,pmat,pmetal,y_lag1,Dp_lag1,...,lr_diff2,poil_diff2,pmat_diff2,pmetal_diff2,ys,Dps,ys_lag1,Dps_lag1,ys_lag2,Dps_lag2
2,3.970622,0.028823,0.640953,0.027982,0.024841,3.696729,4.220098,4.305733,3.967677,0.032477,...,-0.000023,0.142778,0.123911,-0.002106,3.755427,0.029535,3.736803,0.029817,3.723439,0.027880
3,3.973806,0.038217,0.615193,0.031335,0.028302,3.661658,4.311326,4.431295,3.970622,0.028823,...,0.003059,0.120407,-0.052773,0.107670,3.766682,0.040626,3.755427,0.029535,3.736803,0.029817
4,3.953413,0.035451,0.609975,0.022955,0.024909,3.643353,4.207531,4.284341,3.973806,0.038217,...,0.003462,-0.035071,0.091228,0.125562,3.768565,0.033697,3.766682,0.040626,3.755427,0.029535
5,3.951749,0.018735,0.694921,0.021896,0.025985,3.550055,4.289884,4.277811,3.953413,0.035451,...,-0.003394,-0.018305,-0.103795,-0.146954,3.776422,0.032422,3.768565,0.033697,3.766682,0.040626
6,3.970122,0.025836,0.724808,0.031908,0.029275,3.679337,4.284165,4.195716,3.951749,0.018735,...,0.001076,-0.093299,0.082353,-0.006530,3.787429,0.032043,3.776422,0.032422,3.768565,0.033697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,5.008861,0.014444,2.906448,0.006571,0.007648,4.613407,4.814593,5.240803,5.000886,0.021992,...,0.002416,0.123919,0.058115,-0.029523,5.331930,0.014947,5.320754,0.021158,5.317501,0.016353
174,5.015219,0.009122,2.961698,0.009901,0.009396,4.485170,4.719217,5.244402,5.008861,0.014444,...,0.000429,-0.119741,-0.135785,-0.220728,5.332679,0.011538,5.331930,0.014947,5.320754,0.021158
175,5.018379,0.010911,3.020958,0.011307,0.008954,4.397714,4.696997,5.416306,5.015219,0.009122,...,0.001748,-0.128237,-0.095376,0.003599,5.343477,0.008314,5.332679,0.011538,5.331930,0.014947
176,5.029266,0.004715,3.095903,0.012372,0.008826,4.361766,4.674107,5.315188,5.018379,0.010911,...,-0.000442,-0.087456,-0.022220,0.171903,5.352381,0.007976,5.343477,0.008314,5.332679,0.011538
177,5.041832,0.009635,3.051312,0.012887,0.010165,4.462956,4.678431,5.289791,5.029266,0.004715,...,-0.000129,-0.035948,-0.022890,-0.101118,5.356727,0.010715,5.352381,0.007976,5.343477,0.008314

us_final_vecm_df is:
 None

,Dp,Dp_diff1,Dp_diff2,Dp_lag1,Dp_lag2,Dps,Dps_lag1,Dps_lag2,eq,eq_diff1,...,r_lag1,r_lag2,y,y_diff1,y_diff2,y_lag1,y_lag2,ys,ys_lag1,ys_lag2
2,0.028823,-0.003654,-0.001252,0.032477,0.033730,0.029535,0.029817,0.027880,0.640953,-0.058117,...,0.023084,0.022407,3.970622,0.002945,0.007175,3.967677,3.960503,3.755427,3.736803,3.723439
3,0.038217,0.009394,-0.003654,0.028823,0.032477,0.040626,0.029535,0.029817,0.615193,-0.025760,...,0.027982,0.023084,3.973806,0.003184,0.002945,3.970622,3.967677,3.766682,3.755427,3.736803
4,0.035451,-0.002766,0.009394,0.038217,0.028823,0.033697,0.040626,0.029535,0.609975,-0.005218,...,0.031335,0.027982,3.953413,-0.020394,0.003184,3.973806,3.970622,3.768565,3.766682,3.755427
5,0.018735,-0.016716,-0.002766,0.035451,0.038217,0.032422,0.033697,0.040626,0.694921,0.084946,...,0.022955,0.031335,3.951749,-0.001663,-0.020394,3.953413,3.973806,3.776422,3.768565,3.766682
6,0.025836,0.007101,-0.016716,0.018735,0.035451,0.032043,0.032422,0.033697,0.724808,0.029887,...,0.021896,0.022955,3.970122,0.018373,-0.001663,3.951749,3.953413,3.787429,3.776422,3.768565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,0.014444,-0.007547,-0.001222,0.021992,0.023214,0.014947,0.021158,0.016353,2.906448,-0.066698,...,0.002677,0.000765,5.008861,0.007974,-0.001445,5.000886,5.002331,5.331930,5.320754,5.317501
174,0.009122,-0.005322,-0.007547,0.014444,0.021992,0.011538,0.014947,0.021158,2.961698,0.055251,...,0.006571,0.002677,5.015219,0.006358,0.007974,5.008861,5.000886,5.332679,5.331930,5.320754
175,0.010911,0.001789,-0.005322,0.009122,0.014444,0.008314,0.011538,0.014947,3.020958,0.059260,...,0.009901,0.006571,5.018379,0.003160,0.006358,5.015219,5.008861,5.343477,5.332679,5.331930
176,0.004715,-0.006196,0.001789,0.010911,0.009122,0.007976,0.008314,0.011538,3.095903,0.074945,...,0.011307,0.009901,5.029266,0.010887,0.003160,5.018379,5.015219,5.352381,5.343477,5.332679
177,0.009635,0.004920,-0.006196,0.004715,0.010911,0.010715,0.007976,0.008314,3.051312,-0.044590,...,0.012372,0.011307,5.041832,0.012566,0.010887,5.029266,5.018379,5.356727,5.352381,5.343477

us_final_vecm_df after sorting is:
 None
--- US VARX(2,2) Model Estimated Successfully ---
Endogenous Matrix Dimensions (Variables): 8
Exogenous Matrix Dimensions (Regressors): 6

Coefficient Parameters shape for the US system: (23, 8)
  Summary of Regression Results
==================================
Model:                         VAR
Method:                        OLS
Date:           Sun, 26, Jul, 2026
Time:                     20:29:14
--------------------------------------------------------------------
No. of Equations:         8.00000    BIC:                   -65.9430
Nobs:                     174.000    HQIC:                  -67.9285
Log likelihood:           4236.51    FPE:                8.23965e-31
AIC:                     -69.2836    Det(Omega_mle):     3.05192e-31
--------------------------------------------------------------------
Results for equation y
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.248252         0.051928            4.781           0.000
ys                0.741559         0.046088           16.090           0.000
Dps              -0.008405         0.077926           -0.108           0.914
ys_lag1          -0.509029         0.095005           -5.358           0.000
Dps_lag1         -0.026718         0.087174           -0.306           0.759
ys_lag2          -0.193586         0.075862           -2.552           0.011
Dps_lag2          0.139451         0.080058            1.742           0.082
L1.y              0.715334         0.083863            8.530           0.000
L1.Dp            -0.332085         0.116380           -2.853           0.004
L1.eq             0.025684         0.007514            3.418           0.001
L1.r              0.907689         0.350347            2.591           0.010
L1.lr            -0.234346         0.560938           -0.418           0.676
L1.poil           0.002026         0.004240            0.478           0.633
L1.pmat          -0.023929         0.010033           -2.385           0.017
L1.pmetal        -0.000886         0.006427           -0.138           0.890
L2.y              0.185997         0.079471            2.340           0.019
L2.Dp             0.038817         0.101885            0.381           0.703
L2.eq            -0.007954         0.007543           -1.055           0.292
L2.r             -1.394718         0.362003           -3.853           0.000
L2.lr             0.622801         0.533645            1.167           0.243
L2.poil          -0.002846         0.004131           -0.689           0.491
L2.pmat           0.019081         0.009607            1.986           0.047
L2.pmetal         0.003047         0.006442            0.473           0.636
============================================================================

Results for equation Dp
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.068824         0.041880            1.643           0.100
ys                0.125294         0.037170            3.371           0.001
Dps               0.165621         0.062847            2.635           0.008
ys_lag1          -0.099437         0.076621           -1.298           0.194
Dps_lag1         -0.109262         0.070305           -1.554           0.120
ys_lag2          -0.028372         0.061183           -0.464           0.643
Dps_lag2         -0.035786         0.064566           -0.554           0.579
L1.y             -0.064407         0.067635           -0.952           0.341
L1.Dp             0.308746         0.093860            3.289           0.001
L1.eq             0.003460         0.006060            0.571           0.568
L1.r              0.752936         0.282553            2.665           0.008
L1.lr             0.308302         0.452393            0.681           0.496
L1.poil           0.000802         0.003420            0.235           0.815
L1.pmat          -0.005766         0.008092           -0.713           0.476
L1.pmetal         0.001441         0.005183            0.278           0.781
L2.y              0.056807         0.064093            0.886           0.375
L2.Dp             0.141381         0.082170            1.721           0.085
L2.eq            -0.002032         0.006083           -0.334           0.738
L2.r             -0.478435         0.291954           -1.639           0.101
L2.lr            -0.809539         0.430382           -1.881           0.060
L2.poil          -0.003325         0.003332           -0.998           0.318
L2.pmat          -0.002728         0.007748           -0.352           0.725
L2.pmetal         0.005144         0.005195            0.990           0.322
============================================================================

Results for equation eq
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.397697         0.646225            0.615           0.538
ys                0.584705         0.573553            1.019           0.308
Dps              -0.436085         0.969764           -0.450           0.653
ys_lag1          -1.926899         1.182297           -1.630           0.103
Dps_lag1          0.489020         1.084843            0.451           0.652
ys_lag2           1.649287         0.944080            1.747           0.081
Dps_lag2         -1.893897         0.996288           -1.901           0.057
L1.y              1.988688         1.043643            1.906           0.057
L1.Dp            -0.321053         1.448311           -0.222           0.825
L1.eq             0.886317         0.093504            9.479           0.000
L1.r              2.887711         4.359943            0.662           0.508
L1.lr           -15.601303         6.980662           -2.235           0.025
L1.poil          -0.046483         0.052768           -0.881           0.378
L1.pmat          -0.177655         0.124862           -1.423           0.155
L1.pmetal         0.155134         0.079977            1.940           0.052
L2.y             -2.263529         0.988982           -2.289           0.022
L2.Dp             0.944906         1.267920            0.745           0.456
L2.eq            -0.004719         0.093865           -0.050           0.960
L2.r              0.976612         4.504995            0.217           0.828
L2.lr             9.692060         6.641013            1.459           0.144
L2.poil          -0.028451         0.051410           -0.553           0.580
L2.pmat           0.147551         0.119561            1.234           0.217
L2.pmetal        -0.121218         0.080164           -1.512           0.131
============================================================================

Results for equation r
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.015425         0.014206            1.086           0.278
ys                0.016851         0.012608            1.336           0.181
Dps              -0.008794         0.021318           -0.413           0.680
ys_lag1           0.005794         0.025990            0.223           0.824
Dps_lag1          0.005646         0.023848            0.237           0.813
ys_lag2          -0.022299         0.020753           -1.074           0.283
Dps_lag2          0.025500         0.021901            1.164           0.244
L1.y             -0.007615         0.022942           -0.332           0.740
L1.Dp            -0.104101         0.031838           -3.270           0.001
L1.eq             0.002605         0.002055            1.267           0.205
L1.r              1.141189         0.095843           11.907           0.000
L1.lr             0.124226         0.153454            0.810           0.418
L1.poil           0.001502         0.001160            1.294           0.196
L1.pmat          -0.002927         0.002745           -1.066           0.286
L1.pmetal         0.000586         0.001758            0.334           0.739
L2.y              0.004471         0.021740            0.206           0.837
L2.Dp             0.125026         0.027872            4.486           0.000
L2.eq            -0.001549         0.002063           -0.751           0.453
L2.r             -0.275266         0.099032           -2.780           0.005
L2.lr            -0.101795         0.145987           -0.697           0.486
L2.poil          -0.001866         0.001130           -1.651           0.099
L2.pmat           0.001458         0.002628            0.555           0.579
L2.pmetal         0.000130         0.001762            0.074           0.941
============================================================================

Results for equation lr
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.025531         0.010182            2.507           0.012
ys                0.015802         0.009037            1.749           0.080
Dps              -0.000955         0.015280           -0.063           0.950
ys_lag1           0.014431         0.018629            0.775           0.439
Dps_lag1          0.000122         0.017094            0.007           0.994
ys_lag2          -0.030207         0.014876           -2.031           0.042
Dps_lag2          0.023786         0.015698            1.515           0.130
L1.y             -0.019241         0.016444           -1.170           0.242
L1.Dp            -0.018767         0.022821           -0.822           0.411
L1.eq             0.001683         0.001473            1.142           0.253
L1.r              0.092711         0.068699            1.350           0.177
L1.lr             1.038383         0.109993            9.440           0.000
L1.poil           0.000753         0.000831            0.906           0.365
L1.pmat          -0.004036         0.001967           -2.052           0.040
L1.pmetal        -0.000044         0.001260           -0.035           0.972
L2.y              0.015011         0.015583            0.963           0.335
L2.Dp             0.029161         0.019978            1.460           0.144
L2.eq            -0.001209         0.001479           -0.818           0.414
L2.r             -0.015420         0.070984           -0.217           0.828
L2.lr            -0.323630         0.104641           -3.093           0.002
L2.poil          -0.000380         0.000810           -0.469           0.639
L2.pmat           0.002890         0.001884            1.534           0.125
L2.pmetal        -0.000215         0.001263           -0.170           0.865
============================================================================

Results for equation poil
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const            -0.206384         1.265417           -0.163           0.870
ys                5.042029         1.123112            4.489           0.000
Dps               2.447594         1.898960            1.289           0.197
ys_lag1          -4.844279         2.315136           -2.092           0.036
Dps_lag1         -5.687916         2.124305           -2.678           0.007
ys_lag2          -0.111504         1.848668           -0.060           0.952
Dps_lag2          0.799025         1.950899            0.410           0.682
L1.y              0.181717         2.043628            0.089           0.929
L1.Dp            -0.961911         2.836036           -0.339           0.734
L1.eq             0.007469         0.183096            0.041           0.967
L1.r             -6.204938         8.537499           -0.727           0.467
L1.lr            15.987695        13.669307            1.170           0.242
L1.poil           0.970866         0.103329            9.396           0.000
L1.pmat           0.009687         0.244500            0.040           0.968
L1.pmetal         0.266970         0.156608            1.705           0.088
L2.y             -0.024412         1.936592           -0.013           0.990
L2.Dp             1.415204         2.482799            0.570           0.569
L2.eq            -0.110335         0.183804           -0.600           0.548
L2.r              9.442697         8.821535            1.070           0.284
L2.lr           -18.998782        13.004217           -1.461           0.144
L2.poil          -0.142761         0.100670           -1.418           0.156
L2.pmat          -0.203761         0.234121           -0.870           0.384
L2.pmetal        -0.087816         0.156975           -0.559           0.576
============================================================================

Results for equation pmat
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.355742         0.437156            0.814           0.416
ys                0.665086         0.387995            1.714           0.086
Dps               0.873421         0.656022            1.331           0.183
ys_lag1          -0.087029         0.799796           -0.109           0.913
Dps_lag1          1.299262         0.733871            1.770           0.077
ys_lag2          -0.662878         0.638648           -1.038           0.299
Dps_lag2         -1.805196         0.673965           -2.678           0.007
L1.y              0.142137         0.706000            0.201           0.840
L1.Dp            -0.200084         0.979748           -0.204           0.838
L1.eq             0.134402         0.063253            2.125           0.034
L1.r             -5.503996         2.949398           -1.866           0.062
L1.lr             2.502903         4.722253            0.530           0.596
L1.poil          -0.024435         0.035696           -0.685           0.494
L1.pmat           0.991568         0.084466           11.739           0.000
L1.pmetal         0.096932         0.054103            1.792           0.073
L2.y              0.013113         0.669023            0.020           0.984
L2.Dp            -0.153605         0.857718           -0.179           0.858
L2.eq            -0.167332         0.063498           -2.635           0.008
L2.r              4.897296         3.047522            1.607           0.108
L2.lr            -6.942972         4.492488           -1.545           0.122
L2.poil          -0.004079         0.034778           -0.117           0.907
L2.pmat          -0.135608         0.080880           -1.677           0.094
L2.pmetal        -0.050717         0.054229           -0.935           0.350
============================================================================

Results for equation pmetal
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const            -1.560672         0.743130           -2.100           0.036
ys                1.617448         0.659560            2.452           0.014
Dps               1.548453         1.115186            1.389           0.165
ys_lag1          -1.864353         1.359589           -1.371           0.170
Dps_lag1          1.661120         1.247522            1.332           0.183
ys_lag2           0.116794         1.085651            0.108           0.914
Dps_lag2         -0.947693         1.145687           -0.827           0.408
L1.y              1.070001         1.200143            0.892           0.373
L1.Dp            -1.351923         1.665494           -0.812           0.417
L1.eq             0.097265         0.107525            0.905           0.366
L1.r             -0.184115         5.013741           -0.037           0.971
L1.lr            -1.288733         8.027453           -0.161           0.872
L1.poil          -0.000200         0.060681           -0.003           0.997
L1.pmat          -0.039808         0.143585           -0.277           0.782
L1.pmetal         1.133454         0.091970           12.324           0.000
L2.y             -0.355999         1.137285           -0.313           0.754
L2.Dp             0.546034         1.458051            0.374           0.708
L2.eq            -0.242655         0.107941           -2.248           0.025
L2.r              4.121138         5.180545            0.796           0.426
L2.lr            -5.974577         7.636871           -0.782           0.434
L2.poil          -0.001964         0.059119           -0.033           0.973
L2.pmat          -0.050791         0.137490           -0.369           0.712
L2.pmetal        -0.215077         0.092185           -2.333           0.020
============================================================================

Correlation matrix of residuals
                 y        Dp        eq         r        lr      poil      pmat    pmetal
y         1.000000  0.017882  0.071840  0.232620  0.122521  0.042853 -0.095658 -0.045638
Dp        0.017882  1.000000 -0.023521  0.057584  0.246495  0.606593  0.194764  0.264176
eq        0.071840 -0.023521  1.000000  0.083457 -0.124943 -0.031817  0.045463  0.221698
r         0.232620  0.057584  0.083457  1.000000  0.586722  0.081242  0.126931  0.102823
lr        0.122521  0.246495 -0.124943  0.586722  1.000000  0.277386  0.306192  0.230108
poil      0.042853  0.606593 -0.031817  0.081242  0.277386  1.000000  0.284407  0.356245
pmat     -0.095658  0.194764  0.045463  0.126931  0.306192  0.284407  1.000000  0.345705
pmetal   -0.045638  0.264176  0.221698  0.102823  0.230108  0.356245  0.345705  1.000000

In [7]:
# Use Johansens test to find the cointegration (Beta) and speed of adjustment (alpha)
# lets remove the global variables from the us_df data so that we can only find the cointegration 
# relationship between the domestic vars and its foreign vars.

# print(us_df.columns)

endog_vars = ['y', 'Dp', 'eq', 'r', 'lr']
exog_vars = ['ys', 'Dps', 'eps']

us_raw_level_df = pd.concat([us_df[endog_vars], us_df[exog_vars]], axis = 1)
display(us_raw_level_df)
print(f"columns for us_raw_level_df is: {us_raw_level_df.columns}")

# Run the automated Johansens test
# det_order = 0, includes an unrestricted constant intercept in the VECM space. 
# k_ar_diff = 1, enforces 1 lag of short run differences (corresponds to p = 2 for levels).
johansen_res = coint_johansen(us_raw_level_df, det_order = 0, k_ar_diff = 0)

# Rearrange the data to compare the johansens trace stats vs the crit values properly.
ci_level_df = pd.DataFrame(johansen_res.cvt, index = [i for i in range(len(johansen_res.cvt))], columns = ['ci_90%', 'ci_95%', 'ci_99%'])
trace_stats_df = pd.DataFrame(johansen_res.lr1, columns = ['trace_stats'])
max_eigenvalues_df = pd.DataFrame(johansen_res.lr2, columns = ['max_eigenvalue'])
johansen_df = pd.concat([max_eigenvalues_df, trace_stats_df, ci_level_df], axis = 1)
johansen_df['id_90%'] = np.where(johansen_df['trace_stats'] >= johansen_df['ci_90%'],1,0)
johansen_df['id_95%'] = np.where(johansen_df['trace_stats'] >= johansen_df['ci_95%'],1,0)
johansen_df['id_99%'] = np.where(johansen_df['trace_stats'] >= johansen_df['ci_99%'],1,0)
johansen_df['rank_90%'] = johansen_df['id_90%'].cumsum()
johansen_df['rank_95%'] = johansen_df['id_95%'].cumsum()
johansen_df['rank_99%'] = johansen_df['id_99%'].cumsum()


# Extracts the output from the results of the Johansen test. 
print("--- Automation Johansen Statistics ---")
print("Trace Statistics: \n", johansen_res.lr1)
print("\nMax Eigenvalue Statistics:\n", johansen_res.lr2)
print("Critical values (90%, 95%, 99% thresholds):\n", johansen_res.cvt)
print(f"final table for the johansen statistics to see the ranking is as below:")
print(display(johansen_df))

,y,Dp,eq,r,lr,ys,Dps,eps
0,3.960503,0.033730,0.684670,0.022407,0.021804,3.723439,0.027880,-2.381442
1,3.967677,0.032477,0.699070,0.023084,0.021781,3.736803,0.029817,-2.420323
2,3.970622,0.028823,0.640953,0.027982,0.024841,3.755427,0.029535,-2.440535
3,3.973806,0.038217,0.615193,0.031335,0.028302,3.766682,0.040626,-2.465478
4,3.953413,0.035451,0.609975,0.022955,0.024909,3.768565,0.033697,-2.498637
...,...,...,...,...,...,...,...,...
173,5.008861,0.014444,2.906448,0.006571,0.007648,5.331930,0.014947,-3.370713
174,5.015219,0.009122,2.961698,0.009901,0.009396,5.332679,0.011538,-3.365033
175,5.018379,0.010911,3.020958,0.011307,0.008954,5.343477,0.008314,-3.395617
176,5.029266,0.004715,3.095903,0.012372,0.008826,5.352381,0.007976,-3.403638
177,5.041832,0.009635,3.051312,0.012887,0.010165,5.356727,0.010715,-3.408446

columns for us_raw_level_df is: Index(['y', 'Dp', 'eq', 'r', 'lr', 'ys', 'Dps', 'eps'], dtype='str')
--- Automation Johansen Statistics ---
Trace Statistics:
 [261.23338409 126.80606136  87.46034748  52.93295576  34.71010667
  16.68711516   4.90165438   0.93369163]

Max Eigenvalue Statistics:
 [134.42732273  39.34571388  34.52739172  18.22284909  18.02299151
  11.78546078   3.96796275   0.93369163]
Critical values (90%, 95%, 99% thresholds):
 [[153.6341 159.529  171.0905]
 [120.3673 125.6185 135.9825]
 [ 91.109   95.7542 104.9637]
 [ 65.8202  69.8189  77.8202]
 [ 44.4929  47.8545  54.6815]
 [ 27.0669  29.7961  35.4628]
 [ 13.4294  15.4943  19.9349]
 [  2.7055   3.8415   6.6349]]
final table for the johansen statistics to see the ranking is as below:

C:\Users\benchee\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\tsa\vector_ar\vecm.py:731: ComplexWarning: Casting complex values to real discards the imaginary part
  lr1[i] = -t * np.sum(tmp, 0)
C:\Users\benchee\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\tsa\vector_ar\vecm.py:732: ComplexWarning: Casting complex values to real discards the imaginary part
  lr2[i] = -t * np.log(1 - a[i])

,max_eigenvalue,trace_stats,ci_90%,ci_95%,ci_99%,id_90%,id_95%,id_99%,rank_90%,rank_95%,rank_99%
0,134.427323,261.233384,153.6341,159.5290,171.0905,1,1,1,1,1,1
1,39.345714,126.806061,120.3673,125.6185,135.9825,1,1,0,2,2,1
2,34.527392,87.460347,91.1090,95.7542,104.9637,0,0,0,2,2,1
3,18.222849,52.932956,65.8202,69.8189,77.8202,0,0,0,2,2,1
4,18.022992,34.710107,44.4929,47.8545,54.6815,0,0,0,2,2,1
5,11.785461,16.687115,27.0669,29.7961,35.4628,0,0,0,2,2,1
6,3.967963,4.901654,13.4294,15.4943,19.9349,0,0,0,2,2,1
7,0.933692,0.933692,2.7055,3.8415,6.6349,0,0,0,2,2,1

None

In [8]:
# VECMX code.
# Once when we have identified the rankings for the US domestic and foreign variables,
# we can then proceed to compute the VECMX formula to find the cointegration vector
# and the speed of adjustment for the alpha. 

print(us_df.columns)

# obtain the ranking of the trace statistics from johansen using the 95% confidence interval level.
coin_rank = johansen_df['rank_95%'].max()
print(f"cointegration rank for US is: {coin_rank}")

# define domestic/endogenous variables for US. 
endog_vars = ['y','Dp', 'eq', 'r', 'lr']
# define foreign/exogenous variables for US.
exog_vars = ['ys', 'Dps', 'eps', 'poil', 'pmat', 'pmetal']
exog_vars2 = ['ys', 'Dps', 'eps']
# We have hit an issue about the VECM limitation. It is not able to compute the alpha (speed of adjustment)
# for the endog, exog and global vars altogether.
# Gemini has recommended that instead of using VECM model to compute the alpha, 
# we use the VECMX (to include all of the endog + exog vars only) to obtain the long term cointegration for all the variables. 
# and then we manually compute the alpha for all the vars (endog + exog + global)

# obtain all of the endog + exog vars only. 
endog_exog_vars = endog_vars + exog_vars2
print(f"endog_exog_vars is: {endog_exog_vars}")

# join the exog + exog data. 
temp_df = us_df[endog_exog_vars]
# 3. Fit the final VECMX via Statsmodels
# k_ar_diffed = 1: Sets lag of short-run differences (level p = 2 architecture)
# coint_rank = 2: Enforces the 2 unique cointegration vectors found via Trace Statistics from Johansens test. 
# deterministic = 'c': Includes an unrestricted constant intercept in the VECM --> Why? didn't mohaddes use a restricted linear time trend?

temp_model = VECM(
    endog = temp_df,
    k_ar_diff = 1,
    coint_rank = coin_rank,
    deterministic = 'c'
)

temp_results = temp_model.fit()

# 4. Extract and label the structural output matrices. 
# Beta Matrix represents the long-run cointegration vectors (CV1 and CV2)
# Alpha Matrix represents the short-run speed of adjustment parameters. --> What? i thought it was the speed of adjustment for the beta factor?

beta_coefficients = temp_results.beta
alpha_coefficients = temp_results.alpha

print(f"beta_coefficients are: \n {beta_coefficients}")
print(f"alpha_coefficients are: \n {alpha_coefficients}")
print(f"beta_coefficients shape is: \n {beta_coefficients.shape}")
print(f"alpha_coefficients shape is: \n {alpha_coefficients.shape}")


# We are going to compute the manual VECMX here to find the country Alpha. 
start_row = 2 # assuming that the delta change is 1 then the lag has to be 2. 

# calculate the actual Error-Correction Terms: EC = Z_{t-1} * Beta 
# z_{t-1} is the lagged level vector of your joint space variables. 
z_lag1 = temp_model




# formulate readable labels matching the combined long run level vector Z_{t-1}
# statsmodels automatically appends the exogenous variables to the bottom of the beta block
z_variable_names = us_df[endog_vars].columns.tolist() + us_df[exog_vars].columns.tolist()
print(f"z_variable_names is: {z_variable_names}")
beta_output_df = pd.DataFrame(
    beta_coefficients,
    index = z_variable_names,
    columns = ['cv1_gdp_normalized', 'cv2_dp_normalized']
)

alpha_output_df = pd.DataFrame(
    alpha_coefficients,
    index = us_df[endog_vars].columns.tolist(),
    columns = ['a1_adjustment_speed_cv1', 'a1_adjustment_speed_cv2']
)

print(f"--- Step 1: Long-Run BETA Cointegrating Vectors ---")
print(beta_output_df.round(4))

print(f"--- Step 2: Short-Run ALPHA Speed of Adjustment Parameters ---")
print(alpha_output_df.round(4))

Index(['date', 'y', 'Dp', 'eq', 'r', 'lr', 'ys', 'Dps', 'eps', 'poil', 'pmat',
       'pmetal'],
      dtype='str')
cointegration rank for US is: 2
endog_exog_vars is: ['y', 'Dp', 'eq', 'r', 'lr', 'ys', 'Dps', 'eps']
beta_coefficients are:
 [[ 1.00000000e+00 -3.72870620e-19]
 [ 5.75879196e-16  1.00000000e+00]
 [ 4.09665181e-01 -1.83437596e-02]
 [-6.56858225e+01  1.66077994e+00]
 [ 1.05735048e+02 -3.47847197e+00]
 [-1.48604790e+00  2.11372556e-02]
 [-8.83583342e+00  3.54618652e-02]
 [-5.57976330e-01  1.82802987e-02]]
alpha_coefficients are:
 [[-7.54886827e-04 -3.97717768e-01]
 [-6.88694910e-03 -3.41941134e-01]
 [ 1.47307123e-02 -9.51095387e-02]
 [-2.90887156e-04  7.10490480e-03]
 [ 2.15472938e-04  3.08386289e-02]
 [ 9.33919025e-03 -1.17575275e-01]
 [ 1.70622700e-03  8.22973126e-02]
 [-8.49862671e-03 -2.03090501e-01]]
beta_coefficients shape is:
 (8, 2)
alpha_coefficients shape is:
 (8, 2)
z_variable_names is: ['y', 'Dp', 'eq', 'r', 'lr', 'ys', 'Dps', 'eps', 'poil', 'pmat', 'pmetal']

ValueError: Shape of passed values is (8, 2), indices imply (11, 2)

$\Large\text{Gemini hasn't been useful in computing the VECMX and cointegration and alpha (speed of adjustments). I will be focusing solely on Mohaddes's GVAR Matlab code to actually} $ $\Large\text{recreate the logic. I took a look at his code and it seems like he uses mathematical shortcuts to obtain the same results. Lets give this a shot.}$

In [14]:
# to compute the cointegration ranking via Johansens test. 
# we first need to define our short term contemporary variables for the regressors 
# and then we need to define the short-term contemporary variables for the dependent variables (\delta_y_{i,t})
# and then we need to define the lagged level variables for the z variables z_{i,t-1}

endog_vars = ['y', 'Dp', 'eq', 'r', 'lr']
exog_vars = ['ys', 'Dps', 'eps', 'poil', 'pmat', 'pmetal']
# global_vars = ['poil', 'pmat', 'pmetal']

us_endog_vars_df = us_df[endog_vars]
us_exog_vars_df = us_df[exog_vars]
# global_vars_df = us_df[global_vars]

# to make this less complicated we shall assume a lag order of 1 for both p and q. VECMX(1,1)
delta_y = us_endog_vars_df.diff().dropna().add_suffix('_diff1') # dependent variable \delta_y_{i,t}
delta_x = us_exog_vars_df.diff().dropna().add_suffix('_diff1') # independent short term contemp var \delta_x_{i,t}

z0_df = us_endog_vars_df.diff().dropna().add_suffix('_diff1') # \delta_y_{i,t} --> do we need this?
lagged_y_df = us_endog_vars_df.shift(1).add_suffix('_lag1') # lagged levels for y variables y_{i,t-1}
lagged_x_df = us_exog_vars_df.shift(1).add_suffix('_lag1') # lagged levels for x vars x_{i,t-1} --> required for long term cointegration.
display(lagged_y_df, lagged_x_df)
z1_df = pd.concat([lagged_y_df, lagged_x_df], axis = 1).dropna()  # lagged levels 
z2_df = us_exog_vars_df.diff().dropna().add_suffix('_diff1')  # \delta_x_{i,t} = x_{i,t} - x_{i, t-1}
print(f"us_df is: \n {display(us_df)}")
print(f"z0_df is: \n {display(z0_df)}")
print(f"z1_df is: \n {display(z1_df)}")
print(f"z2_df is: \n {display(z2_df)}")


# for ease of reference lets quickly define what z0, z1 and z2 are. 
# z0 = \delta_y_{i,t} --> these are the short run changes of the contemporary endogenous variables. 
# z1 = y_{i, t-1} and x_{i, t-1} --> these are the lagged levels for both exog and endog variables. This will find out the cointegration relationship between all variables. 
# z2 = \delta_x_{i,t} --> these are the short run changes of the contemporary exogenous variables. 

# for exogenous variables because we are taking the short run changes \delta_x_{i,t} is only required as the lag order = 1
# however, if lag p, q are 1 then we only need to include the delta_x_{i,t}. as \delta_y_{i,t} are dependent variables.

# it is time to create the deterministic intercept. 
ones = np.ones((len(z2_df),1))
trend = np.arange(1,z2_df.shape[0] + 1)[:, np.newaxis]
# trend.shape

# for this particular case we will use the estcase = 4 (unrestricted intercept but restricted time trend)
# this is consistent with how Pesaran presented his paper for the GVAR. 
# argument is that due to log spaces of GDP there is a baseline where the rest of the world's GDP follows a specific trend. 
# mathematically this also solves an explosion on the quadratic equation that would blow the VECMX* out of proportion. 

# for estcase = 4, we need to define 2 intercepts and trends into z2_df (short run contemp dynamic changes) and z1_df (lagged levels)
trend2 = trend - 1
#print(f"trend was: {trend}")
#print(f"trend2 now is: {trend2}")
print(f"trend2 shape is: {trend2.shape}")
print(f"z1_df shape is: {z1_df.shape}")
z1_vals = np.concatenate((trend2 , z1_df.values), axis = 1)
print(f"z1_vals is as per below:\n")
#display(z1_vals)
print(f"z1_vals shape is: {z1_vals.shape}")

z2_vals = np.concatenate((ones, z2_df.values), axis = 1)
print(f"z2_vals shape is: {z2_vals.shape}")

# following mohaddes logic by transposing the matrices of z0, z1, and z2
print(f"shape of z1_df is: {z1_df.shape}")
z0_vals_t = z0_df.T.values
z1_vals_t = z1_vals.T
z2_vals_t = z2_vals.T
print(f"z0_vals_t is: {z0_vals_t.shape}")
print(f"z1_vals_t is: {z1_vals_t.shape}")
print(f"z2_vals_t is: {z2_vals_t.shape}")

# define the row numbers + column numbers for endog only. 
n, T = z0_vals_t.shape
print(f"n, T is: ({n}, {T})")

print(f"shape of z0_vals_t is: {z0_vals_t.shape}")
print(f"shape of z2_vals_t.T is: {z2_vals_t.T.shape}")
print(f"shape of m_02 will be: ({z0_vals_t.shape[0]},{z2_vals_t.T.shape[1]})")


# compute the product moment mtrices M_{i,j}
if z2_vals_t.size > 0:
    m_02 = (1/T) * (z0_vals_t) @ z2_vals_t.T
    m_12 = (1/T) * (z1_vals_t) @ z2_vals_t.T
    m_22 = (1/T) * (z2_vals_t) @ z2_vals_t.T

print(f"shapes of m_02, m_12 and m_22 is: {m_02.shape, m_12.shape, m_22.shape}")

# Compute the R_{i,t} series
if z2_vals_t.size > 0:
    r_0 = z0_vals_t - ((m_02 @ np.linalg.inv(m_22)) @ z2_vals_t)
    r_1 = z1_vals_t - ((m_12 @ np.linalg.inv(m_22)) @ z2_vals_t)

print(f"r_0 shape is: {r_0.shape}")
print(f"r_1 shape is: {r_1.shape}")

# Compute the product moment matrices s_{i,j}
s_00 = (r_0 @ r_0.T) * (1/T)
s_01 = (r_0 @ r_1.T) * (1/T)
s_11 = (r_1 @ r_1.T) * (1/T)
s_10 = s_01.T

print(f"s_00, s_01, s_01, s_11 shapes are: {s_00.shape, s_01.shape, s_10.shape, s_11.shape}")

# compute the eigenvalue problem.
# Step 1: obtain the eigenvalues and eigenvectors from s_11 matrix
print(f"s_11 is: \n {s_11}")
# rho, w = la.eig(s_11) # we are trying to compute the eigenvalues (rho) and eigenvectors (W) for s_11?
rho_real, w_real = la.eigh(s_11) # we shall use eigh as it turns imaginary numbers ending with "+j" into actual numbers. 
#print(f"w is: \n {w}")
#print(f"w shape is: \n {w.shape}")
#print(f"rho is: \n {rho}")
#print(f"rho shape is: \n {rho.shape}")

print(f"rho_real is: \n {rho_real}")
print(f"rho_real shape is: \n {rho_real.shape}")
print(f"w_real is: \n {w_real}")
print(f"w_real shape is: \n {w_real.shape}")


# lets export the s_00, s_01, s_10, s_11, rho (eigenvalues), w (eigenvectors) into excel.
s_00_df = pd.DataFrame(s_00, index = z0_df.columns, columns = z0_df.columns)
s_10_df = pd.DataFrame(s_10, index = ['trend1'] + z1_df.columns.tolist(), columns = z0_df.columns)
s_01_df = pd.DataFrame(s_01, index = z0_df.columns, columns = ['trend1'] + z1_df.columns.tolist())
s_11_df = pd.DataFrame(s_11, index = ['trend1'] + z1_df.columns.tolist(), columns = ['trend1'] + z1_df.columns.tolist())
rho_real_df = pd.DataFrame(rho_real, index = [f"eigenvals_{i}" for i in range(1, len(rho_real)+1)], columns = ['eigenvalues'])
w_real_df = pd.DataFrame(w_real, index = ['trend1'] + z1_df.columns.tolist(), columns = [f"var_set_{i}" for i in range(1, (len(w_real)+1))])

print(f"s_00_df is:\n {display(s_00_df)}")
print(f"s_10_df is:\n {display(s_10_df)}")
print(f"s_01_df is:\n {display(s_01_df)}")
print(f"s_11_df is:\n {display(s_11_df)}")
print(f"rho_real_df sorted is:\n {display(rho_real_df)}")
print(f"w_real_df is:\n {display(w_real_df)}")

# 2. get the index positions that would sort abs(rho) in DESCENDING order to obtain the largest eigenvalues.
desc_ind = np.argsort(np.abs(rho_real))[::-1]
print(f"desc_ind is: \n {desc_ind}")

# 3. Apply the sorted indexes to both components. 
rho_real_sorted = rho_real[desc_ind] # we shall use the real values from eigh from now on. 
print(f"rho_real is: \n {rho_real}")
print(f"rho_real_sorted is: \n {rho_real_sorted}")
print(f"rho_real_sorted shape is: \n {rho_real_sorted.shape}")

w_real_sorted = w_real[:, desc_ind] # Rearranges the columns of the eigenvector matrix
print(f"w_real is: \n {w_real}")
print(f"w_real_sorted is: \n {w_real_sorted}")
print(f"w_real_sorted shape is: \n {w_real_sorted.shape}")

rho_real_sorted_df = pd.DataFrame(rho_real_sorted, index = [f"eigenvals_{i}" for i in range(1, len(rho_real)+1)], columns = ['eigenvalues'])
w_real_sorted_df = pd.DataFrame(w_real_sorted, index = ['trend1'] + z1_df.columns.tolist(), columns = [f"var_set_{i}" for i in range(1, (len(w_real)+1))])


file_name = "us_vecm_eig_data.xlsx"
with pd.ExcelWriter(file_name) as writer:
    rho_real_sorted_df.to_excel(writer, sheet_name = 'rho_real_sorted', index = True)
    w_real_sorted_df.to_excel(writer, sheet_name = 'w_real_sorted', index = True)
    s_00_df.to_excel(writer, sheet_name = 's_00', index = True)
    s_10_df.to_excel(writer, sheet_name = 's_10', index = True)
    s_01_df.to_excel(writer, sheet_name = 's_01', index = True)
    s_11_df.to_excel(writer, sheet_name = 's_11', index = True)
print(f"{file_name} has been exported to working folder: ({os.getcwd()}\\{file_name})")

# we are going to use "Spectral decomposition" to compute the generalized eigenvalue problem. 
# by inverting S_11 and then square rooting it. we will be able to have a normalized bounded eigenvalues and eigenvectors that are stable for us to compute the VECM. 
# using the spectral decomposition we will need to obtain the matrix square root of the s_11_half_inv.
# once we obtain the s_11_half_inv we will need to compute the matrix square root form 
# which is sqrt_s11 = w @ s_11_half_inv @ w
rho_inv_sqrt = 1.0 / np.sqrt(rho_real_sorted) # inverted and square rooted
rho_inv_sqrt_diag = np.diag(rho_inv_sqrt) # created a diagonal matrix.
print(f"rho_inv_sqrt_diag is:\n {rho_inv_sqrt_diag}")
print(f"rho_inv_sqrt_diag shape is:\n {rho_inv_sqrt_diag.shape}")

sqrt_inv_half_s11 = (w_real_sorted @ rho_inv_sqrt_diag @ w_real_sorted.T)
print(f"sqrt_inv_half_s11 is: \n {sqrt_inv_half_s11}")
print(f"sqrt_inv_half_s11 shape is: \n {sqrt_inv_half_s11.shape}")

sqrt_inv_half_s11_df = pd.DataFrame(sqrt_inv_half_s11, index = [i for i in range(len(sqrt_inv_half_s11))], columns = [i for i in range(len(sqrt_inv_half_s11))]) 
print(f"sqrt_inv_half_s11_df is:\n {display(sqrt_inv_half_s11_df)}")

# compute the eigenvalue problem now that you have your sqrt_inv_half_s11
middle_term = s_10 @ la.inv(s_00) @ s_01
adj_s11 = (sqrt_inv_half_s11 @ middle_term @ sqrt_inv_half_s11)
print(f"adj_s11 is: \n {adj_s11}")
print(f"adj_s11 shape is: \n {adj_s11.shape}")

adj_s11_df = pd.DataFrame(adj_s11, index = [i for i in range(len(adj_s11))], columns = [i for i in range(len(adj_s11))])
print(f"adj_s11_df is:\n {display(adj_s11_df)}")

# Update - [20260726]: I have done a quick check on the matrix multiplication on the adj_s11 and it looks good. 
# now that we have the adjusted s11 we can finally compute the eigenvalues and eigenvectors.
# now that we have the adj_s11 we can compute its eigenvalues and eigenvectors. 
lambda1, u = la.eigh(adj_s11)
print(f"lambda1 is:\n {lambda1}")
print(f"lambda1 shape is:\n {lambda1.shape}")
print(f"u is:\n {u}")
print(f"u shape is:\n {u.shape}")

# resorting the eigenvalues and eigenvectors according to the largest eigenvalues corresponding to its eigenvectors. 
desc_ind2 = np.argsort(np.abs(lambda1))[::-1]
print(f"desc_ind2 is: {desc_ind2}")
lambda1_sorted = lambda1[desc_ind2]
u_sorted = u[:, desc_ind2]

print(f"lambda1_sorted is:\n {lambda1_sorted}")
print(f"u_sorted is:\n {u_sorted}")

lambda1_sorted_df = pd.DataFrame(lambda1_sorted, index = [f"eigen_vals_{i}" for i in range(1, (len(lambda1_sorted)+1))], columns = ['eigenvalues'])
u_sorted_df = pd.DataFrame(u_sorted, index = ['trend1'] + z1_df.columns.tolist(), columns = [f"eigen_vecs_{i}" for i in range(1, (len(u_sorted)+1))])

print(f"lambda1_sorted_df is:\n {display(lambda1_sorted_df)}")
print(f"u_sorted_df is:\n {display(u_sorted_df)}")

# as per mohaddes code, we shall normalize the U matrix using V' x s_11 x v = I

v = sqrt_inv_half_s11 @ u_sorted
print(f"v is:\n {v}")
print(f"v shape is: \n {v.shape}")


if z0_vals_t.shape[0] < z1_vals_t.shape[0]:
#    print(f"z0_vals_t.shape[0] is: {z0_vals_t.shape[0]}")
#    print(f"z1_vals_t.shape[0] is: {z1_vals_t.shape[0]}")
    endog_rows = z0_vals_t.shape[0]
    lambda1_sorted1 = lambda1_sorted[:endog_rows]
    v2 = v[:, :endog_rows]

print(f"lambda1_sorted1 is:\n {lambda1_sorted1}")
print(f"v2 is:\n {v2}")

# finally! we can estimate the parameters for the VECMX for the US variables.
# for testing purposes we shall define the coint_rank as 2 for US. (it is 2 anyway)
coint_rank = 2
beta = v2[:, :coint_rank]
# alpha = (s_01 @ beta) @ (np.eye())
print(f"beta is: \n {beta}")
print(f"beta shape is: \n {beta.shape}")
print(f"np.eye(len(beta)) is:\n {np.eye(beta.shape[0])}")
ect_variance_matrix = beta.T @ s_11 @ beta # This computes the error correction term variance based on the s_11 matrix.
print(f"ect_variance_matrix is: {ect_variance_matrix}")
print(f"ect_variance_matrix shape is: {ect_variance_matrix.shape}")

final_id_matrix = np.eye(beta.shape[1])

print(f"final_id_matrix is: {final_id_matrix}")
print(f"final_id_matrix is: {final_id_matrix.shape}")
alpha = (s_01 @ beta) @ ((final_id_matrix) @ la.inv(ect_variance_matrix))
print(f"alpha is:\n {alpha}")
print(f"alpha shape is: \n {alpha.shape}")

if z2_vals_t.size > 0:
    psi_coef = (m_02 @ la.inv(m_22)) - ((alpha @ beta.T @ m_12) @ la.inv(m_22))
    epsilon = (z0_vals_t) - (alpha @ beta.T @ z1_vals_t) - (psi_coef @ z2_vals_t)
else:
    psi_coef = []
    epsilon = z0_vals_t - (alpha @ beta.T @ z1_vals_t)

print(f"psi_coef is:\n {psi_coef}")
print(f"psi_coef shape is:\n {psi_coef.shape}")
print(f"epsilon is: \n {epsilon}")
print(f"epsilon shape is: \n {epsilon.shape}")

omega = (1/T) * (epsilon @ epsilon.T)
ecm = beta.T @ z1_vals_t

print(f"omega is:\n {omega}")
print(f"omega shape is:\n {omega.shape}")
print(f"ecm is:\n {ecm}")
print(f"ecm shape is:\n {ecm.shape}")

# lets export the final results so that we can manually do it in excel to ensure that the math sticks. 
# convert beta, s_01, s_11, psi, m_02, m_22, alpha, m_12, epsilon, z0_vals_t, z1_vals_t, z2_vals_t, omega into DataFrames

beta_df = pd.DataFrame(beta, index = ['trend1'] + z1_df.columns.tolist(), columns = ['cv1','cv2'])
alpha_df = pd.DataFrame(alpha, index = z0_df.columns.tolist(), columns = ['alpha1','alpha2'])
m_02_df = pd.DataFrame(m_02, index = z0_df.columns.tolist(), columns = ['intercept'] + z2_df.columns.tolist())
m_22_df = pd.DataFrame(m_22, index = ['intercept'] + z2_df.columns.tolist(), columns = ['intercept'] + z2_df.columns.tolist())
m_12_df = pd.DataFrame(m_12, index = ['trend1'] + z1_df.columns.tolist(), columns = ['intercept'] + z2_df.columns.tolist())
s_11_df = pd.DataFrame(s_11, index = ['trend1'] + z1_df.columns.tolist(), columns = ['trend1'] + z1_df.columns.tolist() )
s_01_df = pd.DataFrame(s_01, index = z0_df.columns.tolist(), columns = ['trend1'] + z1_df.columns.tolist())
z0_vals_t_df = pd.DataFrame(z0_vals_t, index = z0_df.columns.tolist(), columns = [i for i in range(z0_vals_t.shape[1])])
z1_vals_t_df = pd.DataFrame(z1_vals_t, index = ['trend1'] + z1_df.columns.tolist(), columns = [i for i in range(z1_vals_t.shape[1])])
z2_vals_t_df = pd.DataFrame(z2_vals_t, index = ['intercept'] + z2_df.columns.tolist(), columns = [i for i in range(z2_vals_t.shape[1])])
omega_df = pd.DataFrame(omega, index = z0_df.columns.tolist(), columns  = z0_df.columns.tolist())
ecm_df = pd.DataFrame(ecm, index = ['cv1', 'cv2'], columns  = [i for i in range(z1_df.shape[0])])
epsilon_df = pd.DataFrame(epsilon, index = z0_df.columns.tolist(), columns  = [i for i in range(z1_df.shape[0])])
psi_df = pd.DataFrame(psi_coef, index = z0_df.columns.tolist(), columns  = ['intercept'] + z2_df.columns.tolist())

print(f"beta_df is:\n {display(beta_df)}")
print(f"alpha_df is:\n {display(alpha_df)}")
print(f"m_02_df is:\n {display(m_02_df)}")
print(f"m_22_df is:\n {display(m_22_df)}")
print(f"m_12_df is:\n {display(m_12_df)}")
print(f"s_12_df is:\n {display(s_11_df)}")
print(f"s_01_df is:\n {display(s_01_df)}")
print(f"z0_vals_t_df is:\n {display(z0_vals_t_df)}")
print(f"z1_vals_t_df is:\n {display(z1_vals_t_df)}")
print(f"z2_vals_t_df is:\n {display(z2_vals_t_df)}")
print(f"omega_df is:\n {display(omega_df)}")
print(f"ecm_df is:\n {display(ecm_df)}")
print(f"epsilon_df is:\n {display(epsilon_df)}")
print(f"psi_df is:\n {display(psi_df)}")

filename = "vecm_final_results.xlsx"
with pd.ExcelWriter(filename) as writer:
    beta_df.to_excel(writer, sheet_name = 'beta', index = True)
    alpha_df.to_excel(writer, sheet_name = 'alpha', index = True)
    m_02_df.to_excel(writer, sheet_name = 'm_02', index = True)
    m_22_df.to_excel(writer, sheet_name = 'm_22', index = True)
    m_12_df.to_excel(writer, sheet_name = 'm_12', index = True)
    s_11_df.to_excel(writer, sheet_name = 's_11', index = True)
    s_01_df.to_excel(writer, sheet_name = 's_01', index = True)
    z0_vals_t_df.to_excel(writer, sheet_name = 'z0_vals_t', index = True)
    z1_vals_t_df.to_excel(writer, sheet_name = 'z1_vals_t', index = True)
    z2_vals_t_df.to_excel(writer, sheet_name = 'z2_vals_t', index = True)
    omega_df.to_excel(writer, sheet_name = 'omega', index = True)
    ecm_df.to_excel(writer, sheet_name = 'ecm', index = True)
    epsilon_df.to_excel(writer, sheet_name = 'epsilon', index = True)
    psi_df.to_excel(writer, sheet_name = 'psi', index = True)

print(f"{filename} has been exported as Excel via working folder: ({os.getcwd()}\\{filename})")

# to normalize the eigenvectors so that they will follow the order of y, and then Dp for coint_rank = 2
b_top = beta[[1, 2], :] # shape 2 x 2
print(f"b_top is: \n {b_top}")

# post multiply beta by an inverse of b_top block 
# this mathematical trick forces those two rows to become a perfect [[1,0], [0,1]] identity grid.
beta_temasek = beta @ np.linalg.inv(b_top)

print(f"beta_temasek is:\n {beta_temasek}")

       y_lag1   Dp_lag1   eq_lag1    r_lag1   lr_lag1
0         NaN       NaN       NaN       NaN       NaN
1    3.960503  0.033730  0.684670  0.022407  0.021804
2    3.967677  0.032477  0.699070  0.023084  0.021781
3    3.970622  0.028823  0.640953  0.027982  0.024841
4    3.973806  0.038217  0.615193  0.031335  0.028302
..        ...       ...       ...       ...       ...
173  5.000886  0.021992  2.973145  0.002677  0.007220
174  5.008861  0.014444  2.906448  0.006571  0.007648
175  5.015219  0.009122  2.961698  0.009901  0.009396
176  5.018379  0.010911  3.020958  0.011307  0.008954
177  5.029266  0.004715  3.095903  0.012372  0.008826

[178 rows x 5 columns]

      ys_lag1  Dps_lag1  eps_lag1  poil_lag1  pmat_lag1  pmetal_lag1
0         NaN       NaN       NaN        NaN        NaN          NaN
1    3.723439  0.027880 -2.381442   3.433544   4.148960     4.200168
2    3.736803  0.029817 -2.420323   3.576322   4.272871     4.198063
3    3.755427  0.029535 -2.440535   3.696729   4.220098     4.305733
4    3.766682  0.040626 -2.465478   3.661658   4.311326     4.431295
..        ...       ...       ...        ...        ...          ...
173  5.320754  0.021158 -3.376600   4.733148   4.950379     5.461531
174  5.331930  0.014947 -3.370713   4.613407   4.814593     5.240803
175  5.332679  0.011538 -3.365033   4.485170   4.719217     5.244402
176  5.343477  0.008314 -3.395617   4.397714   4.696997     5.416306
177  5.352381  0.007976 -3.403638   4.361766   4.674107     5.315188

[178 rows x 6 columns]

,date,y,Dp,eq,r,lr,ys,Dps,eps,poil,pmat,pmetal
0,1979-06-30,3.960503,0.033730,0.684670,0.022407,0.021804,3.723439,0.027880,-2.381442,3.433544,4.148960,4.200168
1,1979-09-30,3.967677,0.032477,0.699070,0.023084,0.021781,3.736803,0.029817,-2.420323,3.576322,4.272871,4.198063
2,1979-12-31,3.970622,0.028823,0.640953,0.027982,0.024841,3.755427,0.029535,-2.440535,3.696729,4.220098,4.305733
3,1980-03-31,3.973806,0.038217,0.615193,0.031335,0.028302,3.766682,0.040626,-2.465478,3.661658,4.311326,4.431295
4,1980-06-30,3.953413,0.035451,0.609975,0.022955,0.024909,3.768565,0.033697,-2.498637,3.643353,4.207531,4.284341
...,...,...,...,...,...,...,...,...,...,...,...,...
173,2022-09-30,5.008861,0.014444,2.906448,0.006571,0.007648,5.331930,0.014947,-3.370713,4.613407,4.814593,5.240803
174,2022-12-31,5.015219,0.009122,2.961698,0.009901,0.009396,5.332679,0.011538,-3.365033,4.485170,4.719217,5.244402
175,2023-03-31,5.018379,0.010911,3.020958,0.011307,0.008954,5.343477,0.008314,-3.395617,4.397714,4.696997,5.416306
176,2023-06-30,5.029266,0.004715,3.095903,0.012372,0.008826,5.352381,0.007976,-3.403638,4.361766,4.674107,5.315188
177,2023-09-30,5.041832,0.009635,3.051312,0.012887,0.010165,5.356727,0.010715,-3.408446,4.462956,4.678431,5.289791

us_df is:
 None

      y_diff1  Dp_diff1  eq_diff1   r_diff1  lr_diff1
1    0.007175 -0.001252  0.014400  0.000677 -0.000023
2    0.002945 -0.003654 -0.058117  0.004898  0.003059
3    0.003184  0.009394 -0.025760  0.003353  0.003462
4   -0.020394 -0.002766 -0.005218 -0.008380 -0.003394
5   -0.001663 -0.016716  0.084946 -0.001059  0.001076
..        ...       ...       ...       ...       ...
173  0.007974 -0.007547 -0.066698  0.003894  0.000429
174  0.006358 -0.005322  0.055251  0.003330  0.001748
175  0.003160  0.001789  0.059260  0.001406 -0.000442
176  0.010887 -0.006196  0.074945  0.001065 -0.000129
177  0.012566  0.004920 -0.044590  0.000515  0.001340

[177 rows x 5 columns]

z0_df is:
 None

,y_lag1,Dp_lag1,eq_lag1,r_lag1,lr_lag1,ys_lag1,Dps_lag1,eps_lag1,poil_lag1,pmat_lag1,pmetal_lag1
1,3.960503,0.033730,0.684670,0.022407,0.021804,3.723439,0.027880,-2.381442,3.433544,4.148960,4.200168
2,3.967677,0.032477,0.699070,0.023084,0.021781,3.736803,0.029817,-2.420323,3.576322,4.272871,4.198063
3,3.970622,0.028823,0.640953,0.027982,0.024841,3.755427,0.029535,-2.440535,3.696729,4.220098,4.305733
4,3.973806,0.038217,0.615193,0.031335,0.028302,3.766682,0.040626,-2.465478,3.661658,4.311326,4.431295
5,3.953413,0.035451,0.609975,0.022955,0.024909,3.768565,0.033697,-2.498637,3.643353,4.207531,4.284341
...,...,...,...,...,...,...,...,...,...,...,...
173,5.000886,0.021992,2.973145,0.002677,0.007220,5.320754,0.021158,-3.376600,4.733148,4.950379,5.461531
174,5.008861,0.014444,2.906448,0.006571,0.007648,5.331930,0.014947,-3.370713,4.613407,4.814593,5.240803
175,5.015219,0.009122,2.961698,0.009901,0.009396,5.332679,0.011538,-3.365033,4.485170,4.719217,5.244402
176,5.018379,0.010911,3.020958,0.011307,0.008954,5.343477,0.008314,-3.395617,4.397714,4.696997,5.416306
177,5.029266,0.004715,3.095903,0.012372,0.008826,5.352381,0.007976,-3.403638,4.361766,4.674107,5.315188

z1_df is:
 None

     ys_diff1  Dps_diff1  eps_diff1  poil_diff1  pmat_diff1  pmetal_diff1
1    0.013364   0.001937  -0.038881    0.142778    0.123911     -0.002106
2    0.018624  -0.000282  -0.020211    0.120407   -0.052773      0.107670
3    0.011254   0.011091  -0.024944   -0.035071    0.091228      0.125562
4    0.001883  -0.006929  -0.033159   -0.018305   -0.103795     -0.146954
5    0.007858  -0.001275  -0.040097   -0.093299    0.082353     -0.006530
..        ...        ...        ...         ...         ...           ...
173  0.011176  -0.006211   0.005886   -0.119741   -0.135785     -0.220728
174  0.000749  -0.003409   0.005680   -0.128237   -0.095376      0.003599
175  0.010798  -0.003223  -0.030584   -0.087456   -0.022220      0.171903
176  0.008904  -0.000338  -0.008021   -0.035948   -0.022890     -0.101118
177  0.004346   0.002739  -0.004809    0.101189    0.004324     -0.025397

[177 rows x 6 columns]

z2_df is:
 None
trend2 shape is: (177, 1)
z1_df shape is: (177, 11)
z1_vals is as per below:

z1_vals shape is: (177, 12)
z2_vals shape is: (177, 7)
shape of z1_df is: (177, 11)
z0_vals_t is: (5, 177)
z1_vals_t is: (12, 177)
z2_vals_t is: (7, 177)
n, T is: (5, 177)
shape of z0_vals_t is: (5, 177)
shape of z2_vals_t.T is: (177, 7)
shape of m_02 will be: (5,7)
shapes of m_02, m_12 and m_22 is: ((5, 7), (12, 7), (7, 7))
r_0 shape is: (5, 177)
r_1 shape is: (12, 177)
s_00, s_01, s_01, s_11 shapes are: ((5, 5), (5, 12), (12, 5), (12, 12))
s_11 is:
 [[ 2.49693552e+03  1.55382625e+01 -1.35636371e-01  3.39021269e+01
  -3.57444213e-01 -3.62166811e-01  2.42797158e+01 -6.34539619e-01
  -1.50503225e+01  2.25845065e+01  8.11007485e+00  2.06493788e+01]
 [ 1.55382625e+01  9.91141318e-02 -9.17519538e-04  2.18649010e-01
  -2.28433071e-03 -2.31500207e-03  1.52533592e-01 -4.18738125e-03
  -9.39362047e-02  1.33275256e-01  5.30271017e-02  1.24075591e-01]
 [-1.35636371e-01 -9.17519538e-04  5.17162456e-05 -1.88628809e-03
   3.27485443e-05  2.56366572e-05 -1.39620795e-03  4.30239477e-05
   7.65622923e-04  6.39201155e-05 -4.79247277e-04 -3.66624769e-04]
 [ 3.39021269e+01  2.18649010e-01 -1.88628809e-03  5.20058293e-01
  -4.81363130e-03 -5.10284043e-03  3.30555921e-01 -9.36586618e-03
  -1.98136705e-01  2.40939466e-01  1.14494483e-01  2.43047984e-01]
 [-3.57444213e-01 -2.28433071e-03  3.27485443e-05 -4.81363130e-03
   7.04375629e-05  6.10931859e-05 -3.54957112e-03  9.64921350e-05
   2.21710686e-03 -2.74068300e-03 -1.38153233e-03 -2.64632228e-03]
 [-3.62166811e-01 -2.31500207e-03  2.56366572e-05 -5.10284043e-03
   6.10931859e-05  6.00181729e-05 -3.57035169e-03  9.90316426e-05
   2.22386484e-03 -2.80590122e-03 -1.33433433e-03 -2.80088645e-03]
 [ 2.42797158e+01  1.52533592e-01 -1.39620795e-03  3.30555921e-01
  -3.54957112e-03 -3.57035169e-03  2.37828692e-01 -6.35281260e-03
  -1.48167915e-01  2.22466755e-01  8.16568709e-02  2.01956328e-01]
 [-6.34539619e-01 -4.18738125e-03  4.30239477e-05 -9.36586618e-03
   9.64921350e-05  9.90316426e-05 -6.35281260e-03  2.50661605e-04
   3.92055824e-03 -5.76812767e-03 -1.94652692e-03 -4.42565000e-03]
 [-1.50503225e+01 -9.39362047e-02  7.65622923e-04 -1.98136705e-01
   2.21710686e-03  2.22386484e-03 -1.48167915e-01  3.92055824e-03
   9.77090656e-02 -1.51901051e-01 -5.63016681e-02 -1.38463519e-01]
 [ 2.25845065e+01  1.33275256e-01  6.39201155e-05  2.40939466e-01
  -2.74068300e-03 -2.80590122e-03  2.22466755e-01 -5.76812767e-03
  -1.51901051e-01  4.25368625e-01  6.51965491e-02  2.88004054e-01]
 [ 8.11007485e+00  5.30271017e-02 -4.79247277e-04  1.14494483e-01
  -1.38153233e-03 -1.33433433e-03  8.16568709e-02 -1.94652692e-03
  -5.63016681e-02  6.51965491e-02  4.71779396e-02  7.82154685e-02]
 [ 2.06493788e+01  1.24075591e-01 -3.66624769e-04  2.43047984e-01
  -2.64632228e-03 -2.80088645e-03  2.01956328e-01 -4.42565000e-03
  -1.38463519e-01  2.88004054e-01  7.82154685e-02  2.58216135e-01]]
rho_real is:
 [1.50085570e-06 1.29769673e-05 2.36618356e-05 3.85394840e-05
 1.81922745e-04 1.64286814e-03 2.40529267e-03 1.35360599e-02
 3.73279311e-02 4.38894970e-02 3.01351319e-01 2.49822101e+03]
rho_real shape is:
 (12,)
w_real is:
 [[ 4.64012586e-05 -6.86101166e-05 -5.29097069e-04  8.46510037e-04
   3.01247535e-03 -5.05226276e-03 -7.90434077e-03 -2.12148143e-03
   1.68619467e-02  8.45155231e-03  7.49927926e-03  9.99742679e-01]
 [ 4.87082582e-03 -7.18904170e-04 -6.14124119e-02 -6.36629944e-02
   6.66682450e-01  6.59529073e-01  2.64145581e-01  1.41849363e-01
  -1.38704824e-01 -4.82498080e-02  3.47462630e-02  6.22134817e-03]
 [-4.77300934e-02  2.54113995e-01  9.47015030e-01 -1.20599187e-01
   1.35689297e-01 -4.84624441e-02 -2.69658021e-02 -1.24454610e-02
  -9.95241198e-03 -1.46881154e-03 -4.77873896e-03 -5.43006401e-05]
 [-3.29589207e-03  4.69235046e-03 -1.04232019e-02 -7.33137300e-03
  -6.06674603e-02 -1.22087450e-01  9.15510620e-03 -1.87165887e-01
  -9.14908947e-01 -1.36495176e-01  3.00383735e-01  1.35739769e-02]
 [ 4.93937369e-01 -8.33840150e-01  2.33776876e-01 -5.97212163e-02
   3.93487915e-02 -2.30298176e-02 -4.46290271e-03 -1.97558458e-02
  -4.67622371e-03  2.05663550e-03 -1.78897318e-03 -1.43114180e-04]
 [-8.67377829e-01 -4.86556674e-01  7.39333825e-02 -6.79530688e-02
   2.31174331e-02 -1.09805691e-02 -9.67916575e-03 -8.36060233e-03
   7.69645137e-04  3.48984673e-03 -1.78140369e-03 -1.45006508e-04]
 [-7.09168251e-03 -1.67307985e-02  1.40530197e-01 -4.71455586e-02
  -7.19000965e-01  5.30717056e-01  3.57388677e-01  2.12862501e-01
  -6.01113999e-02 -4.74381437e-02 -8.94398993e-03  9.72134105e-03]
 [ 3.59912138e-02  5.34101660e-02 -1.36582369e-01 -9.83001245e-01
  -3.59294129e-02 -2.74138809e-02 -8.75561951e-02 -2.49024534e-02
   2.09411157e-02 -1.16156402e-02 -1.90132483e-03 -2.54064821e-04]
 [ 1.97204687e-03 -2.62077913e-03  2.52692160e-02  5.87945662e-02
  -1.13104075e-01  5.06323545e-01 -7.44181603e-01 -3.49265600e-01
  -5.04101810e-03  2.13646531e-01  7.23778999e-02 -6.02607046e-03]
 [ 1.92886304e-03  4.93045354e-06 -1.09134470e-02 -4.92095906e-03
   1.05458420e-02 -2.53824242e-02 -9.57975572e-02  2.03597522e-01
  -3.64996042e-01  3.42205013e-01 -8.35499965e-01  9.04336110e-03]
 [ 2.49992382e-03 -1.45842453e-02  1.59194985e-03  3.01087586e-02
  -2.88887303e-04 -3.58245786e-03 -4.75666453e-01  6.69894284e-01
  -5.40301100e-02 -5.66414241e-01  9.34045288e-03  3.24726894e-03]
 [-3.05078789e-03  4.96093755e-03 -8.38093392e-04  1.62001668e-02
  -1.39078003e-02  8.75113064e-02  6.78623624e-02 -5.34883881e-01
   5.54803520e-02 -7.02133551e-01 -4.52777268e-01  8.26825540e-03]]
w_real shape is:
 (12, 12)

               y_diff1      Dp_diff1  eq_diff1       r_diff1      lr_diff1
y_diff1   3.990936e-05  7.724033e-06  0.000043  2.814251e-06  9.262473e-07
Dp_diff1  7.724033e-06  2.287870e-05  0.000015  8.342304e-07  4.541498e-07
eq_diff1  4.341513e-05  1.489177e-05  0.004603 -3.628297e-06 -1.337661e-05
r_diff1   2.814251e-06  8.342304e-07 -0.000004  2.727584e-06  1.052414e-06
lr_diff1  9.262473e-07  4.541498e-07 -0.000013  1.052414e-06  1.147512e-06

s_00_df is:
 None

              y_diff1      Dp_diff1      eq_diff1       r_diff1      lr_diff1
trend1       0.017953  9.150484e-03 -4.318803e-02  8.283112e-03  1.670187e-03
y_lag1       0.000044  4.228407e-05 -7.750219e-04  4.682216e-05  6.481957e-06
Dp_lag1     -0.000013 -1.773416e-05 -8.697311e-05  3.960783e-07  1.718423e-06
eq_lag1      0.000345  7.408105e-05 -2.775377e-03  1.141687e-04  3.071452e-05
r_lag1      -0.000004 -2.201251e-06 -2.958034e-06 -1.662256e-06  1.556226e-07
lr_lag1     -0.000003 -2.568718e-06 -4.734820e-07 -1.542809e-06 -5.700711e-07
ys_lag1      0.000109  8.032164e-05 -7.431391e-04  7.364664e-05  1.151973e-05
Dps_lag1     0.000005 -8.339685e-07 -3.244022e-05 -7.005868e-07  3.572784e-07
eps_lag1     0.000011 -3.358048e-05  2.097734e-04 -5.517320e-05 -1.997367e-05
poil_lag1   -0.000493 -2.110507e-04 -4.945902e-03  9.666710e-05  6.645858e-05
pmat_lag1   -0.000013 -7.318919e-06 -7.131213e-04  5.295121e-05  1.634260e-05
pmetal_lag1 -0.000163 -2.230725e-05 -1.953254e-03  1.195067e-04  6.054641e-05

s_10_df is:
 None

,trend1,y_lag1,Dp_lag1,eq_lag1,r_lag1,lr_lag1,ys_lag1,Dps_lag1,eps_lag1,poil_lag1,pmat_lag1,pmetal_lag1
y_diff1,0.017953,0.000044,-1.288881e-05,0.000345,-4.328986e-06,-2.959040e-06,0.000109,4.659427e-06,0.000011,-0.000493,-0.000013,-0.000163
Dp_diff1,0.009150,0.000042,-1.773416e-05,0.000074,-2.201251e-06,-2.568718e-06,0.000080,-8.339685e-07,-0.000034,-0.000211,-0.000007,-0.000022
eq_diff1,-0.043188,-0.000775,-8.697311e-05,-0.002775,-2.958034e-06,-4.734820e-07,-0.000743,-3.244022e-05,0.000210,-0.004946,-0.000713,-0.001953
r_diff1,0.008283,0.000047,3.960783e-07,0.000114,-1.662256e-06,-1.542809e-06,0.000074,-7.005868e-07,-0.000055,0.000097,0.000053,0.000120
lr_diff1,0.001670,0.000006,1.718423e-06,0.000031,1.556226e-07,-5.700711e-07,0.000012,3.572784e-07,-0.000020,0.000066,0.000016,0.000061

s_01_df is:
 None

,trend1,y_lag1,Dp_lag1,eq_lag1,r_lag1,lr_lag1,ys_lag1,Dps_lag1,eps_lag1,poil_lag1,pmat_lag1,pmetal_lag1
trend1,2496.935520,15.538262,-0.135636,33.902127,-0.357444,-0.362167,24.279716,-0.634540,-15.050322,22.584506,8.110075,20.649379
y_lag1,15.538262,0.099114,-0.000918,0.218649,-0.002284,-0.002315,0.152534,-0.004187,-0.093936,0.133275,0.053027,0.124076
Dp_lag1,-0.135636,-0.000918,0.000052,-0.001886,0.000033,0.000026,-0.001396,0.000043,0.000766,0.000064,-0.000479,-0.000367
eq_lag1,33.902127,0.218649,-0.001886,0.520058,-0.004814,-0.005103,0.330556,-0.009366,-0.198137,0.240939,0.114494,0.243048
r_lag1,-0.357444,-0.002284,0.000033,-0.004814,0.000070,0.000061,-0.003550,0.000096,0.002217,-0.002741,-0.001382,-0.002646
lr_lag1,-0.362167,-0.002315,0.000026,-0.005103,0.000061,0.000060,-0.003570,0.000099,0.002224,-0.002806,-0.001334,-0.002801
ys_lag1,24.279716,0.152534,-0.001396,0.330556,-0.003550,-0.003570,0.237829,-0.006353,-0.148168,0.222467,0.081657,0.201956
Dps_lag1,-0.634540,-0.004187,0.000043,-0.009366,0.000096,0.000099,-0.006353,0.000251,0.003921,-0.005768,-0.001947,-0.004426
eps_lag1,-15.050322,-0.093936,0.000766,-0.198137,0.002217,0.002224,-0.148168,0.003921,0.097709,-0.151901,-0.056302,-0.138464
poil_lag1,22.584506,0.133275,0.000064,0.240939,-0.002741,-0.002806,0.222467,-0.005768,-0.151901,0.425369,0.065197,0.288004
pmat_lag1,8.110075,0.053027,-0.000479,0.114494,-0.001382,-0.001334,0.081657,-0.001947,-0.056302,0.065197,0.047178,0.078215
pmetal_lag1,20.649379,0.124076,-0.000367,0.243048,-0.002646,-0.002801,0.201956,-0.004426,-0.138464,0.288004,0.078215,0.258216

s_11_df is:
 None

              eigenvalues
eigenvals_1      0.000002
eigenvals_2      0.000013
eigenvals_3      0.000024
eigenvals_4      0.000039
eigenvals_5      0.000182
eigenvals_6      0.001643
eigenvals_7      0.002405
eigenvals_8      0.013536
eigenvals_9      0.037328
eigenvals_10     0.043889
eigenvals_11     0.301351
eigenvals_12  2498.221014

rho_real_df sorted is:
 None

,var_set_1,var_set_2,var_set_3,var_set_4,var_set_5,var_set_6,var_set_7,var_set_8,var_set_9,var_set_10,var_set_11,var_set_12
trend1,0.000046,-0.000069,-0.000529,0.000847,0.003012,-0.005052,-0.007904,-0.002121,0.016862,0.008452,0.007499,0.999743
y_lag1,0.004871,-0.000719,-0.061412,-0.063663,0.666682,0.659529,0.264146,0.141849,-0.138705,-0.048250,0.034746,0.006221
Dp_lag1,-0.047730,0.254114,0.947015,-0.120599,0.135689,-0.048462,-0.026966,-0.012445,-0.009952,-0.001469,-0.004779,-0.000054
eq_lag1,-0.003296,0.004692,-0.010423,-0.007331,-0.060667,-0.122087,0.009155,-0.187166,-0.914909,-0.136495,0.300384,0.013574
r_lag1,0.493937,-0.833840,0.233777,-0.059721,0.039349,-0.023030,-0.004463,-0.019756,-0.004676,0.002057,-0.001789,-0.000143
lr_lag1,-0.867378,-0.486557,0.073933,-0.067953,0.023117,-0.010981,-0.009679,-0.008361,0.000770,0.003490,-0.001781,-0.000145
ys_lag1,-0.007092,-0.016731,0.140530,-0.047146,-0.719001,0.530717,0.357389,0.212863,-0.060111,-0.047438,-0.008944,0.009721
Dps_lag1,0.035991,0.053410,-0.136582,-0.983001,-0.035929,-0.027414,-0.087556,-0.024902,0.020941,-0.011616,-0.001901,-0.000254
eps_lag1,0.001972,-0.002621,0.025269,0.058795,-0.113104,0.506324,-0.744182,-0.349266,-0.005041,0.213647,0.072378,-0.006026
poil_lag1,0.001929,0.000005,-0.010913,-0.004921,0.010546,-0.025382,-0.095798,0.203598,-0.364996,0.342205,-0.835500,0.009043
pmat_lag1,0.002500,-0.014584,0.001592,0.030109,-0.000289,-0.003582,-0.475666,0.669894,-0.054030,-0.566414,0.009340,0.003247
pmetal_lag1,-0.003051,0.004961,-0.000838,0.016200,-0.013908,0.087511,0.067862,-0.534884,0.055480,-0.702134,-0.452777,0.008268

w_real_df is:
 None
desc_ind is:
 [11 10  9  8  7  6  5  4  3  2  1  0]
rho_real is:
 [1.50085570e-06 1.29769673e-05 2.36618356e-05 3.85394840e-05
 1.81922745e-04 1.64286814e-03 2.40529267e-03 1.35360599e-02
 3.73279311e-02 4.38894970e-02 3.01351319e-01 2.49822101e+03]
rho_real_sorted is:
 [2.49822101e+03 3.01351319e-01 4.38894970e-02 3.73279311e-02
 1.35360599e-02 2.40529267e-03 1.64286814e-03 1.81922745e-04
 3.85394840e-05 2.36618356e-05 1.29769673e-05 1.50085570e-06]
rho_real_sorted shape is:
 (12,)
w_real is:
 [[ 4.64012586e-05 -6.86101166e-05 -5.29097069e-04  8.46510037e-04
   3.01247535e-03 -5.05226276e-03 -7.90434077e-03 -2.12148143e-03
   1.68619467e-02  8.45155231e-03  7.49927926e-03  9.99742679e-01]
 [ 4.87082582e-03 -7.18904170e-04 -6.14124119e-02 -6.36629944e-02
   6.66682450e-01  6.59529073e-01  2.64145581e-01  1.41849363e-01
  -1.38704824e-01 -4.82498080e-02  3.47462630e-02  6.22134817e-03]
 [-4.77300934e-02  2.54113995e-01  9.47015030e-01 -1.20599187e-01
   1.35689297e-01 -4.84624441e-02 -2.69658021e-02 -1.24454610e-02
  -9.95241198e-03 -1.46881154e-03 -4.77873896e-03 -5.43006401e-05]
 [-3.29589207e-03  4.69235046e-03 -1.04232019e-02 -7.33137300e-03
  -6.06674603e-02 -1.22087450e-01  9.15510620e-03 -1.87165887e-01
  -9.14908947e-01 -1.36495176e-01  3.00383735e-01  1.35739769e-02]
 [ 4.93937369e-01 -8.33840150e-01  2.33776876e-01 -5.97212163e-02
   3.93487915e-02 -2.30298176e-02 -4.46290271e-03 -1.97558458e-02
  -4.67622371e-03  2.05663550e-03 -1.78897318e-03 -1.43114180e-04]
 [-8.67377829e-01 -4.86556674e-01  7.39333825e-02 -6.79530688e-02
   2.31174331e-02 -1.09805691e-02 -9.67916575e-03 -8.36060233e-03
   7.69645137e-04  3.48984673e-03 -1.78140369e-03 -1.45006508e-04]
 [-7.09168251e-03 -1.67307985e-02  1.40530197e-01 -4.71455586e-02
  -7.19000965e-01  5.30717056e-01  3.57388677e-01  2.12862501e-01
  -6.01113999e-02 -4.74381437e-02 -8.94398993e-03  9.72134105e-03]
 [ 3.59912138e-02  5.34101660e-02 -1.36582369e-01 -9.83001245e-01
  -3.59294129e-02 -2.74138809e-02 -8.75561951e-02 -2.49024534e-02
   2.09411157e-02 -1.16156402e-02 -1.90132483e-03 -2.54064821e-04]
 [ 1.97204687e-03 -2.62077913e-03  2.52692160e-02  5.87945662e-02
  -1.13104075e-01  5.06323545e-01 -7.44181603e-01 -3.49265600e-01
  -5.04101810e-03  2.13646531e-01  7.23778999e-02 -6.02607046e-03]
 [ 1.92886304e-03  4.93045354e-06 -1.09134470e-02 -4.92095906e-03
   1.05458420e-02 -2.53824242e-02 -9.57975572e-02  2.03597522e-01
  -3.64996042e-01  3.42205013e-01 -8.35499965e-01  9.04336110e-03]
 [ 2.49992382e-03 -1.45842453e-02  1.59194985e-03  3.01087586e-02
  -2.88887303e-04 -3.58245786e-03 -4.75666453e-01  6.69894284e-01
  -5.40301100e-02 -5.66414241e-01  9.34045288e-03  3.24726894e-03]
 [-3.05078789e-03  4.96093755e-03 -8.38093392e-04  1.62001668e-02
  -1.39078003e-02  8.75113064e-02  6.78623624e-02 -5.34883881e-01
   5.54803520e-02 -7.02133551e-01 -4.52777268e-01  8.26825540e-03]]
w_real_sorted is:
 [[ 9.99742679e-01  7.49927926e-03  8.45155231e-03  1.68619467e-02
  -2.12148143e-03 -7.90434077e-03 -5.05226276e-03  3.01247535e-03
   8.46510037e-04 -5.29097069e-04 -6.86101166e-05  4.64012586e-05]
 [ 6.22134817e-03  3.47462630e-02 -4.82498080e-02 -1.38704824e-01
   1.41849363e-01  2.64145581e-01  6.59529073e-01  6.66682450e-01
  -6.36629944e-02 -6.14124119e-02 -7.18904170e-04  4.87082582e-03]
 [-5.43006401e-05 -4.77873896e-03 -1.46881154e-03 -9.95241198e-03
  -1.24454610e-02 -2.69658021e-02 -4.84624441e-02  1.35689297e-01
  -1.20599187e-01  9.47015030e-01  2.54113995e-01 -4.77300934e-02]
 [ 1.35739769e-02  3.00383735e-01 -1.36495176e-01 -9.14908947e-01
  -1.87165887e-01  9.15510620e-03 -1.22087450e-01 -6.06674603e-02
  -7.33137300e-03 -1.04232019e-02  4.69235046e-03 -3.29589207e-03]
 [-1.43114180e-04 -1.78897318e-03  2.05663550e-03 -4.67622371e-03
  -1.97558458e-02 -4.46290271e-03 -2.30298176e-02  3.93487915e-02
  -5.97212163e-02  2.33776876e-01 -8.33840150e-01  4.93937369e-01]
 [-1.45006508e-04 -1.78140369e-03  3.48984673e-03  7.69645137e-04
  -8.36060233e-03 -9.67916575e-03 -1.09805691e-02  2.31174331e-02
  -6.79530688e-02  7.39333825e-02 -4.86556674e-01 -8.67377829e-01]
 [ 9.72134105e-03 -8.94398993e-03 -4.74381437e-02 -6.01113999e-02
   2.12862501e-01  3.57388677e-01  5.30717056e-01 -7.19000965e-01
  -4.71455586e-02  1.40530197e-01 -1.67307985e-02 -7.09168251e-03]
 [-2.54064821e-04 -1.90132483e-03 -1.16156402e-02  2.09411157e-02
  -2.49024534e-02 -8.75561951e-02 -2.74138809e-02 -3.59294129e-02
  -9.83001245e-01 -1.36582369e-01  5.34101660e-02  3.59912138e-02]
 [-6.02607046e-03  7.23778999e-02  2.13646531e-01 -5.04101810e-03
  -3.49265600e-01 -7.44181603e-01  5.06323545e-01 -1.13104075e-01
   5.87945662e-02  2.52692160e-02 -2.62077913e-03  1.97204687e-03]
 [ 9.04336110e-03 -8.35499965e-01  3.42205013e-01 -3.64996042e-01
   2.03597522e-01 -9.57975572e-02 -2.53824242e-02  1.05458420e-02
  -4.92095906e-03 -1.09134470e-02  4.93045354e-06  1.92886304e-03]
 [ 3.24726894e-03  9.34045288e-03 -5.66414241e-01 -5.40301100e-02
   6.69894284e-01 -4.75666453e-01 -3.58245786e-03 -2.88887303e-04
   3.01087586e-02  1.59194985e-03 -1.45842453e-02  2.49992382e-03]
 [ 8.26825540e-03 -4.52777268e-01 -7.02133551e-01  5.54803520e-02
  -5.34883881e-01  6.78623624e-02  8.75113064e-02 -1.39078003e-02
   1.62001668e-02 -8.38093392e-04  4.96093755e-03 -3.05078789e-03]]
w_real_sorted shape is:
 (12, 12)
us_vecm_eig_data.xlsx has been exported to working folder: (C:\Users\benchee\us_vecm_eig_data.xlsx)
rho_inv_sqrt_diag is:
 [[2.00071197e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.82164377e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.77331064e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 5.17586619e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  8.59515803e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 2.03899441e+01 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.46716756e+01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 7.41406688e+01
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.61082015e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 2.05577596e+02 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.77596123e+02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 8.16263789e+02]]
rho_inv_sqrt_diag shape is:
 (12, 12)
sqrt_inv_half_s11 is:
 [[ 2.47030955e-02  6.27823848e-03 -8.61742565e-02 -7.74550280e-02
   1.34040943e-02 -3.24682212e-02 -3.16972662e-01 -1.07551779e-01
   5.23744834e-02 -1.14474236e-02  4.17612776e-02 -4.26115560e-02]
 [ 6.27823848e-03  4.68408248e+01 -5.19472618e+00 -4.26412879e+00
   1.31609843e+00 -2.68785427e+00 -2.59809918e+01  9.20102421e+00
  -2.74033293e+00  1.66776252e-01 -1.96390364e+00  3.74429430e-01]
 [-8.61742565e-02 -5.19472618e+00  2.07937259e+02 -1.83129537e+00
  -3.09627076e+01  1.54367845e+01  1.92875480e+01 -5.40788464e+00
   2.21711440e+00 -1.91288039e+00 -1.20323331e+00 -2.27701310e-01]
 [-7.74550280e-02 -4.26412879e+00 -1.83129537e+00  5.57520064e+00
  -2.90224028e+00  1.55541401e+00  1.42222549e+00  1.60154631e+00
  -8.01434206e-01  7.55903906e-01 -5.89060377e-01  6.16429349e-01]
 [ 1.34040943e-02  1.31609843e+00 -3.09627076e+01 -2.90224028e+00
   4.04098332e+02 -2.32805602e+02  5.75399827e+00  4.96293201e+00
   1.56190696e+00  3.33640830e-01  4.09705860e+00 -2.58686866e+00]
 [-3.24682212e-02 -2.68785427e+00  1.54367845e+01  1.55541401e+00
  -2.32805602e+02  6.81741498e+02  8.46979067e+00 -2.40471801e+01
  -1.45749572e+00 -1.44214289e+00 -6.89726826e-02  1.26735815e+00]
 [-3.16972662e-01 -2.59809918e+01  1.92875480e+01  1.42222549e+00
   5.75399827e+00  8.46979067e+00  5.28370491e+01  3.93186120e+00
   6.83322465e+00 -1.45952716e+00 -2.25660776e+00  1.39962091e+00]
 [-1.07551779e-01  9.20102421e+00 -5.40788464e+00  1.60154631e+00
   4.96293201e+00 -2.40471801e+01  3.93186120e+00  1.61615228e+02
  -8.65067729e+00  1.20325388e+00 -4.22050878e+00 -2.54003205e+00]
 [ 5.23744834e-02 -2.74033293e+00  2.21711440e+00 -8.01434206e-01
   1.56190696e+00 -1.45749572e+00  6.83322465e+00 -8.65067729e+00
   2.05346661e+01  5.85058453e-01  4.89739839e+00  1.14916132e+00]
 [-1.14474236e-02  1.66776252e-01 -1.91288039e+00  7.55903906e-01
   3.33640830e-01 -1.44214289e+00 -1.45952716e+00  1.20325388e+00
   5.85058453e-01  3.11910494e+00  1.24254827e+00 -1.71260302e+00]
 [ 4.17612776e-02 -1.96390364e+00 -1.20323331e+00 -5.89060377e-01
   4.09705860e+00 -6.89726826e-02 -2.25660776e+00 -4.22050878e+00
   4.89739839e+00  1.24254827e+00  1.02282321e+01 -1.81829504e+00]
 [-4.26115560e-02  3.74429430e-01 -2.27701310e-01  6.16429349e-01
  -2.58686866e+00  1.26735815e+00  1.39962091e+00 -2.54003205e+00
   1.14916132e+00 -1.71260302e+00 -1.81829504e+00  5.55569891e+00]]
sqrt_inv_half_s11 shape is:
 (12, 12)

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.024703,0.006278,-0.086174,-0.077455,0.013404,-0.032468,-0.316973,-0.107552,0.052374,-0.011447,0.041761,-0.042612
1,0.006278,46.840825,-5.194726,-4.264129,1.316098,-2.687854,-25.980992,9.201024,-2.740333,0.166776,-1.963904,0.374429
2,-0.086174,-5.194726,207.937259,-1.831295,-30.962708,15.436785,19.287548,-5.407885,2.217114,-1.912880,-1.203233,-0.227701
3,-0.077455,-4.264129,-1.831295,5.575201,-2.902240,1.555414,1.422225,1.601546,-0.801434,0.755904,-0.589060,0.616429
4,0.013404,1.316098,-30.962708,-2.902240,404.098332,-232.805602,5.753998,4.962932,1.561907,0.333641,4.097059,-2.586869
5,-0.032468,-2.687854,15.436785,1.555414,-232.805602,681.741498,8.469791,-24.047180,-1.457496,-1.442143,-0.068973,1.267358
6,-0.316973,-25.980992,19.287548,1.422225,5.753998,8.469791,52.837049,3.931861,6.833225,-1.459527,-2.256608,1.399621
7,-0.107552,9.201024,-5.407885,1.601546,4.962932,-24.047180,3.931861,161.615228,-8.650677,1.203254,-4.220509,-2.540032
8,0.052374,-2.740333,2.217114,-0.801434,1.561907,-1.457496,6.833225,-8.650677,20.534666,0.585058,4.897398,1.149161
9,-0.011447,0.166776,-1.912880,0.755904,0.333641,-1.442143,-1.459527,1.203254,0.585058,3.119105,1.242548,-1.712603
10,0.041761,-1.963904,-1.203233,-0.589060,4.097059,-0.068973,-2.256608,-4.220509,4.897398,1.242548,10.228232,-1.818295
11,-0.042612,0.374429,-0.227701,0.616429,-2.586869,1.267358,1.399621,-2.540032,1.149161,-1.712603,-1.818295,5.555699

sqrt_inv_half_s11_df is:
 None
adj_s11 is:
 [[ 1.36857337e-02 -1.16622376e-02 -3.16562853e-02  5.51139795e-05
  -1.81656641e-02  1.16223835e-03 -1.05466420e-02  3.49506516e-04
   1.39892090e-02 -1.07830717e-02  9.61253764e-03  4.97542144e-03]
 [-1.16622376e-02  1.31718095e-01  7.59305841e-02 -7.29567416e-04
   1.06802744e-02  1.75426307e-02  1.79076133e-02  1.07666242e-03
  -3.39125118e-02  7.55897364e-02  2.22358627e-02  2.68173028e-02]
 [-3.16562853e-02  7.59305841e-02  4.30579024e-01  8.51348365e-02
  -4.53086395e-02  3.91310451e-02 -2.73520991e-02  2.13844129e-02
  -3.25020557e-02  1.54669644e-01  5.92312039e-02  3.32762026e-02]
 [ 5.51139795e-05 -7.29567416e-04  8.51348365e-02  6.28912541e-02
  -2.15205186e-02 -1.05123919e-03 -5.38632283e-03  4.95253051e-02
   2.02136317e-02  5.35353596e-02  2.41302349e-02  1.08031761e-02]
 [-1.81656641e-02  1.06802744e-02 -4.53086395e-02 -2.15205186e-02
   7.22559162e-02 -6.96025949e-02  3.40625321e-04 -8.97043007e-03
  -5.00767047e-02 -8.22895283e-03 -3.42021049e-02  3.15254302e-03]
 [ 1.16223835e-03  1.75426307e-02  3.91310451e-02 -1.05123919e-03
  -6.96025949e-02  1.38969186e-01  5.35589755e-02 -8.80050894e-04
   6.17908566e-02 -2.46813264e-04  1.70550450e-02 -3.47655484e-02]
 [-1.05466420e-02  1.79076133e-02 -2.73520991e-02 -5.38632283e-03
   3.40625321e-04  5.35589755e-02  4.80412518e-02  8.87174402e-03
   2.13217853e-02 -4.06578331e-03 -1.22385314e-02 -2.61129781e-02]
 [ 3.49506516e-04  1.07666242e-03  2.13844129e-02  4.95253051e-02
  -8.97043007e-03 -8.80050894e-04  8.87174402e-03  4.88615333e-02
   2.33342307e-02  3.61207755e-02  1.25415475e-02  3.22733467e-03]
 [ 1.39892090e-02 -3.39125118e-02 -3.25020557e-02  2.02136317e-02
  -5.00767047e-02  6.17908566e-02  2.13217853e-02  2.33342307e-02
   6.09121620e-02 -1.52261072e-02  1.21902305e-02 -2.04513377e-02]
 [-1.07830717e-02  7.55897364e-02  1.54669644e-01  5.35353596e-02
  -8.22895283e-03 -2.46813264e-04 -4.06578331e-03  3.61207755e-02
  -1.52261072e-02  9.63363093e-02  3.40545079e-02  2.91202647e-02]
 [ 9.61253764e-03  2.22358627e-02  5.92312039e-02  2.41302349e-02
  -3.42021049e-02  1.70550450e-02 -1.22385314e-02  1.25415475e-02
   1.21902305e-02  3.40545079e-02  2.99352049e-02  1.63253090e-02]
 [ 4.97542144e-03  2.68173028e-02  3.32762026e-02  1.08031761e-02
   3.15254302e-03 -3.47655484e-02 -2.61129781e-02  3.22733467e-03
  -2.04513377e-02  2.91202647e-02  1.63253090e-02  2.69028593e-02]]
adj_s11 shape is:
 (12, 12)

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.013686,-0.011662,-0.031656,0.000055,-0.018166,0.001162,-0.010547,0.000350,0.013989,-0.010783,0.009613,0.004975
1,-0.011662,0.131718,0.075931,-0.000730,0.010680,0.017543,0.017908,0.001077,-0.033913,0.075590,0.022236,0.026817
2,-0.031656,0.075931,0.430579,0.085135,-0.045309,0.039131,-0.027352,0.021384,-0.032502,0.154670,0.059231,0.033276
3,0.000055,-0.000730,0.085135,0.062891,-0.021521,-0.001051,-0.005386,0.049525,0.020214,0.053535,0.024130,0.010803
4,-0.018166,0.010680,-0.045309,-0.021521,0.072256,-0.069603,0.000341,-0.008970,-0.050077,-0.008229,-0.034202,0.003153
5,0.001162,0.017543,0.039131,-0.001051,-0.069603,0.138969,0.053559,-0.000880,0.061791,-0.000247,0.017055,-0.034766
6,-0.010547,0.017908,-0.027352,-0.005386,0.000341,0.053559,0.048041,0.008872,0.021322,-0.004066,-0.012239,-0.026113
7,0.000350,0.001077,0.021384,0.049525,-0.008970,-0.000880,0.008872,0.048862,0.023334,0.036121,0.012542,0.003227
8,0.013989,-0.033913,-0.032502,0.020214,-0.050077,0.061791,0.021322,0.023334,0.060912,-0.015226,0.012190,-0.020451
9,-0.010783,0.075590,0.154670,0.053535,-0.008229,-0.000247,-0.004066,0.036121,-0.015226,0.096336,0.034055,0.029120
10,0.009613,0.022236,0.059231,0.024130,-0.034202,0.017055,-0.012239,0.012542,0.012190,0.034055,0.029935,0.016325
11,0.004975,0.026817,0.033276,0.010803,0.003153,-0.034766,-0.026113,0.003227,-0.020451,0.029120,0.016325,0.026903

adj_s11_df is:
 None
lambda1 is:
 [-1.90467089e-15 -7.03886914e-17 -3.37557150e-17 -9.13292171e-18
  2.15620188e-17  4.79578698e-17  6.07982394e-17  7.52712792e-02
  1.16255360e-01  1.50766777e-01  2.50368168e-01  5.68426945e-01]
lambda1 shape is:
 (12,)
u is:
 [[ 2.51193658e-01  6.95881527e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00 -5.62334478e-01 -3.27707622e-01
   1.09936869e-01 -9.82358021e-02 -6.65449789e-02  5.36066638e-02]
 [-2.48519083e-01  2.82244536e-01  3.22102015e-02 -1.55733314e-02
   1.98507849e-01 -8.67601452e-03  2.46286220e-01 -2.13609408e-01
   2.72478165e-01  7.52181514e-01  1.40688507e-01 -2.27409552e-01]
 [ 6.02001304e-02  1.40642466e-01  9.41640254e-02  6.32182127e-03
   2.03512573e-01 -7.37184478e-02 -1.02491563e-04  1.18301456e-01
  -4.03297957e-01 -1.71256558e-01  2.19243267e-02 -8.45211845e-01]
 [-5.98786695e-02  2.74964002e-01 -3.79124670e-01 -4.21325612e-01
  -2.22365014e-01  2.83519324e-01  3.20785562e-01  2.05532465e-01
   4.32492377e-01 -3.03931229e-01 -7.15917482e-02 -2.00082364e-01]
 [-8.00359954e-02 -1.37122161e-02  1.50925629e-04 -5.76694169e-01
   1.32685091e-01 -2.30865475e-01 -3.96384492e-01  4.59070424e-01
  -4.07673307e-02  1.54643692e-01  4.31033429e-01  1.03407169e-01]
 [-1.59612869e-01 -2.09869935e-01 -3.11399367e-01 -2.19405387e-01
   3.20761326e-02  2.27098721e-01 -3.60571859e-01  1.88035440e-02
  -1.79380777e-01  3.17671414e-01 -6.79330277e-01 -8.84278872e-02]
 [ 7.41125749e-01  1.07069968e-01  4.76748396e-02  8.66043364e-02
  -4.87734572e-02 -9.35334635e-02  1.75956218e-01  4.67892188e-01
   5.40634073e-02  3.28325007e-01 -2.36994190e-01  3.99748488e-02]
 [-1.25812189e-01 -1.07856580e-01 -1.59097139e-01  4.31380027e-01
   5.33998382e-01 -8.79119173e-02 -2.36342705e-01  3.08335333e-01
   5.26941605e-01 -1.63428492e-01 -7.85571014e-02 -8.23331708e-02]
 [-1.44215243e-01  4.26185401e-02  7.23169199e-01 -3.33675457e-01
   1.65384848e-01 -1.70635324e-01  1.13196532e-01  3.51212608e-03
   2.09835975e-01 -1.59899631e-01 -4.49008495e-01  5.07012214e-02]
 [-3.72898218e-04 -2.74125268e-01  2.95262460e-01  1.31523845e-01
  -6.21762746e-01  6.88089160e-02 -3.58822852e-01  4.34621239e-02
   3.76427832e-01  1.23043151e-01  9.76908015e-02 -3.63358444e-01]
 [ 1.96648069e-01 -2.43866108e-01 -3.21308414e-01 -2.01213078e-01
  -5.04029678e-02 -7.34793481e-01  5.02794904e-02 -3.80982030e-01
   1.86554597e-01 -4.77921759e-02 -9.63091303e-02 -1.47083812e-01]
 [ 4.59873626e-01 -3.70053107e-01  9.17226092e-02 -2.80666659e-01
   3.83512990e-01  4.67958181e-01 -4.66168370e-02 -3.44381044e-01
   1.70320945e-01 -2.32833696e-02  2.00319693e-01 -8.87260456e-02]]
u shape is:
 (12, 12)
desc_ind2 is: [11 10  9  8  7  0  1  6  5  2  4  3]
lambda1_sorted is:
 [ 5.68426945e-01  2.50368168e-01  1.50766777e-01  1.16255360e-01
  7.52712792e-02 -1.90467089e-15 -7.03886914e-17  6.07982394e-17
  4.79578698e-17 -3.37557150e-17  2.15620188e-17 -9.13292171e-18]
u_sorted is:
 [[ 5.36066638e-02 -6.65449789e-02 -9.82358021e-02  1.09936869e-01
  -3.27707622e-01  2.51193658e-01  6.95881527e-01 -5.62334478e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.27409552e-01  1.40688507e-01  7.52181514e-01  2.72478165e-01
  -2.13609408e-01 -2.48519083e-01  2.82244536e-01  2.46286220e-01
  -8.67601452e-03  3.22102015e-02  1.98507849e-01 -1.55733314e-02]
 [-8.45211845e-01  2.19243267e-02 -1.71256558e-01 -4.03297957e-01
   1.18301456e-01  6.02001304e-02  1.40642466e-01 -1.02491563e-04
  -7.37184478e-02  9.41640254e-02  2.03512573e-01  6.32182127e-03]
 [-2.00082364e-01 -7.15917482e-02 -3.03931229e-01  4.32492377e-01
   2.05532465e-01 -5.98786695e-02  2.74964002e-01  3.20785562e-01
   2.83519324e-01 -3.79124670e-01 -2.22365014e-01 -4.21325612e-01]
 [ 1.03407169e-01  4.31033429e-01  1.54643692e-01 -4.07673307e-02
   4.59070424e-01 -8.00359954e-02 -1.37122161e-02 -3.96384492e-01
  -2.30865475e-01  1.50925629e-04  1.32685091e-01 -5.76694169e-01]
 [-8.84278872e-02 -6.79330277e-01  3.17671414e-01 -1.79380777e-01
   1.88035440e-02 -1.59612869e-01 -2.09869935e-01 -3.60571859e-01
   2.27098721e-01 -3.11399367e-01  3.20761326e-02 -2.19405387e-01]
 [ 3.99748488e-02 -2.36994190e-01  3.28325007e-01  5.40634073e-02
   4.67892188e-01  7.41125749e-01  1.07069968e-01  1.75956218e-01
  -9.35334635e-02  4.76748396e-02 -4.87734572e-02  8.66043364e-02]
 [-8.23331708e-02 -7.85571014e-02 -1.63428492e-01  5.26941605e-01
   3.08335333e-01 -1.25812189e-01 -1.07856580e-01 -2.36342705e-01
  -8.79119173e-02 -1.59097139e-01  5.33998382e-01  4.31380027e-01]
 [ 5.07012214e-02 -4.49008495e-01 -1.59899631e-01  2.09835975e-01
   3.51212608e-03 -1.44215243e-01  4.26185401e-02  1.13196532e-01
  -1.70635324e-01  7.23169199e-01  1.65384848e-01 -3.33675457e-01]
 [-3.63358444e-01  9.76908015e-02  1.23043151e-01  3.76427832e-01
   4.34621239e-02 -3.72898218e-04 -2.74125268e-01 -3.58822852e-01
   6.88089160e-02  2.95262460e-01 -6.21762746e-01  1.31523845e-01]
 [-1.47083812e-01 -9.63091303e-02 -4.77921759e-02  1.86554597e-01
  -3.80982030e-01  1.96648069e-01 -2.43866108e-01  5.02794904e-02
  -7.34793481e-01 -3.21308414e-01 -5.04029678e-02 -2.01213078e-01]
 [-8.87260456e-02  2.00319693e-01 -2.32833696e-02  1.70320945e-01
  -3.44381044e-01  4.59873626e-01 -3.70053107e-01 -4.66168370e-02
   4.67958181e-01  9.17226092e-02  3.83512990e-01 -2.80666659e-01]]

                eigenvalues
eigen_vals_1   5.684269e-01
eigen_vals_2   2.503682e-01
eigen_vals_3   1.507668e-01
eigen_vals_4   1.162554e-01
eigen_vals_5   7.527128e-02
eigen_vals_6  -1.904671e-15
eigen_vals_7  -7.038869e-17
eigen_vals_8   6.079824e-17
eigen_vals_9   4.795787e-17
eigen_vals_10 -3.375572e-17
eigen_vals_11  2.156202e-17
eigen_vals_12 -9.132922e-18

lambda1_sorted_df is:
 None

,eigen_vecs_1,eigen_vecs_2,eigen_vecs_3,eigen_vecs_4,eigen_vecs_5,eigen_vecs_6,eigen_vecs_7,eigen_vecs_8,eigen_vecs_9,eigen_vecs_10,eigen_vecs_11,eigen_vecs_12
trend1,0.053607,-0.066545,-0.098236,0.109937,-0.327708,0.251194,0.695882,-0.562334,0.000000,0.000000,0.000000,0.000000
y_lag1,-0.227410,0.140689,0.752182,0.272478,-0.213609,-0.248519,0.282245,0.246286,-0.008676,0.032210,0.198508,-0.015573
Dp_lag1,-0.845212,0.021924,-0.171257,-0.403298,0.118301,0.060200,0.140642,-0.000102,-0.073718,0.094164,0.203513,0.006322
eq_lag1,-0.200082,-0.071592,-0.303931,0.432492,0.205532,-0.059879,0.274964,0.320786,0.283519,-0.379125,-0.222365,-0.421326
r_lag1,0.103407,0.431033,0.154644,-0.040767,0.459070,-0.080036,-0.013712,-0.396384,-0.230865,0.000151,0.132685,-0.576694
lr_lag1,-0.088428,-0.679330,0.317671,-0.179381,0.018804,-0.159613,-0.209870,-0.360572,0.227099,-0.311399,0.032076,-0.219405
ys_lag1,0.039975,-0.236994,0.328325,0.054063,0.467892,0.741126,0.107070,0.175956,-0.093533,0.047675,-0.048773,0.086604
Dps_lag1,-0.082333,-0.078557,-0.163428,0.526942,0.308335,-0.125812,-0.107857,-0.236343,-0.087912,-0.159097,0.533998,0.431380
eps_lag1,0.050701,-0.449008,-0.159900,0.209836,0.003512,-0.144215,0.042619,0.113197,-0.170635,0.723169,0.165385,-0.333675
poil_lag1,-0.363358,0.097691,0.123043,0.376428,0.043462,-0.000373,-0.274125,-0.358823,0.068809,0.295262,-0.621763,0.131524
pmat_lag1,-0.147084,-0.096309,-0.047792,0.186555,-0.380982,0.196648,-0.243866,0.050279,-0.734793,-0.321308,-0.050403,-0.201213
pmetal_lag1,-0.088726,0.200320,-0.023283,0.170321,-0.344381,0.459874,-0.370053,-0.046617,0.467958,0.091723,0.383513,-0.280667

u_sorted_df is:
 None
v is:
 [[ 9.31240423e-02  7.71063088e-02 -6.49267479e-02 -5.56367071e-02
  -2.13027954e-01 -2.32113125e-01 -1.92079295e-02 -4.70207031e-02
  -4.73781976e-02  5.07339122e-02 -4.29709814e-02 -5.78869817e-02]
 [-6.77415481e+00  1.61195677e+01  2.72774118e+01  1.60720453e+01
  -1.96474307e+01 -3.16046288e+01  8.27159716e+00  3.38051419e+00
   1.57190927e+00 -4.96188190e-01  1.51438782e+01  3.81048392e+00]
 [-1.76553806e+02 -2.51260647e+01 -3.21479943e+01 -8.99093826e+01
   1.92555015e+01  2.82255900e+01  2.80449102e+01  1.04267211e+01
  -6.21003749e+00  1.84796779e+01  3.57815644e+01  1.52882725e+01]
 [ 6.01873317e-01 -3.19061192e+00 -4.09517716e+00  2.85098171e+00
   1.76382986e+00  1.71569400e+00 -6.14931202e-01  8.22982378e-01
   3.41217874e+00 -3.20584864e+00 -2.34465922e+00  1.64693365e-01]
 [ 8.82316038e+01  3.28709953e+02 -3.55732577e+00  4.05822404e+01
   1.80159508e+02  5.83318233e+00  3.85599663e+01 -7.66232143e+01
  -1.50153035e+02  6.99427090e+01  4.19774570e+01 -1.78892188e+02]
 [-9.44415151e+01 -5.62967692e+02  1.82173147e+02 -1.31948588e+02
  -9.52539577e+01 -7.86033005e+01 -1.34685690e+02 -1.46218990e+02
   2.10010776e+02 -2.08663476e+02 -1.88691605e+01 -2.55211374e+01]
 [-7.97631098e+00 -2.21307108e+01 -4.15803987e+00 -1.04012537e+01
   3.73011330e+01  4.35198899e+01 -3.49438299e-01 -1.61478422e+00
  -4.43913207e+00  5.06104831e+00  1.69738837e+00 -1.38805790e+00]
 [-8.38695069e+00  9.81515815e+00 -2.28302986e+01  9.22722724e+01
   5.37613554e+01 -1.74641738e+01 -8.55900507e+00 -2.94651432e+01
  -1.69381374e+01 -2.36336119e+01  8.34272030e+01  7.62267328e+01]
 [ 1.94455616e-01 -8.96409033e+00 -2.23897908e+00 -3.34394933e-01
  -2.78735280e-01  5.66580911e+00  3.98808237e-01  4.49880416e+00
  -7.46161163e+00  1.61351317e+01 -1.48056278e+00 -1.14094625e+01]
 [ 2.97124187e-01  8.82321964e-01 -5.87231332e-01  3.17979156e+00
  -3.46385643e-02 -1.86311035e+00 -5.09395595e-01 -7.73924688e-01
  -1.61957207e+00  5.14506543e-01 -2.37455986e+00  6.29162318e-01]
 [ 7.24477868e-01 -1.01100796e+00 -1.61239335e+00  2.93162414e-01
  -3.53461431e+00 -5.28513556e-01 -2.63789332e+00 -9.87176284e-01
  -9.55739732e+00  1.08808190e+00 -3.28150082e+00 -7.11096408e+00]
 [ 3.22253292e-01 -1.49701050e+00  5.77743117e-01 -7.25383987e-01
  -2.54922970e+00  3.23951003e+00 -6.87232427e-01  2.12314483e+00
   4.78770487e+00  1.25189657e+00  1.64090726e+00 -1.82985683e+00]]
v shape is:
 (12, 12)
lambda1_sorted1 is:
 [0.56842695 0.25036817 0.15076678 0.11625536 0.07527128]
v2 is:
 [[ 9.31240423e-02  7.71063088e-02 -6.49267479e-02 -5.56367071e-02
  -2.13027954e-01]
 [-6.77415481e+00  1.61195677e+01  2.72774118e+01  1.60720453e+01
  -1.96474307e+01]
 [-1.76553806e+02 -2.51260647e+01 -3.21479943e+01 -8.99093826e+01
   1.92555015e+01]
 [ 6.01873317e-01 -3.19061192e+00 -4.09517716e+00  2.85098171e+00
   1.76382986e+00]
 [ 8.82316038e+01  3.28709953e+02 -3.55732577e+00  4.05822404e+01
   1.80159508e+02]
 [-9.44415151e+01 -5.62967692e+02  1.82173147e+02 -1.31948588e+02
  -9.52539577e+01]
 [-7.97631098e+00 -2.21307108e+01 -4.15803987e+00 -1.04012537e+01
   3.73011330e+01]
 [-8.38695069e+00  9.81515815e+00 -2.28302986e+01  9.22722724e+01
   5.37613554e+01]
 [ 1.94455616e-01 -8.96409033e+00 -2.23897908e+00 -3.34394933e-01
  -2.78735280e-01]
 [ 2.97124187e-01  8.82321964e-01 -5.87231332e-01  3.17979156e+00
  -3.46385643e-02]
 [ 7.24477868e-01 -1.01100796e+00 -1.61239335e+00  2.93162414e-01
  -3.53461431e+00]
 [ 3.22253292e-01 -1.49701050e+00  5.77743117e-01 -7.25383987e-01
  -2.54922970e+00]]
beta is:
 [[ 9.31240423e-02  7.71063088e-02]
 [-6.77415481e+00  1.61195677e+01]
 [-1.76553806e+02 -2.51260647e+01]
 [ 6.01873317e-01 -3.19061192e+00]
 [ 8.82316038e+01  3.28709953e+02]
 [-9.44415151e+01 -5.62967692e+02]
 [-7.97631098e+00 -2.21307108e+01]
 [-8.38695069e+00  9.81515815e+00]
 [ 1.94455616e-01 -8.96409033e+00]
 [ 2.97124187e-01  8.82321964e-01]
 [ 7.24477868e-01 -1.01100796e+00]
 [ 3.22253292e-01 -1.49701050e+00]]
beta shape is:
 (12, 2)
np.eye(len(beta)) is:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
ect_variance_matrix is: [[ 1.00000000e+00 -6.15691898e-14]
 [-6.05244820e-14  1.00000000e+00]]
ect_variance_matrix shape is: (2, 2)
final_id_matrix is: [[1. 0.]
 [0. 1.]]
final_id_matrix is: (2, 2)
alpha is:
 [[ 2.63946730e-03 -1.08243104e-03]
 [ 3.07428083e-03  6.88755788e-04]
 [ 1.83217533e-02  8.04007274e-03]
 [-3.46819108e-05  5.20682446e-05]
 [-1.53381812e-04  3.43268696e-04]]
alpha shape is:
 (5, 2)
psi_coef is:
 [[ 0.12777205  0.80168672 -0.03416904 -0.01852226  0.00163815 -0.00188184
  -0.00704164]
 [ 0.17835162  0.03486793  0.08853575 -0.02051255  0.0173538   0.00250658
   0.00144089]
 [ 1.13458057 -0.18888638 -0.31319698 -0.83445738 -0.06981595  0.0440615
   0.12021658]
 [-0.00137695  0.02298481 -0.00981403  0.01009208  0.00119815  0.00146266
   0.00266749]
 [-0.00351287  0.0122653  -0.00892986  0.0164587   0.0021964   0.00423976
   0.00275732]]
psi_coef shape is:
 (5, 7)
epsilon is:
 [[ 6.36135394e-03 -1.69921168e-03  3.58951053e-03 -1.21945546e-02
   2.17314683e-03  1.08723624e-02  1.44572853e-02 -9.92131620e-03
   1.07617664e-02 -1.20846884e-02 -1.54816473e-02 -3.41847257e-04
  -2.34743691e-03  9.37327919e-04  2.56619715e-03  6.49885965e-03
   9.34466516e-03  5.81041912e-03 -1.74787281e-03  8.29701807e-03
  -5.82302485e-03 -2.10907402e-03 -5.01196065e-03 -2.52449852e-04
   5.46256024e-03 -3.44318535e-03  1.02053326e-02 -9.22667000e-03
   8.21906596e-05 -1.03191129e-03 -5.57080346e-03 -1.05878384e-03
  -1.94203094e-03  4.77656882e-03 -4.75581775e-03  2.68945728e-03
  -3.36442490e-03  2.42493436e-03  4.57122415e-03  2.45683764e-03
   4.87190825e-03 -2.35733664e-03  1.22090911e-03  2.96094272e-03
  -5.58336786e-03 -8.59476292e-03 -4.42973996e-03 -3.04234109e-03
  -2.77382342e-03 -4.42719129e-03  1.13980947e-03  1.90914189e-03
   1.35376715e-03  5.03291014e-03 -6.39616728e-03 -2.52101836e-04
  -3.43168356e-03  4.49037824e-03  2.46294374e-03  2.88261507e-03
  -1.35340987e-03  8.55040864e-03 -2.12463892e-03  1.17857225e-03
   1.70050857e-05  1.77848486e-04 -5.33163751e-03  1.13024109e-02
  -1.04402373e-03 -1.30415595e-03  3.07560059e-03  7.21900320e-04
   6.48731363e-03 -6.60822607e-03  9.96020438e-03  1.20562502e-03
   4.91224720e-03  2.62846775e-03  2.65194860e-03 -2.25791964e-03
   2.22018381e-03  3.95525470e-03 -1.22108914e-02  4.81768965e-03
  -7.86410382e-03  6.88154300e-04 -7.71367694e-03  3.00203189e-03
  -6.32188567e-03 -9.24165906e-04 -4.86595221e-04 -9.55451970e-03
  -5.36877937e-04 -2.95674529e-03 -3.17274678e-04  8.51277490e-03
   5.76972905e-03 -4.00868812e-04 -3.89927927e-03  3.78350598e-04
  -1.21251550e-04  8.87654235e-04  8.60046342e-03 -1.66465815e-03
  -1.07104827e-03  1.28432854e-05  5.05640866e-03 -2.75118987e-03
  -4.33272062e-03 -1.11451864e-03 -1.61715862e-02  6.63435990e-04
   2.18709639e-04 -7.12904886e-03 -8.04355681e-03  3.63953334e-03
  -3.43390092e-03 -5.85737410e-03 -7.20307434e-04 -9.51716837e-03
  -8.44150115e-03  6.04565715e-04 -5.52672371e-03 -2.87816540e-03
  -4.82036706e-03 -8.55533332e-04 -9.95168558e-03  3.29574468e-03
  -5.81962476e-03  7.78516215e-03  6.09267804e-03 -2.60637946e-04
   1.97425781e-03 -3.40854423e-03  3.48524533e-03 -8.71727661e-03
  -6.18691439e-04  4.32619818e-03 -6.63087010e-03  3.58546945e-03
   6.47935993e-03 -1.22644707e-03  2.72774306e-03 -5.12445760e-03
  -2.59712505e-03 -9.64400840e-05 -1.62095547e-03 -4.49113220e-03
   3.34360801e-03  2.29888101e-03 -2.10901031e-03 -7.08690989e-04
  -1.40943330e-03  3.42447010e-03 -2.06586263e-04 -5.63007755e-04
   4.71557948e-03  8.97053563e-05 -1.99874307e-03  2.40664234e-04
   6.63180552e-03  6.77795090e-03  1.41466798e-02 -1.56259461e-02
  -1.75427760e-03 -1.22229291e-03  9.26808092e-03  1.09409844e-02
   2.91827895e-03  8.14416203e-03 -4.85703389e-03  1.34719598e-03
   2.84548785e-03  9.45513825e-03 -3.89676786e-03  4.42682052e-03
   7.94539084e-03]
 [ 1.35297550e-03 -1.35377305e-03  1.09423240e-02  7.18767534e-03
  -7.26159697e-03  5.17321076e-03  1.54976683e-03  1.91179380e-03
   7.13024061e-03 -8.95390499e-03 -2.99750506e-03  2.61190151e-03
   4.61944394e-03 -1.22624171e-02 -8.22933447e-03  4.54291375e-03
  -2.90542357e-03 -3.87144987e-03 -1.64068643e-03  7.50871613e-04
   2.63164680e-03 -2.05047464e-03 -2.24621987e-03  5.76983093e-03
  -1.67283848e-03  2.26496900e-05  1.27447230e-04 -2.80705904e-03
   2.61407175e-03 -7.05819531e-03 -2.87264748e-03 -8.13211993e-04
   3.69171871e-05 -1.21378558e-03 -1.89254749e-03  7.43872652e-03
   5.84563638e-03  7.63381253e-04 -3.46666062e-03  4.95913648e-03
  -5.30544825e-03 -2.65502712e-03  2.26188885e-03  2.36384001e-03
  -2.31033807e-03 -1.36649370e-03  1.88627099e-03 -4.06013877e-04
  -7.38894598e-04 -2.34489346e-03  4.47866839e-04 -4.26411995e-04
   5.98553190e-05  8.00502768e-04  2.27324926e-03 -3.92705443e-04
  -2.33294985e-03  1.79710495e-03  5.12733126e-04 -2.31308967e-03
   2.74149867e-03 -9.53931659e-04  2.15358433e-03 -1.81973181e-03
  -1.81129636e-03 -2.97529657e-03 -1.75790523e-03 -7.16162389e-04
  -4.15802405e-03 -2.29666282e-03 -9.82378165e-05 -3.87654744e-04
  -1.34075389e-03 -1.43835745e-03  2.07001124e-03  1.67075674e-03
  -7.21270647e-04 -1.29243214e-03 -1.03935597e-03 -1.19414404e-03
  -6.57148274e-03 -3.08405209e-03  1.98066519e-03  4.15510026e-03
  -2.31141303e-03 -1.19741650e-03  4.10961534e-03 -2.53550798e-03
   5.44491136e-04  3.64375858e-03 -4.60114980e-04  7.78445836e-04
   2.57354192e-03  4.11585879e-03  1.21587080e-03 -4.46741469e-03
   3.08284302e-03  3.21774107e-04  4.01164914e-03  1.46099036e-03
  -1.53898211e-03  6.43022842e-03 -2.10820569e-03 -1.02864966e-03
   4.75936407e-03  3.32939049e-03 -4.72502948e-03 -3.63390162e-04
   1.46666597e-04 -6.24211412e-03  7.72135122e-03 -1.78160008e-03
  -4.30004557e-03  5.93756681e-03  2.28083687e-04  9.65162698e-04
   7.93991245e-03 -1.13930303e-02  9.40895527e-03 -3.72534521e-03
   2.06490217e-03  4.74984414e-04 -3.61473157e-03 -4.97159384e-03
   3.31968501e-03  1.56608176e-03  3.03553738e-04  2.18066809e-03
   2.33465909e-04  1.00232870e-04 -1.61821802e-03 -1.25760109e-03
  -8.48033886e-04 -8.93063784e-04 -3.72547920e-03 -3.94743697e-03
   8.22956074e-05 -1.20192556e-03  2.97874124e-03  9.07718943e-04
  -1.53235263e-03  3.92610213e-04 -5.98824250e-04  4.67467712e-03
   3.60618671e-03  1.68334867e-03  3.37706604e-03 -9.81906153e-04
  -3.17646190e-04  1.60453621e-03  6.54377296e-04 -3.06669526e-03
   1.92400436e-03  5.05487084e-04  6.75410470e-04 -2.88515043e-03
   2.63142711e-05  1.35380586e-03  2.53025427e-04 -1.20201528e-03
  -3.27676563e-04  4.76025370e-08  3.23884299e-03 -4.81505878e-03
  -3.04412291e-03 -6.36826499e-03 -4.41842144e-03  3.02067057e-03
   3.90017020e-03  4.95022267e-03  4.22158199e-03  3.72697397e-03
   2.87009886e-03 -4.89476903e-04  1.00383365e-03 -7.12005233e-03
  -2.51587503e-03]
 [ 7.40423689e-03 -6.63233997e-02 -6.85160406e-02  2.07319307e-02
   7.80325579e-02  3.36155720e-02 -3.25546567e-02  2.79004212e-03
  -1.06128065e-01 -1.90932606e-02 -3.57520673e-02 -4.32256183e-04
   5.50745099e-02  1.72001711e-01  2.59587791e-03  1.33773421e-02
  -2.55911994e-02 -3.03774549e-02 -7.54881285e-02 -5.64760868e-02
   8.60160069e-02  5.51311118e-02  9.11934936e-02  2.23926586e-03
   4.68794185e-03  5.38917008e-02  5.56388010e-02  7.81214202e-03
  -5.63014857e-02 -1.78437422e-02  8.59167514e-02 -4.57320898e-02
   6.42056175e-02 -3.26338242e-01 -4.99601083e-03 -6.85420321e-02
   1.10019451e-02 -6.64111220e-03  2.87201448e-02  7.59873419e-02
   6.39689862e-02 -2.69842373e-02 -5.81512971e-02 -3.22487967e-03
  -9.64669965e-02 -2.37211737e-02  1.03463350e-01  3.30428238e-02
   1.23977153e-02 -2.22569574e-02  2.53052811e-02 -3.16040417e-02
  -1.28415008e-02  5.79575451e-02  1.19094889e-02 -1.37017485e-02
  -1.25830272e-03 -1.74291284e-02  8.14798523e-03 -5.31513574e-02
  -2.18678432e-02 -2.80731440e-02  6.71732129e-02  3.41811911e-02
   3.52064878e-02  4.42836630e-02  2.82612810e-02 -5.92767008e-03
  -2.04316013e-03  7.90814021e-02  3.51231077e-02  3.94880038e-02
   9.88913430e-02  3.18146185e-02  8.40854597e-02  2.40255979e-02
  -3.36924455e-02  3.28180876e-02  8.34297044e-02  4.28993212e-02
  -6.65909376e-03  3.62606670e-02  2.79597318e-02  1.10108659e-02
   3.37675522e-02 -9.72736054e-02 -1.19485093e-01 -2.26334219e-02
  -1.00004264e-01 -1.61778445e-02  7.11135363e-03 -7.79448190e-02
  -1.42446857e-01  4.25620550e-04 -7.43617056e-02  7.06237111e-02
   2.25508833e-02  3.90358377e-02  2.32914384e-02  2.55940461e-02
  -8.94215206e-03  1.27400175e-02  5.38107781e-03  1.43532980e-03
   1.16907781e-02 -1.02967992e-02  1.65321935e-02 -6.45141335e-02
  -6.81896585e-03  3.98967349e-02 -4.33309069e-02  2.22885464e-02
  -5.27606159e-03 -3.81824620e-02 -1.21427187e-01  6.86318562e-03
  -6.64199282e-02 -1.81983411e-01 -1.65953598e-01  1.19274014e-03
   5.80819341e-02  4.17825912e-02  2.08439876e-02 -1.91425953e-02
  -3.96540934e-02  3.53378655e-02  4.38884252e-02  6.55557037e-03
  -5.79985415e-02  5.12249757e-02  4.81470897e-02 -1.77266252e-02
  -5.48530562e-04 -3.96597937e-02  4.26948067e-02  3.78353501e-03
   2.60756139e-02  7.89414871e-02  1.02775148e-02  3.16205799e-02
  -4.68059466e-03  3.91719647e-02 -4.36932562e-03 -4.18005923e-02
  -4.41327242e-02  6.72211249e-02 -6.03295826e-03 -1.27259737e-02
   2.50119209e-02  1.90577217e-02  4.28219685e-02  3.07473963e-02
  -1.21326936e-02  6.05678741e-02 -3.75313224e-02  4.95978718e-02
   7.86360087e-02 -1.65874229e-01  7.99410156e-02  9.69103918e-03
  -1.30231012e-02  5.02946516e-02 -2.61986402e-01  1.56081909e-01
  -3.76262972e-02  6.42347920e-02 -1.74370029e-03  3.98544978e-02
   1.17531418e-02  1.03723170e-01 -7.11064444e-02 -1.67936435e-01
  -3.51273039e-03  4.90500620e-02 -1.64499409e-02  5.44041596e-02
  -8.87411118e-02]
 [ 4.60686846e-04  4.32923583e-03  3.06216282e-03 -7.55959869e-03
  -7.73398901e-04  1.00955861e-02  1.85665976e-03  9.86188421e-04
   3.81208073e-04 -6.85977629e-03  2.40136157e-03 -8.07492038e-04
  -7.15942535e-03 -2.60669893e-03  4.56880563e-04  1.12551926e-04
   1.39911723e-03 -6.33329615e-04  8.60000474e-04  1.50737567e-03
   1.15605436e-03 -3.47355287e-03 -1.34129526e-03 -1.41323512e-03
  -6.16190434e-04  2.06007957e-04  3.31680331e-04 -1.67860146e-03
  -1.26083379e-03 -4.71316302e-04  4.42379107e-04 -1.28564963e-04
   3.96259115e-04 -3.14246442e-04  2.52296648e-04  4.69108158e-04
   2.56482117e-03  2.00112926e-03  1.57967243e-03 -1.48867158e-04
  -9.24652386e-04 -2.95787558e-04  4.77719647e-04 -9.47026567e-05
  -1.09940362e-03 -9.21381809e-04 -1.41874400e-03 -1.25761135e-03
  -7.21355573e-05 -1.55039547e-03 -1.46993379e-03 -7.88514298e-04
  -1.17559631e-03 -8.38703278e-06 -1.17808549e-04  3.11098468e-04
   1.73936108e-04  4.32426724e-04 -4.51832314e-04  1.31178659e-03
   1.12407528e-03  1.53906044e-03  7.65213195e-04  6.51138606e-04
  -4.88432075e-04 -2.34198964e-04 -7.56380842e-04  3.08416749e-04
   3.24229232e-04 -5.22035467e-04  6.16570533e-05  8.26227141e-06
   1.85330487e-04  4.85925975e-06  7.29996277e-04  5.17188028e-05
  -1.96823136e-04 -7.69402339e-04  2.99730230e-04 -3.75331751e-04
  -1.11696557e-04  5.53880003e-04  7.60278419e-04  3.41839230e-04
   6.02562584e-04  6.12846013e-05 -2.68902333e-03 -2.64163408e-03
  -4.07094975e-04 -2.54607491e-03 -6.23103464e-04 -1.37139828e-04
  -1.12519379e-04 -6.55123742e-04 -4.14687654e-04  4.05123324e-04
  -6.96567560e-04 -6.62867655e-05 -5.05887407e-04  5.18020939e-05
   8.58808728e-04  1.52972480e-03  8.94104085e-04  5.45247268e-04
   8.71138606e-04  7.43041897e-04  7.34056642e-04  3.33412409e-05
   4.11469802e-04  8.79171894e-06  1.17119383e-05 -8.53847201e-04
  -5.02339241e-04 -1.86241047e-03 -3.47083001e-03 -1.13643189e-03
  -1.07051437e-04 -1.76133195e-03  1.29053869e-03 -2.01576981e-04
  -8.28505065e-04 -6.07454242e-04 -5.12614305e-04 -3.85553599e-04
   5.61979178e-04 -4.09409341e-04 -4.71282164e-04  1.76549102e-04
  -1.09882326e-05  4.15600278e-04  1.69726247e-04  4.17912638e-05
   5.16042901e-04  1.26309778e-05 -1.45182159e-04  2.74478366e-04
  -1.34026200e-04  1.43461128e-04  9.52574655e-05  3.24696273e-04
   3.33702700e-04  5.17656251e-04  6.14748135e-04  9.26019926e-05
   3.40588332e-04  7.02139975e-04  6.29901849e-04 -3.68617796e-04
   1.10061729e-05 -1.75271371e-04 -3.42106232e-05  1.43589129e-03
   5.03271573e-04  2.40927566e-04  7.09540521e-04  4.60993188e-04
   8.70369641e-04  9.86075105e-04  3.00353215e-04 -3.15254809e-04
  -3.99004567e-04 -4.64371880e-04  3.61091970e-05  6.91430315e-06
  -2.25263927e-03 -4.38579493e-04 -6.09083987e-04 -4.84449694e-04
   3.63754373e-04  2.22432615e-04  7.34235600e-05  2.04540475e-03
   4.66424655e-03  3.68487672e-03  1.32312449e-03  1.47536981e-03
   6.29610583e-04]
 [-1.43091677e-03  1.63906270e-03  2.08298126e-03 -3.02899015e-03
   7.28558604e-04  3.14536918e-03  9.05732124e-04  8.09210256e-04
   2.04694648e-03 -1.43254350e-03  2.90316257e-04 -8.64310597e-04
  -2.32035813e-03 -4.14801700e-03  2.33098115e-05 -5.75277218e-04
   2.06790572e-03  7.62349762e-04  1.21684041e-03  3.10576409e-03
  -1.40966842e-04 -1.91818014e-03  6.02834437e-04 -7.73764677e-04
  -3.06484334e-04 -1.02297450e-03 -1.13103504e-03 -1.83918127e-03
  -3.45180507e-04 -4.24821430e-04 -1.97118620e-04  1.91478483e-03
   9.02459918e-04  1.50247307e-03 -6.67368022e-05  7.08602505e-04
   1.84281662e-03  7.35547600e-04 -1.37171238e-04 -1.19314660e-03
  -1.56878806e-03 -6.71032899e-04  9.29800241e-04  1.60156762e-04
  -7.84089345e-04 -9.36448653e-04 -2.35631061e-05 -1.96563390e-04
   2.20423577e-04 -6.24942479e-04  1.46077925e-04 -2.68082090e-04
  -1.08278921e-03  4.91460365e-05 -8.79549795e-04 -5.75594608e-04
  -7.94461559e-04  2.21201314e-04 -4.06603210e-04  1.64614755e-03
   8.60170084e-04  9.72716409e-04 -1.21782389e-03 -7.08090549e-04
  -3.59729442e-04 -1.16622019e-03 -9.02546062e-05  1.71685776e-03
   2.39167805e-04 -1.25274982e-03  3.35137956e-04  8.43690599e-04
  -4.91863004e-04 -6.81172966e-04  5.17444163e-04  3.07250453e-04
  -5.29955077e-04 -1.17241863e-04  3.54082620e-04  7.22221898e-04
   1.66451029e-04  3.54381185e-04  7.71875549e-04 -5.39787027e-04
  -6.03143021e-04 -6.97504238e-04 -1.00184760e-03  3.35511642e-04
   7.77516380e-04  5.70176595e-04  7.79785151e-04  3.45717259e-04
  -1.73836241e-03 -4.73362781e-04 -1.61844878e-04  2.27479103e-04
   7.81239474e-04  2.42685417e-04 -9.86228295e-04  9.77516155e-04
  -6.17221454e-04  3.35763092e-04 -4.47235152e-04 -9.00913901e-04
  -6.21836519e-04 -9.66971121e-05 -8.22400967e-04  1.03519516e-05
  -6.22244717e-04 -5.65907882e-04 -8.55598144e-05  1.06024384e-04
   5.54382342e-04 -7.59137990e-04 -1.95062539e-03 -4.08277228e-05
  -1.53743847e-04 -3.64647621e-04  5.93689949e-04  9.99518612e-04
  -7.54374045e-04 -6.15228779e-04 -1.60899732e-04 -9.01526504e-04
  -5.32876302e-04 -4.30155496e-04  6.65541661e-04  1.57910547e-04
  -1.46630191e-03 -4.35304283e-04 -2.84768752e-04 -9.59089015e-04
  -1.15714053e-04 -1.83029559e-04 -1.29268586e-04  3.62080879e-04
   1.47411018e-03  2.72621532e-04  2.99764733e-04  3.58124739e-04
   4.28151170e-04  3.41207808e-04  1.90596714e-04  6.27438290e-04
   6.01817096e-04  6.06253819e-04 -2.10104272e-04 -8.80503916e-04
  -7.14296532e-04  5.79294400e-04  2.94802526e-04  9.12889770e-04
   5.62373948e-04  8.01433756e-05  7.96503002e-04  2.15704743e-04
   6.26566617e-04  9.04378804e-04 -5.42689462e-04 -8.86048672e-04
  -7.18514154e-04  2.84636938e-04 -2.28531561e-04 -3.67118562e-04
  -1.63389208e-03 -1.07236830e-04  4.12101490e-04  2.75903966e-04
   1.26005126e-05  7.07622727e-04  6.92180630e-05  2.32397899e-03
   1.73424426e-03  2.08647099e-03 -3.70398801e-04  1.46688460e-04

                    cv1         cv2
trend1         0.093124    0.077106
y_lag1        -6.774155   16.119568
Dp_lag1     -176.553806  -25.126065
eq_lag1        0.601873   -3.190612
r_lag1        88.231604  328.709953
lr_lag1      -94.441515 -562.967692
ys_lag1       -7.976311  -22.130711
Dps_lag1      -8.386951    9.815158
eps_lag1       0.194456   -8.964090
poil_lag1      0.297124    0.882322
pmat_lag1      0.724478   -1.011008
pmetal_lag1    0.322253   -1.497010

beta_df is:
 None

            alpha1    alpha2
y_diff1   0.002639 -0.001082
Dp_diff1  0.003074  0.000689
eq_diff1  0.018322  0.008040
r_diff1  -0.000035  0.000052
lr_diff1 -0.000153  0.000343

alpha_df is:
 None

,intercept,ys_diff1,Dps_diff1,eps_diff1,poil_diff1,pmat_diff1,pmetal_diff1
y_diff1,0.006109,0.000160,1.123280e-05,-9.280113e-05,0.000674,0.000145,0.000244
Dp_diff1,-0.000136,0.000022,1.128579e-05,-3.414948e-05,0.000501,0.000082,0.000169
eq_diff1,0.013371,0.000160,2.062189e-06,-4.742619e-04,0.000400,0.000560,0.001616
r_diff1,-0.000054,0.000003,1.702315e-07,-1.334708e-06,0.000046,0.000014,0.000027
lr_diff1,-0.000066,0.000002,1.783224e-07,-5.560069e-07,0.000058,0.000022,0.000031

m_02_df is:
 None

,intercept,ys_diff1,Dps_diff1,eps_diff1,poil_diff1,pmat_diff1,pmetal_diff1
intercept,1.000000,0.009228,-0.000097,-0.005802,0.005816,0.002991,0.006156
ys_diff1,0.009228,0.000210,0.000012,-0.000133,0.000817,0.000204,0.000337
Dps_diff1,-0.000097,0.000012,0.000040,-0.000009,0.000212,0.000026,0.000037
eps_diff1,-0.005802,-0.000133,-0.000009,0.000591,-0.001739,-0.000498,-0.001028
poil_diff1,0.005816,0.000817,0.000212,-0.001739,0.023741,0.003448,0.005794
pmat_diff1,0.002991,0.000204,0.000026,-0.000498,0.003448,0.003275,0.002535
pmetal_diff1,0.006156,0.000337,0.000037,-0.001028,0.005794,0.002535,0.007887

m_22_df is:
 None

,intercept,ys_diff1,Dps_diff1,eps_diff1,poil_diff1,pmat_diff1,pmetal_diff1
trend1,88.000000,0.738846,-0.008567,-0.469009,0.855227,0.083492,0.756824
y_lag1,4.539326,0.041444,-0.000460,-0.026168,0.028996,0.012379,0.029438
Dp_lag1,0.008333,0.000076,-0.000005,-0.000071,0.000041,0.000035,-0.000023
eq_lag1,1.918687,0.017079,-0.000199,-0.010557,0.020992,0.003701,0.015145
r_lag1,0.009926,0.000096,-0.000001,-0.000055,-0.000013,0.000003,-0.000028
lr_lag1,0.013908,0.000135,-0.000002,-0.000076,-0.000008,0.000032,0.000011
ys_lag1,4.608653,0.041789,-0.000464,-0.026318,0.029877,0.011910,0.030209
Dps_lag1,0.019379,0.000190,-0.000022,-0.000155,-0.000146,0.000164,0.000141
eps_lag1,-2.933635,-0.026606,0.000332,0.016502,-0.018320,-0.007159,-0.017626
poil_lag1,3.601912,0.032143,-0.000337,-0.019687,0.011092,0.006380,0.016638
pmat_lag1,4.591948,0.042195,-0.000560,-0.026612,0.027652,0.011565,0.027032
pmetal_lag1,4.526811,0.041188,-0.000519,-0.026699,0.029470,0.011797,0.025267

m_12_df is:
 None

,trend1,y_lag1,Dp_lag1,eq_lag1,r_lag1,lr_lag1,ys_lag1,Dps_lag1,eps_lag1,poil_lag1,pmat_lag1,pmetal_lag1
trend1,2496.935520,15.538262,-0.135636,33.902127,-0.357444,-0.362167,24.279716,-0.634540,-15.050322,22.584506,8.110075,20.649379
y_lag1,15.538262,0.099114,-0.000918,0.218649,-0.002284,-0.002315,0.152534,-0.004187,-0.093936,0.133275,0.053027,0.124076
Dp_lag1,-0.135636,-0.000918,0.000052,-0.001886,0.000033,0.000026,-0.001396,0.000043,0.000766,0.000064,-0.000479,-0.000367
eq_lag1,33.902127,0.218649,-0.001886,0.520058,-0.004814,-0.005103,0.330556,-0.009366,-0.198137,0.240939,0.114494,0.243048
r_lag1,-0.357444,-0.002284,0.000033,-0.004814,0.000070,0.000061,-0.003550,0.000096,0.002217,-0.002741,-0.001382,-0.002646
lr_lag1,-0.362167,-0.002315,0.000026,-0.005103,0.000061,0.000060,-0.003570,0.000099,0.002224,-0.002806,-0.001334,-0.002801
ys_lag1,24.279716,0.152534,-0.001396,0.330556,-0.003550,-0.003570,0.237829,-0.006353,-0.148168,0.222467,0.081657,0.201956
Dps_lag1,-0.634540,-0.004187,0.000043,-0.009366,0.000096,0.000099,-0.006353,0.000251,0.003921,-0.005768,-0.001947,-0.004426
eps_lag1,-15.050322,-0.093936,0.000766,-0.198137,0.002217,0.002224,-0.148168,0.003921,0.097709,-0.151901,-0.056302,-0.138464
poil_lag1,22.584506,0.133275,0.000064,0.240939,-0.002741,-0.002806,0.222467,-0.005768,-0.151901,0.425369,0.065197,0.288004
pmat_lag1,8.110075,0.053027,-0.000479,0.114494,-0.001382,-0.001334,0.081657,-0.001947,-0.056302,0.065197,0.047178,0.078215
pmetal_lag1,20.649379,0.124076,-0.000367,0.243048,-0.002646,-0.002801,0.201956,-0.004426,-0.138464,0.288004,0.078215,0.258216

s_12_df is:
 None

,trend1,y_lag1,Dp_lag1,eq_lag1,r_lag1,lr_lag1,ys_lag1,Dps_lag1,eps_lag1,poil_lag1,pmat_lag1,pmetal_lag1
y_diff1,0.017953,0.000044,-1.288881e-05,0.000345,-4.328986e-06,-2.959040e-06,0.000109,4.659427e-06,0.000011,-0.000493,-0.000013,-0.000163
Dp_diff1,0.009150,0.000042,-1.773416e-05,0.000074,-2.201251e-06,-2.568718e-06,0.000080,-8.339685e-07,-0.000034,-0.000211,-0.000007,-0.000022
eq_diff1,-0.043188,-0.000775,-8.697311e-05,-0.002775,-2.958034e-06,-4.734820e-07,-0.000743,-3.244022e-05,0.000210,-0.004946,-0.000713,-0.001953
r_diff1,0.008283,0.000047,3.960783e-07,0.000114,-1.662256e-06,-1.542809e-06,0.000074,-7.005868e-07,-0.000055,0.000097,0.000053,0.000120
lr_diff1,0.001670,0.000006,1.718423e-06,0.000031,1.556226e-07,-5.700711e-07,0.000012,3.572784e-07,-0.000020,0.000066,0.000016,0.000061

s_01_df is:
 None

,0,1,2,3,4,5,6,7,8,9,...,167,168,169,170,171,172,173,174,175,176
y_diff1,0.007175,0.002945,0.003184,-0.020394,-0.001663,0.018373,0.020059,-0.007832,0.012024,-0.012537,...,0.016925,0.006549,0.016812,-0.004111,-0.001445,0.007974,0.006358,0.003160,0.010887,0.012566
Dp_diff1,-0.001252,-0.003654,0.009394,-0.002766,-0.016716,0.007101,0.000234,-0.003135,0.005282,-0.013987,...,0.004761,0.001126,0.002933,0.003011,-0.001222,-0.007547,-0.005322,0.001789,-0.006196,0.004920
eq_diff1,0.014400,-0.058117,-0.025760,-0.005218,0.084946,0.029887,-0.034363,-0.006774,-0.110549,-0.019640,...,0.065714,-0.016542,0.072512,-0.080267,-0.209684,-0.066698,0.055251,0.059260,0.074945,-0.044590
r_diff1,0.000677,0.004898,0.003353,-0.008380,-0.001059,0.010012,0.001703,0.001127,0.000319,-0.007283,...,-0.000058,0.000050,0.000017,0.000632,0.001912,0.003894,0.003330,0.001406,0.001065,0.000515
lr_diff1,-0.000023,0.003059,0.003462,-0.003394,0.001076,0.003290,0.001191,0.001742,0.002399,-0.001660,...,0.000682,-0.000665,0.000526,0.000991,0.002416,0.000429,0.001748,-0.000442,-0.000129,0.001340

z0_vals_t_df is:
 None

,0,1,2,3,4,5,6,7,8,9,...,167,168,169,170,171,172,173,174,175,176
trend1,0.000000,1.000000,2.000000,3.000000,4.000000,5.000000,6.000000,7.000000,8.000000,9.000000,...,167.000000,168.000000,169.000000,170.000000,171.000000,172.000000,173.000000,174.000000,175.000000,176.000000
y_lag1,3.960503,3.967677,3.970622,3.973806,3.953413,3.951749,3.970122,3.990181,3.982349,3.994373,...,4.966157,4.983082,4.989631,5.006443,5.002331,5.000886,5.008861,5.015219,5.018379,5.029266
Dp_lag1,0.033730,0.032477,0.028823,0.038217,0.035451,0.018735,0.025836,0.026071,0.022936,0.028218,...,0.011383,0.016144,0.017270,0.020203,0.023214,0.021992,0.014444,0.009122,0.010911,0.004715
eq_lag1,0.684670,0.699070,0.640953,0.615193,0.609975,0.694921,0.724808,0.690445,0.683671,0.573122,...,3.141412,3.207126,3.190584,3.263096,3.182829,2.973145,2.906448,2.961698,3.020958,3.095903
r_lag1,0.022407,0.023084,0.027982,0.031335,0.022955,0.021896,0.031908,0.033611,0.034738,0.035056,...,0.000125,0.000067,0.000117,0.000133,0.000765,0.002677,0.006571,0.009901,0.011307,0.012372
lr_lag1,0.021804,0.021781,0.024841,0.028302,0.024909,0.025985,0.029275,0.030466,0.032208,0.034607,...,0.003270,0.003952,0.003287,0.003812,0.004804,0.007220,0.007648,0.009396,0.008954,0.008826
ys_lag1,3.723439,3.736803,3.755427,3.766682,3.768565,3.776422,3.787429,3.801458,3.813017,3.820110,...,5.280323,5.289313,5.295806,5.309669,5.317501,5.320754,5.331930,5.332679,5.343477,5.352381
Dps_lag1,0.027880,0.029817,0.029535,0.040626,0.033697,0.032422,0.032043,0.038694,0.034243,0.032555,...,0.010233,0.008260,0.010205,0.013832,0.016353,0.021158,0.014947,0.011538,0.008314,0.007976
eps_lag1,-2.381442,-2.420323,-2.440535,-2.465478,-2.498637,-2.538734,-2.545119,-2.547628,-2.528027,-2.522136,...,-3.324926,-3.338563,-3.341636,-3.348691,-3.367209,-3.376600,-3.370713,-3.365033,-3.395617,-3.403638
poil_lag1,3.433544,3.576322,3.696729,3.661658,3.643353,3.550055,3.679337,3.666904,3.561324,3.571967,...,4.108882,4.232603,4.297659,4.379233,4.609229,4.733148,4.613407,4.485170,4.397714,4.361766
pmat_lag1,4.148960,4.272871,4.220098,4.311326,4.207531,4.289884,4.284165,4.204844,4.181515,4.122315,...,4.780327,4.822723,4.764769,4.799214,4.892263,4.950379,4.814593,4.719217,4.696997,4.674107
pmetal_lag1,4.200168,4.198063,4.305733,4.431295,4.284341,4.277811,4.195716,4.135575,4.082994,4.049079,...,5.364814,5.514481,5.465680,5.340962,5.491054,5.461531,5.240803,5.244402,5.416306,5.315188

z1_vals_t_df is:
 None

,0,1,2,3,4,5,6,7,8,9,...,167,168,169,170,171,172,173,174,175,176
intercept,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
ys_diff1,0.013364,0.018624,0.011254,0.001883,0.007858,0.011007,0.014029,0.011558,0.007093,0.006993,...,0.008990,0.006494,0.013863,0.007832,0.003253,0.011176,0.000749,0.010798,0.008904,0.004346
Dps_diff1,0.001937,-0.000282,0.011091,-0.006929,-0.001275,-0.000379,0.006651,-0.004452,-0.001688,-0.001778,...,-0.001974,0.001946,0.003627,0.002521,0.004805,-0.006211,-0.003409,-0.003223,-0.000338,0.002739
eps_diff1,-0.038881,-0.020211,-0.024944,-0.033159,-0.040097,-0.006385,-0.002509,0.019601,0.005891,-0.036069,...,-0.013637,-0.003073,-0.007054,-0.018518,-0.009391,0.005886,0.005680,-0.030584,-0.008021,-0.004809
poil_diff1,0.142778,0.120407,-0.035071,-0.018305,-0.093299,0.129282,-0.012433,-0.105580,0.010643,0.033070,...,0.123721,0.065056,0.081574,0.229996,0.123919,-0.119741,-0.128237,-0.087456,-0.035948,0.101189
pmat_diff1,0.123911,-0.052773,0.091228,-0.103795,0.082353,-0.005719,-0.079321,-0.023329,-0.059200,-0.014048,...,0.042396,-0.057954,0.034444,0.093050,0.058115,-0.135785,-0.095376,-0.022220,-0.022890,0.004324
pmetal_diff1,-0.002106,0.107670,0.125562,-0.146954,-0.006530,-0.082095,-0.060140,-0.052581,-0.033915,-0.044532,...,0.149667,-0.048801,-0.124718,0.150092,-0.029523,-0.220728,0.003599,0.171903,-0.101118,-0.025397

z2_vals_t_df is:
 None

               y_diff1      Dp_diff1  eq_diff1       r_diff1      lr_diff1
y_diff1   3.177091e-05  3.550999e-07  0.000004  2.962153e-06  1.702658e-06
Dp_diff1  3.550999e-07  1.295311e-05 -0.000047  9.049901e-07  6.892602e-07
eq_diff1  3.758283e-06 -4.697209e-05  0.004203 -3.411496e-06 -1.332629e-05
r_diff1   2.962153e-06  9.049901e-07 -0.000003  2.723670e-06  1.029222e-06
lr_diff1  1.702658e-06  6.892602e-07 -0.000013  1.029222e-06  1.006152e-06

omega_df is:
 None

,0,1,2,3,4,5,6,7,8,9,...,167,168,169,170,171,172,173,174,175,176
cv1,-57.470974,-57.133666,-56.425004,-58.150086,-57.943807,-55.062060,-55.834543,-56.150250,-55.636135,-56.913966,...,-54.943553,-55.777762,-55.977543,-56.654068,-57.053863,-56.919568,-55.526000,-54.456618,-54.551071,-53.416172
cv2,-12.334215,-11.844793,-11.790596,-12.890560,-13.403693,-14.141148,-12.550426,-12.220101,-13.245454,-14.106478,...,-15.370599,-16.006776,-15.316656,-15.548249,-15.805528,-15.629671,-13.981953,-13.857249,-13.560918,-12.954930

ecm_df is:
 None

,0,1,2,3,4,5,6,7,8,9,...,167,168,169,170,171,172,173,174,175,176
y_diff1,0.006361,-0.001699,0.003590,-0.012195,0.002173,0.010872,0.014457,-0.009921,0.010762,-0.012085,...,0.010941,0.002918,0.008144,-0.004857,0.001347,0.002845,0.009455,-0.003897,0.004427,0.007945
Dp_diff1,0.001353,-0.001354,0.010942,0.007188,-0.007262,0.005173,0.001550,0.001912,0.007130,-0.008954,...,0.003021,0.003900,0.004950,0.004222,0.003727,0.002870,-0.000489,0.001004,-0.007120,-0.002516
eq_diff1,0.007404,-0.066323,-0.068516,0.020732,0.078033,0.033616,-0.032555,0.002790,-0.106128,-0.019093,...,0.039854,0.011753,0.103723,-0.071106,-0.167936,-0.003513,0.049050,-0.016450,0.054404,-0.088741
r_diff1,0.000461,0.004329,0.003062,-0.007560,-0.000773,0.010096,0.001857,0.000986,0.000381,-0.006860,...,-0.000484,0.000364,0.000222,0.000073,0.002045,0.004664,0.003685,0.001323,0.001475,0.000630
lr_diff1,-0.001431,0.001639,0.002083,-0.003029,0.000729,0.003145,0.000906,0.000809,0.002047,-0.001433,...,0.000276,0.000013,0.000708,0.000069,0.002324,0.001734,0.002086,-0.000370,0.000147,0.000986

epsilon_df is:
 None

,intercept,ys_diff1,Dps_diff1,eps_diff1,poil_diff1,pmat_diff1,pmetal_diff1
y_diff1,0.127772,0.801687,-0.034169,-0.018522,0.001638,-0.001882,-0.007042
Dp_diff1,0.178352,0.034868,0.088536,-0.020513,0.017354,0.002507,0.001441
eq_diff1,1.134581,-0.188886,-0.313197,-0.834457,-0.069816,0.044062,0.120217
r_diff1,-0.001377,0.022985,-0.009814,0.010092,0.001198,0.001463,0.002667
lr_diff1,-0.003513,0.012265,-0.008930,0.016459,0.002196,0.004240,0.002757

psi_df is:
 None
vecm_final_results.xlsx has been exported as Excel via working folder: (C:\Users\benchee\vecm_final_results.xlsx)
b_top is:
 [[  -6.77415481   16.11956771]
 [-176.55380601  -25.12606467]]
beta_temasek is:
 [[ 3.73769992e-03 -6.70865176e-04]
 [ 1.00000000e+00  2.23987520e-18]
 [ 4.61318812e-17  1.00000000e+00]
 [-1.91778209e-01  3.94928876e-03]
 [ 1.85062234e+01 -1.20980471e+00]
 [-3.21669068e+01  1.76912143e+00]
 [-1.22898808e+00  9.23325693e-02]
 [ 6.44402958e-01  2.27786950e-02]
 [-5.26338202e-01  1.90935609e-02]
 [ 4.91720634e-02 -3.56958239e-03]
 [-6.52151578e-02 -1.60121325e-03]
 [-9.03128986e-02  1.63995482e-03]]


$ \text{----------------------------------------------------------------------------------------------------------------------------------------------------------------------------} $

$\Large\text{Code block below is to visualize the macroeconomic variables for the US historical time series.} $

$ \text{----------------------------------------------------------------------------------------------------------------------------------------------------------------------------} $

In [ ]:
# i'd first like to visualize how would the US data play out during the iranian revolution. 
us_graph_df = us_df.copy()
# first off, lets get the diff of the GDP growth data that is in log space. 
us_graph_df['y_diff'] = us_graph_df['y'].diff()
us_graph_df['poil_diff'] = us_graph_df['poil'].diff()
us_graph_df = us_graph_df.dropna().drop(columns = ['y'])
cols = [col for col in us_graph_df.columns if col not in ['y_diff', 'date']]
target_cols = ['date', 'y_diff'] + cols
us_graph_df = us_graph_df[target_cols]
target_cols2 = ['date', 'y_diff', 'Dp', 'r', 'poil', 'eps']
us_graph_df = us_graph_df[target_cols2]
us_graph_df

# Create a 2 x 2 subplot layout
fig, axes = plt.subplots(nrows = 2, ncols = 3, figsize = (14,10), sharex = True)
fig.suptitle(
    "US Macroeconomic Variables (Mohaddes GVAR Dataset)",
    fontsize = 16,
    fontweight = "bold",
    y = 0.98 # slightly raise the title position to the absolute top edge.
)

axes[0, 0].plot(us_graph_df['date'], us_graph_df['y_diff'], color = 'blue', linewidth = 1.5)
axes[0, 0].set_title("1. US GDP Growth ($\\Delta y$)", fontsize = 12, pad = 10)
axes[0, 0].grid(True, linestyle = "--", alpha = 0.5)

axes[0, 1].plot(us_graph_df['date'], us_graph_df['poil'], color = 'green', linewidth = 1.5)
axes[0, 1].set_title("2. Oil Prices ($poil$)", fontsize = 12, pad = 10)
axes[0, 1].grid(True, linestyle = "--", alpha = 0.5)

axes[0, 2].plot(us_graph_df['date'], us_graph_df['Dp'], color = 'purple', linewidth = 1.5)
axes[0, 2].set_title("3. US Inflation ($Dp$)", fontsize = 12, pad = 10)
axes[0, 2].grid(True, linestyle = "--", alpha = 0.5)

axes[1, 0].plot(us_graph_df['date'], us_graph_df['r'], color = 'red', linewidth = 1.5)
axes[1, 0].set_title("4. US Interest Rates ($r$)", fontsize = 12, pad = 10)
axes[1, 0].grid(True, linestyle = "--", alpha = 0.5)

axes[1, 1].plot(us_graph_df['date'], us_graph_df['eps'], color = 'orange', linewidth = 1.5)
axes[1, 1].set_title("5. US FX Rate ($eps$)", fontsize = 12, pad = 10)
axes[1, 1].grid(True, linestyle = "--", alpha = 0.5)


# Clean up X-axis ticks (Quarterly data can crowd the axes)
# Show a tick every 20 quarters (5 years) to keep it scannable
tick_spacing = 20
visible_ticks = us_graph_df['date'][::tick_spacing]

for ax in axes.flat:
    ax.set_xticks(visible_ticks)
    ax.tick_params(axis = 'x', labelrotation = 45, labelsize = 9)

# adjust margins and display
plt.tight_layout(rect = [0, 0, 1, 0.93])
plt.show()