In [28]:
import numpy as np
import pandas as pd
import os
from datetime import datetime, date
from statsmodels.tsa.vector_ar.var_model import VAR
from statsmodels.tsa.vector_ar.vecm import VECM
from scipy.linalg import eig
print(f"modules have been imported.")

modules have been imported.

In [11]:
# Step 1: to simulate dummy macroeconomic data for 4 economies (T=100 periods)

np.random.seed(42)

num_periods = 100
economies = ['SG','US','CN','EU']
variables = ['gdp', 'inf', 'int']

columns = [f"{eco}_{var}" for eco in economies for var in variables]
data = pd.DataFrame(np.random.randn(num_periods, len(columns)), columns = columns)
display(data)

# 2. define fixed trade weights matrix (rows sum to 1, diags to 0)
# Rows: SG, US, CN, EU | Cols: SG, US, CN, EU

W = np.array([
    [0.0, 0.3, 0.4, 0.3], # SG trade partners
    [0.1, 0.0, 0.5, 0.4], # US trade partners
    [0.2, 0.4, 0.0, 0.4], # CN trade partners
    [0.2, 0.4, 0.4, 0.0]  # EU trade partners
])

W

,SG_gdp,SG_inf,SG_int,US_gdp,US_inf,US_int,CN_gdp,CN_inf,CN_int,EU_gdp,EU_inf,EU_int
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560,-0.463418,-0.465730
1,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304,1.465649,-0.225776,0.067528,-1.424748
2,-0.544383,0.110923,-1.150994,0.375698,-0.600639,-0.291694,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844
3,0.208864,-1.959670,-1.328186,0.196861,0.738467,0.171368,-0.115648,-0.301104,-1.478522,-0.719844,-0.460639,1.057122
4,0.343618,-1.763040,0.324084,-0.385082,-0.676922,0.611676,1.031000,0.931280,-0.839218,-0.309212,0.331263,0.975545
...,...,...,...,...,...,...,...,...,...,...,...,...
95,-0.297564,1.375707,-0.150056,0.125576,-0.173072,0.015579,-1.096275,-1.440051,1.594505,-0.846961,-0.991392,-2.153390
96,-0.638962,-1.323090,1.642015,1.009817,-0.688150,2.252436,0.981765,-0.324831,-2.499406,2.290943,-1.389572,-1.645399
97,1.022570,2.439752,1.384273,0.563909,0.594754,0.853416,0.758929,0.281191,0.104201,-0.062593,-0.753965,-0.280675
98,-1.692957,-0.098340,-0.988591,-1.103589,0.179894,1.392002,0.918317,-1.570501,-0.989628,0.940771,-0.982487,-0.224633
99,0.550052,-0.968344,0.105376,-1.334025,-0.601368,0.319782,-1.592994,0.440475,-0.019638,0.552490,0.223914,1.364140

array([[0. , 0.3, 0.4, 0.3],
       [0.1, 0. , 0.5, 0.4],
       [0.2, 0.4, 0. , 0.4],
       [0.2, 0.4, 0.4, 0. ]])

In [19]:
# 3. Construct Foreign Variables (X*) for Singapore (SG) as an example
sg_partners_data = data[[col for col in data.columns if not col.startswith('SG')]]
sg_partners_data

# reshape partners data to compute weighted average easily.
sg_w = W[0,1:]  # weights for US, CN, EU
sg_w

gdp_star = data['US_gdp'] * sg_w[0] + data['CN_gdp'] * sg_w[1] + data['EU_gdp'] * sg_w[2]
inf_star = data['US_inf'] * sg_w[0] + data['CN_inf'] * sg_w[1] + data['EU_inf'] * sg_w[2]
int_star = data['US_int'] * sg_w[0] + data['CN_int'] * sg_w[1] + data['EU_int'] * sg_w[2]

X_sg_domestic = data[['SG_gdp', 'SG_inf', 'SG_int']]
X_sg_foreign = pd.DataFrame({'gdp_star' : gdp_star,
                            'inf_star' : inf_star,
                            'int_star': int_star})

print(f"X_sg_domestic is: {display(X_sg_domestic)}")
print(f"X_sg_foreign is: {display(X_sg_foreign)}")

      SG_gdp    SG_inf    SG_int
0   0.496714 -0.138264  0.647689
1   0.241962 -1.913280 -1.724918
2  -0.544383  0.110923 -1.150994
3   0.208864 -1.959670 -1.328186
4   0.343618 -1.763040  0.324084
..       ...       ...       ...
95 -0.297564  1.375707 -0.150056
96 -0.638962 -1.323090  1.642015
97  1.022570  2.439752  1.384273
98 -1.692957 -0.098340 -0.988591
99  0.550052 -0.968344  0.105376

[100 rows x 3 columns]

X_sg_domestic is: None

    gdp_star  inf_star  int_star
0   1.251362  0.097703 -0.397750
1  -0.599629 -0.848512  0.253109
2  -0.445287  0.807483 -0.459160
3  -0.203154 -0.037093 -0.222862
4   0.204111  0.268814  0.140479
..       ...       ...       ...
95 -0.654926 -0.925360 -0.003541
96  1.382934 -0.753249 -0.817651
97  0.453966  0.064713  0.213503
98  0.318481 -0.868978 -0.045641
99 -0.871658  0.062954  0.497322

[100 rows x 3 columns]

X_sg_foreign is: None

In [25]:
# 4. Fit VARX(1) for Singapore
# Note: Treat contemporaneous foreign variables and their lags as exog
exog_data = pd.concat([X_sg_foreign, X_sg_foreign.shift(1)], axis = 1).dropna()
exog_data.columns = ['gdp_star', 'inf_star', 'int_star', 'gdp_star_lag1', 'inf_star_lag1', 'int_star_lag1']
endog_data = X_sg_domestic.iloc[1:] # Align time index due to lag shift.

print(f"X_sg_foreign is: {display(X_sg_foreign)}")
print(f"X_sg_foreign.shift(1) is: {display(X_sg_foreign.shift(1).dropna())}")
print(f"exog_data is: {display(exog_data)}")

varx_model = VAR(endog_data, exog=exog_data)
varx_results = varx_model.fit(maxlags = 1)
print(varx_results.summary())

    gdp_star  inf_star  int_star
0   1.251362  0.097703 -0.397750
1  -0.599629 -0.848512  0.253109
2  -0.445287  0.807483 -0.459160
3  -0.203154 -0.037093 -0.222862
4   0.204111  0.268814  0.140479
..       ...       ...       ...
95 -0.654926 -0.925360 -0.003541
96  1.382934 -0.753249 -0.817651
97  0.453966  0.064713  0.213503
98  0.318481 -0.868978 -0.045641
99 -0.871658  0.062954  0.497322

[100 rows x 3 columns]

X_sg_foreign is: None

    gdp_star  inf_star  int_star
1   1.251362  0.097703 -0.397750
2  -0.599629 -0.848512  0.253109
3  -0.445287  0.807483 -0.459160
4  -0.203154 -0.037093 -0.222862
5   0.204111  0.268814  0.140479
..       ...       ...       ...
95 -0.339369  1.048968  0.822200
96 -0.654926 -0.925360 -0.003541
97  1.382934 -0.753249 -0.817651
98  0.453966  0.064713  0.213503
99  0.318481 -0.868978 -0.045641

[99 rows x 3 columns]

X_sg_foreign.shift(1) is: None

    gdp_star  inf_star  int_star  gdp_star_lag1  inf_star_lag1  int_star_lag1
1  -0.599629 -0.848512  0.253109       1.251362       0.097703      -0.397750
2  -0.445287  0.807483 -0.459160      -0.599629      -0.848512       0.253109
3  -0.203154 -0.037093 -0.222862      -0.445287       0.807483      -0.459160
4   0.204111  0.268814  0.140479      -0.203154      -0.037093      -0.222862
5  -0.581202  0.753590  1.012937       0.204111       0.268814       0.140479
..       ...       ...       ...            ...            ...            ...
95 -0.654926 -0.925360 -0.003541      -0.339369       1.048968       0.822200
96  1.382934 -0.753249 -0.817651      -0.654926      -0.925360      -0.003541
97  0.453966  0.064713  0.213503       1.382934      -0.753249      -0.817651
98  0.318481 -0.868978 -0.045641       0.453966       0.064713       0.213503
99 -0.871658  0.062954  0.497322       0.318481      -0.868978      -0.045641

[99 rows x 6 columns]

exog_data is: None
  Summary of Regression Results
==================================
Model:                         VAR
Method:                        OLS
Date:           Sat, 18, Jul, 2026
Time:                     16:14:26
--------------------------------------------------------------------
No. of Equations:         3.00000    BIC:                   0.748487
Nobs:                     98.0000    HQIC:                  0.277242
Log likelihood:          -385.069    FPE:                   0.960126
AIC:                   -0.0428295    Det(Omega_mle):        0.717356
--------------------------------------------------------------------
Results for equation SG_gdp
================================================================================
                   coefficient       std. error           t-stat            prob
--------------------------------------------------------------------------------
const                 0.081888         0.093012            0.880           0.379
gdp_star             -0.198692         0.166244           -1.195           0.232
inf_star              0.059982         0.151984            0.395           0.693
int_star              0.068809         0.153081            0.449           0.653
gdp_star_lag1         0.010342         0.172344            0.060           0.952
inf_star_lag1         0.038620         0.149348            0.259           0.796
int_star_lag1         0.044496         0.149896            0.297           0.767
L1.SG_gdp             0.067901         0.106957            0.635           0.526
L1.SG_inf            -0.054075         0.094775           -0.571           0.568
L1.SG_int             0.018525         0.091264            0.203           0.839
================================================================================

Results for equation SG_inf
================================================================================
                   coefficient       std. error           t-stat            prob
--------------------------------------------------------------------------------
const                -0.112043         0.103933           -1.078           0.281
gdp_star              0.142107         0.185763            0.765           0.444
inf_star              0.044938         0.169829            0.265           0.791
int_star             -0.054194         0.171055           -0.317           0.751
gdp_star_lag1         0.226641         0.192580            1.177           0.239
inf_star_lag1        -0.011498         0.166884           -0.069           0.945
int_star_lag1         0.169931         0.167496            1.015           0.310
L1.SG_gdp            -0.027388         0.119515           -0.229           0.819
L1.SG_inf             0.022802         0.105903            0.215           0.830
L1.SG_int             0.065382         0.101980            0.641           0.521
================================================================================

Results for equation SG_int
================================================================================
                   coefficient       std. error           t-stat            prob
--------------------------------------------------------------------------------
const                -0.000657         0.104624           -0.006           0.995
gdp_star              0.182442         0.186998            0.976           0.329
inf_star             -0.228335         0.170958           -1.336           0.182
int_star              0.018344         0.172192            0.107           0.915
gdp_star_lag1         0.062509         0.193860            0.322           0.747
inf_star_lag1        -0.193264         0.167993           -1.150           0.250
int_star_lag1        -0.126735         0.168609           -0.752           0.452
L1.SG_gdp             0.195615         0.120309            1.626           0.104
L1.SG_inf             0.106300         0.106606            0.997           0.319
L1.SG_int            -0.023529         0.102657           -0.229           0.819
================================================================================

Correlation matrix of residuals
            SG_gdp    SG_inf    SG_int
SG_gdp    1.000000 -0.032369 -0.036206
SG_inf   -0.032369  1.000000 -0.048429
SG_int   -0.036206 -0.048429  1.000000

In [36]:
# Create Johansens test

# 1. Simulate a system where 2 variables are explicitly cointegrated (share a trend)
np.random.seed(42)
T = 200

# Common non-stationary stochastic trend (Random Walk)
common_trend = np.cumsum(np.random.normal(0,1,T))
common_trend

# Generate 3 long-term variables (z_t)
z1 = common_trend + np.random.normal(0,0.5, T) # Driven by trend
z2 = 0.8 * common_trend + np.random.normal(0, 0.5, T) # Cointegrated with z1
z3 = np.cumsum(np.random.normal(0, 1, T)) # Independent random walk

Z = np.vstack([z1, z2, z3]).T # shape: (T, 3)
print(f"Z matrix is: {Z}")
print(f"Z shape is: {Z.shape}")

# 2. prepare the VECM Data Arrays
# Z_t (current levels), Z_lag (lagged levels), dZ (differences)
dZ = np.diff(Z, axis = 0)  # \Delta z_t
Z_lag = Z[:-1, :]  # z_{t-1}
print(f"dZ matrix is: {dZ}")
print(f"dZ shape is: {dZ.shape}")
print(f"Z_lag matrix is: {Z_lag}")
print(f"Z_lag shape is: {Z_lag.shape}")

T_effective = dZ.shape[0] # no of rows (199)
k = Z.shape[1] # no. of variables (3).

Z matrix is: [[ 6.75607833e-01 -3.99842507e-01  7.56988617e-01]
 [ 6.38842115e-01 -1.29276300e-02 -1.65176708e-01]
 [ 1.54766401e+00  8.07532562e-01  7.04429213e-01]
 [ 3.05606927e+00  2.04682489e+00  2.06006707e+00]
 [ 1.60618019e+00  1.61097916e+00  2.47350197e+00]
 [ 1.59196539e+00  1.96012730e+00  4.35029779e+00]
 [ 3.89760836e+00  2.37826237e+00  3.57650859e+00]
 [ 4.66441843e+00  3.45483062e+00  2.33185388e+00]
 [ 4.19557492e+00  3.21058867e+00  5.53133636e-01]
 [ 6.40697686e+00  3.84170831e+00  2.04917795e+00]
 [ 4.30263868e+00  3.56956218e+00  2.70354360e+00]
 [ 4.11924649e+00  2.27884989e+00  2.64795893e+00]
 [ 4.27042682e+00  2.26768367e+00  2.92792756e+00]
 [ 2.20584132e+00  2.14295497e+00  1.80243851e+00]
 [-2.40675732e-03  2.90339298e-01  4.24819049e+00]
 [-2.75750540e-02 -6.99891000e-01  4.37741167e+00]
 [-1.80630339e+00 -3.60336640e-01  4.48680647e+00]
 [-1.22405276e+00 -8.26677444e-01  5.21257309e+00]
 [-2.25634930e+00 -1.02128543e+00  5.69358232e+00]
 [-3.38503416e+00 -2.70701774e+00  5.91746635e+00]
 [-8.02993177e-01 -5.37884005e-01  5.12699189e+00]
 [-3.11973136e+00 -8.71208587e-01  5.59846025e+00]
 [-1.77544046e+00 -1.81933852e+00  7.48048475e+00]
 [-4.34967668e+00 -2.34886952e+00  8.82590479e+00]
 [-4.32366740e+00 -2.94747320e+00  1.04190914e+01]
 [-3.43230358e+00 -2.49710732e+00  9.90787574e+00]
 [-5.09563244e+00 -4.58467969e+00  8.91827092e+00]
 [-5.29094682e+00 -3.45863382e+00  8.79248400e+00]
 [-5.71036498e+00 -3.75295826e+00  8.84820891e+00]
 [-5.30460800e+00 -5.39489524e+00  9.94240043e+00]
 [-6.61129680e+00 -5.58852005e+00  8.24993580e+00]
 [-4.28560601e+00 -4.53468433e+00  9.77948612e+00]
 [-4.38454661e+00 -3.66056944e+00  9.62147822e+00]
 [-5.79084363e+00 -4.01326364e+00  9.19459715e+00]
 [-3.57052650e+00 -2.96282031e+00  8.18249278e+00]
 [-5.54638268e+00 -4.65362637e+00  6.52763611e+00]
 [-6.66704989e+00 -3.70927511e+00  7.35080669e+00]
 [-7.52092157e+00 -6.78136971e+00  7.42412466e+00]
 [-9.27322800e+00 -8.00555904e+00  6.13416376e+00]
 [-8.31925687e+00 -7.02415268e+00  4.83908499e+00]
 [-8.40326733e+00 -6.21357284e+00  4.50330029e+00]
 [-7.89300690e+00 -6.28485831e+00  6.17232181e+00]
 [-7.69879332e+00 -7.39475062e+00  5.91273046e+00]
 [-7.81951306e+00 -6.64647254e+00  4.40958751e+00]
 [-1.03310608e+01 -8.43696487e+00  4.16384444e+00]
 [-1.06180075e+01 -8.02576921e+00  3.89112087e+00]
 [-1.11488683e+01 -8.54581738e+00  1.19423423e+00]
 [-1.01809380e+01 -8.35335861e+00  1.13993936e+00]
 [-8.62792799e+00 -7.86545754e+00  9.09004834e-01]
 [-1.10712044e+01 -9.54856297e+00  1.60521120e+00]
 [-1.15800533e+01 -8.79102858e+00  3.45416729e+00]
 [-1.08757626e+01 -8.59018370e+00  4.58073232e+00]
 [-1.09505375e+01 -1.01021555e+01  4.31184363e+00]
 [-1.08837067e+01 -8.86792817e+00  3.20531772e+00]
 [-1.11286247e+01 -8.56028062e+00  5.77867753e+00]
 [-9.67977668e+00 -7.94656413e+00  5.83789596e+00]
 [-9.64342159e+00 -8.27501691e+00  5.85182525e+00]
 [-1.09399243e+01 -8.98649280e+00  5.82770017e+00]
 [-1.00329164e+01 -8.48068554e+00  6.02578493e+00]
 [-8.89196396e+00 -8.02236373e+00  5.88142452e+00]
 [-1.02219205e+01 -6.82440161e+00  5.30776251e+00]
 [-9.97387688e+00 -7.93765958e+00  4.76090357e+00]
 [-1.26710828e+01 -9.19022209e+00  4.72815030e+00]
 [-1.27588496e+01 -9.69033468e+00  4.18472553e+00]
 [-1.15604141e+01 -9.20346800e+00  3.47187974e+00]
 [-1.07017815e+01 -8.17279676e+00  3.57830997e+00]
 [-9.33369442e+00 -7.81283670e+00  3.32333275e+00]
 [-9.86143786e+00 -6.93833988e+00  4.82732574e+00]
 [-9.00475339e+00 -7.29303549e+00  2.17635593e+00]
 [-9.36448061e+00 -7.83178984e+00  3.26786279e+00]
 [-8.34781865e+00 -7.39229008e+00  4.51394798e+00]
 [-8.24834980e+00 -7.17529556e+00  2.44055775e+00]
 [-6.98466289e+00 -6.81059134e+00  2.09787015e+00]
 [-5.99648458e+00 -4.11784375e+00  1.72642929e+00]
 [-9.11210054e+00 -6.07459311e+00  3.18917591e-01]
 [-7.56839197e+00 -6.36407299e+00 -4.58899097e-01]
 [-7.61286679e+00 -5.88163883e+00 -1.56947494e+00]
 [-8.31151243e+00 -6.25349812e+00  1.82795501e-01]
 [-7.88474217e+00 -4.79627417e+00  1.11847389e+00]
 [-1.00998689e+01 -7.36598225e+00  2.39002899e+00]
 [-1.00701253e+01 -8.16546601e+00  3.11170105e+00]
 [-9.43870611e+00 -8.29358738e+00  1.98264928e+00]
 [-7.49886899e+00 -7.43672508e+00  1.45812902e+00]
 [-9.42905537e+00 -6.94638628e+00  1.94750358e+00]
 [-8.55212454e+00 -8.07308835e+00  7.25375768e-01]
 [-1.10964422e+01 -8.80744547e+00  1.43837420e+00]
 [-9.28088870e+00 -7.68728336e+00  1.19804880e+00]
 [-8.58208644e+00 -7.64177003e+00  8.23227993e-01]
 [-9.26550931e+00 -6.68123338e+00  1.53418796e+00]
 [-9.20408757e+00 -6.67337037e+00  1.97845127e+00]
 [-8.89972139e+00 -7.04051453e+00  1.61748511e+00]
 [-8.07351574e+00 -5.52164015e+00  2.77681491e+00]
 [-8.82375074e+00 -6.78457054e+00  1.69575158e+00]
 [-8.43192946e+00 -7.51602651e+00  2.31168719e+00]
 [-9.07033092e+00 -6.63750889e+00  2.90478845e+00]
 [-1.10588084e+01 -8.30042787e+00  2.59524201e+00]
 [-9.96643340e+00 -8.85160975e+00  2.92137503e+00]
 [-1.00015283e+01 -8.21931179e+00  1.67026145e+00]
 [-9.74363355e+00 -8.55786081e+00  2.59428847e+00]
 [-1.00698373e+01 -8.99912126e+00  2.40938634e+00]
 [-1.22145200e+01 -8.97692921e+00  1.88666332e+00]
 [-1.25007583e+01 -8.82182592e+00  2.93567254e+00]
 [-1.21897355e+01 -1.07499896e+01  2.23132885e+00]
 [-1.30604745e+01 -1.04110431e+01  8.22867555e-01]
 [-1.35373961e+01 -1.11468775e+01 -7.33761619e-01]
 [-1.30642308e+01 -1.07418782e+01 -1.27751667e-01]
 [-1.05978761e+01 -9.28556380e+00 -1.40818102e+00]
 [-1.13579164e+01 -9.28169997e+00  3.46613162e-01]
 [-1.05310316e+01 -8.61940346e+00 -1.73531625e+00]
 [-1.09801226e+01 -9.11869606e+00 -3.88598774e-02]
 [-1.29066381e+01 -1.01030096e+01  1.72157590e-01]
 [-1.22749229e+01 -1.02845681e+01  7.54444779e-02]
 [-1.23513730e+01 -1.03307389e+01 -4.69474609e-01]
 [-9.89408421e+00 -8.69445305e+00 -7.03384945e-02]
 [-9.84046059e+00 -8.68294566e+00 -1.07973197e-01]
 [-1.01811507e+01 -7.77562650e+00  9.95328685e-01]
 [-9.88538793e+00 -7.93063294e+00  1.10955633e+00]
 [-1.15501758e+01 -9.60481159e+00  1.25985810e+00]
 [-1.00901365e+01 -8.15210956e+00  8.96245883e-01]
 [-9.56535813e+00 -7.22453572e+00  8.39300259e-01]
 [-8.66075668e+00 -7.80210637e+00  1.14710203e+00]
 [-9.32106360e+00 -7.42323360e+00 -5.63066365e-01]
 [-8.62495815e+00 -6.90399012e+00 -1.91125179e+00]
 [-8.57150523e+00 -7.40885976e+00 -1.16798769e+00]
 [-9.53385046e+00 -7.60630300e+00 -9.97122254e-01]
 [-7.44748045e+00 -6.37474997e+00 -1.18110559e+00]
 [-7.25186704e+00 -7.07850920e+00 -1.16267166e+00]
 [-8.00138885e+00 -6.69373369e+00 -8.15089952e-01]
 [-7.98550893e+00 -6.50819382e+00 -1.35484963e+00]
 [-8.48687174e+00 -7.49299390e+00 -2.13315436e+00]
 [-1.03578313e+01 -7.96207011e+00 -1.93730910e+00]
 [-1.07317721e+01 -9.05727599e+00 -2.91568188e+00]
 [-1.13075464e+01 -9.10939883e+00 -2.50742912e+00]
 [-1.12104371e+01 -9.30299308e+00 -4.21001273e+00]
 [-1.13037206e+01 -9.75894243e+00 -3.18085709e+00]
 [-1.03148747e+01 -8.16937751e+00 -2.70825961e+00]
 [-1.14373479e+01 -9.24988616e+00 -2.45222988e+00]
 [-1.15073538e+01 -9.26960647e+00 -1.46953889e+00]
 [-1.03266779e+01 -7.92336852e+00  1.95935553e-01]
 [-1.20458702e+01 -9.69965231e+00  1.21030562e+00]
 [-1.19476582e+01 -8.81139237e+00 -6.30568613e-01]
 [-1.01075617e+01 -8.74837765e+00 -1.91014558e+00]
 [-1.17144052e+01 -9.20460872e+00 -2.53496416e+00]
 [-1.19057262e+01 -8.60101941e+00 -2.50887311e+00]
 [-1.16278910e+01 -1.03497197e+01 -1.99121409e+00]
 [-1.04945240e+01 -8.88688682e+00 -2.71695790e+00]
 [-1.25715419e+01 -9.18946370e+00 -2.53019114e+00]
 [-1.38716882e+01 -1.06358877e+01 -3.28557407e+00]
 [-1.30052369e+01 -9.93123886e+00 -3.89709187e+00]
 [-1.24557536e+01 -1.01812167e+01 -5.30375297e+00]
 [-1.19430834e+01 -9.63553488e+00 -6.22698621e+00]
 [-1.10144109e+01 -9.47950983e+00 -7.57867082e+00]
 [-1.20032839e+01 -9.36179996e+00 -8.55454407e+00]
 [-1.22798293e+01 -9.63267761e+00 -7.50090228e+00]
 [-1.19162957e+01 -9.35662872e+00 -8.45030116e+00]
 [-1.31224037e+01 -1.03028497e+01 -5.81791910e+00]
 [-1.07646210e+01 -8.84809469e+00 -5.32460120e+00]
 [-1.04258609e+01 -8.44150433e+00 -5.13976508e+00]
 [-1.13114758e+01 -8.98104197e+00 -5.99812286e+00]
 [-1.12298969e+01 -8.86351739e+00 -5.29781298e+00]
 [-1.15312899e+01 -9.28788306e+00 -5.87345080e+00]
 [-1.02375090e+01 -7.76540240e+00 -5.75144099e+00]
 [-9.89966300e+00 -7.44066399e+00 -3.19135645e+00]
 [-1.04651094e+01 -8.69578396e+00 -3.28741635e+00]
 [-9.35751712e+00 -7.16146433e+00 -2.13814302e+00]
 [-9.49041842e+00 -7.63588424e+00 -2.84131945e+00]
 [-8.35570179e+00 -7.79326069e+00 -2.87630794e+00]
 [-6.56465885e+00 -5.76080719e+00 -1.10550730e+00]
 [-6.76750511e+00 -6.38847049e+00 -1.73247436e+00]
 [-7.95658422e+00 -6.23182020e+00  7.99741975e-02]
 [-8.44733867e+00 -6.75846581e+00  7.87726133e-01]
 [-9.02640490e+00 -6.58210458e+00  2.25259357e-01]
 [-8.62693395e+00 -7.31854091e+00  8.57667096e-01]
 [-8.53171836e+00 -7.31863328e+00  1.83022155e+00]
 [-7.65807175e+00 -6.57302759e+00  2.45203151e+00]
 [-8.29115351e+00 -7.43155144e+00  8.81806788e-01]
 [-7.45831752e+00 -6.19777499e+00  1.54669612e-01]
 [-6.34927275e+00 -4.76732241e+00 -9.28490233e-02]
 [-5.61069912e+00 -6.10377360e+00 -1.67282452e-01]
 [-4.38958057e+00 -2.61646812e+00  4.53389645e-01]
 [-3.77962500e+00 -2.51856306e+00  6.31090646e-01]
 [-4.51661796e+00 -3.58118126e+00 -7.04253713e-01]
 [-6.34976199e+00 -3.91386037e+00 -3.24055862e-01]
 [-5.06821923e+00 -2.70892694e+00  2.86529884e-01]
 [-5.40837083e+00 -3.93211047e+00  8.46320332e-01]
 [-4.23960711e+00 -3.32773291e+00  1.92710106e+00]
 [-3.67068839e+00 -3.30293356e+00  2.76102321e+00]
 [-2.97630988e+00 -3.55643842e+00  3.22020329e+00]
 [-4.28597709e+00 -3.39378330e+00  3.15003758e+00]
 [-6.56448807e+00 -5.44887090e+00  1.48907665e+00]
 [-7.17175853e+00 -5.34225783e+00  1.91869487e+00]
 [-5.62019281e+00 -4.93175064e+00  2.12638255e+00]
 [-6.31217526e+00 -4.28215701e+00  2.39796139e+00]
 [-5.98206805e+00 -5.35140689e+00  1.12121281e+00]
 [-6.13489644e+00 -4.86092323e+00  4.01562732e-02]
 [-6.57388695e+00 -5.32644750e+00  1.09330913e+00]
 [-8.07972383e+00 -5.91346272e+00  1.05375397e+00]
 [-6.39249527e+00 -6.14492702e+00  1.73525467e+00]
 [-7.06849266e+00 -5.83112482e+00  1.76357305e+00]
 [-7.53528488e+00 -6.33470418e+00  1.79332919e+00]]
Z shape is: (200, 3)
dZ matrix is: [[-3.67657182e-02  3.86914877e-01 -9.22165324e-01]
 [ 9.08821897e-01  8.20460192e-01  8.69605920e-01]
 [ 1.50840526e+00  1.23929233e+00  1.35563786e+00]
 [-1.44988908e+00 -4.35845732e-01  4.13434903e-01]
 [-1.42147929e-02  3.49148136e-01  1.87679581e+00]
 [ 2.30564297e+00  4.18135072e-01 -7.73789199e-01]
 [ 7.66810071e-01  1.07656826e+00 -1.24465470e+00]
 [-4.68843518e-01 -2.44241950e-01 -1.77872025e+00]
 [ 2.21140195e+00  6.31119636e-01  1.49604431e+00]
 [-2.10433818e+00 -2.72146132e-01  6.54365656e-01]
 [-1.83392189e-01 -1.29071229e+00 -5.55846709e-02]
 [ 1.51180333e-01 -1.11662222e-02  2.79968626e-01]
 [-2.06458550e+00 -1.24728699e-01 -1.12548905e+00]
 [-2.20824808e+00 -1.85261567e+00  2.44575198e+00]
 [-2.51682967e-02 -9.90230298e-01  1.29221182e-01]
 [-1.77872834e+00  3.39554360e-01  1.09394795e-01]
 [ 5.82250636e-01 -4.66340805e-01  7.25766624e-01]
 [-1.03229655e+00 -1.94607986e-01  4.81009232e-01]
 [-1.12868486e+00 -1.68573231e+00  2.23884024e-01]
 [ 2.58204098e+00  2.16913374e+00 -7.90474455e-01]
 [-2.31673818e+00 -3.33324582e-01  4.71468357e-01]
 [ 1.34429090e+00 -9.48129932e-01  1.88202450e+00]
 [-2.57423622e+00 -5.29530999e-01  1.34542005e+00]
 [ 2.60092782e-02 -5.98603680e-01  1.59318663e+00]
 [ 8.91363821e-01  4.50365876e-01 -5.11215676e-01]
 [-1.66332887e+00 -2.08757237e+00 -9.89604820e-01]
 [-1.95314380e-01  1.12604587e+00 -1.25786920e-01]
 [-4.19418156e-01 -2.94324439e-01  5.57249123e-02]
 [ 4.05756979e-01 -1.64193699e+00  1.09419152e+00]
 [-1.30668880e+00 -1.93624803e-01 -1.69246463e+00]
 [ 2.32569080e+00  1.05383572e+00  1.52955032e+00]
 [-9.89405996e-02  8.74114892e-01 -1.58007899e-01]
 [-1.40629702e+00 -3.52694198e-01 -4.26881070e-01]
 [ 2.22031713e+00  1.05044333e+00 -1.01210438e+00]
 [-1.97585618e+00 -1.69080606e+00 -1.65485667e+00]
 [-1.12066721e+00  9.44351259e-01  8.23170584e-01]
 [-8.53871673e-01 -3.07209460e+00  7.33179672e-02]
 [-1.75230644e+00 -1.22418933e+00 -1.28996090e+00]
 [ 9.53971136e-01  9.81406359e-01 -1.29507877e+00]
 [-8.40104566e-02  8.10579838e-01 -3.35784699e-01]
 [ 5.10260430e-01 -7.12854736e-02  1.66902153e+00]
 [ 1.94213578e-01 -1.10989230e+00 -2.59591351e-01]
 [-1.20719738e-01  7.48278074e-01 -1.50314295e+00]
 [-2.51154779e+00 -1.79049232e+00 -2.45743064e-01]
 [-2.86946623e-01  4.11195658e-01 -2.72723570e-01]
 [-5.30860809e-01 -5.20048168e-01 -2.69688664e+00]
 [ 9.67930266e-01  1.92458765e-01 -5.42948665e-02]
 [ 1.55301003e+00  4.87901066e-01 -2.30934530e-01]
 [-2.44327642e+00 -1.68310543e+00  6.96206365e-01]
 [-5.08848863e-01  7.57534388e-01  1.84895609e+00]
 [ 7.04290670e-01  2.00844885e-01  1.12656503e+00]
 [-7.47748753e-02 -1.51197178e+00 -2.68888691e-01]
 [ 6.68308206e-02  1.23422731e+00 -1.10652591e+00]
 [-2.44918091e-01  3.07647551e-01  2.57335980e+00]
 [ 1.44884807e+00  6.13716488e-01  5.92184340e-02]
 [ 3.63550878e-02 -3.28452782e-01  1.39292919e-02]
 [-1.29650268e+00 -7.11475882e-01 -2.41250871e-02]
 [ 9.07007878e-01  5.05807254e-01  1.98084761e-01]
 [ 1.14095244e+00  4.58321808e-01 -1.44360412e-01]
 [-1.32995650e+00  1.19796212e+00 -5.73662007e-01]
 [ 2.48043581e-01 -1.11325797e+00 -5.46858941e-01]
 [-2.69720597e+00 -1.25256251e+00 -3.27532702e-02]
 [-8.77667747e-02 -5.00112590e-01 -5.43424771e-01]
 [ 1.19843557e+00  4.86866678e-01 -7.12845783e-01]
 [ 8.58632513e-01  1.03067125e+00  1.06430228e-01]
 [ 1.36808712e+00  3.59960053e-01 -2.54977217e-01]
 [-5.27743443e-01  8.74496823e-01  1.50399299e+00]
 [ 8.56684471e-01 -3.54695609e-01 -2.65096981e+00]
 [-3.59727223e-01 -5.38754350e-01  1.09150685e+00]
 [ 1.01666196e+00  4.39499756e-01  1.24608519e+00]
 [ 9.94688463e-02  2.16994519e-01 -2.07339023e+00]
 [ 1.26368691e+00  3.64704220e-01 -3.42687594e-01]
 [ 9.88178310e-01  2.69274759e+00 -3.71440866e-01]
 [-3.11561596e+00 -1.95674936e+00 -1.40751169e+00]
 [ 1.54370857e+00 -2.89479873e-01 -7.77816688e-01]
 [-4.44748211e-02  4.82434156e-01 -1.11057585e+00]
 [-6.98645637e-01 -3.71859285e-01  1.75227044e+00]
 [ 4.26770258e-01  1.45722395e+00  9.35678393e-01]
 [-2.21512676e+00 -2.56970808e+00  1.27155509e+00]
 [ 2.97435832e-02 -7.99483762e-01  7.21672064e-01]
 [ 6.31419236e-01 -1.28121367e-01 -1.12905177e+00]
 [ 1.93983712e+00  8.56862296e-01 -5.24520266e-01]
 [-1.93018638e+00  4.90338803e-01  4.89374561e-01]
 [ 8.76930834e-01 -1.12670207e+00 -1.22212781e+00]
 [-2.54431763e+00 -7.34357117e-01  7.12998430e-01]
 [ 1.81555347e+00  1.12016211e+00 -2.40325398e-01]
 [ 6.98802260e-01  4.55133280e-02 -3.74820808e-01]
 [-6.83422873e-01  9.60536656e-01  7.10959968e-01]
 [ 6.14217393e-02  7.86300743e-03  4.44263311e-01]
 [ 3.04366184e-01 -3.67144160e-01 -3.60966166e-01]
 [ 8.26205648e-01  1.51887438e+00  1.15932980e+00]
 [-7.50235005e-01 -1.26293039e+00 -1.08106333e+00]
 [ 3.91821280e-01 -7.31455972e-01  6.15935607e-01]
 [-6.38401459e-01  8.78517617e-01  5.93101258e-01]
 [-1.98847749e+00 -1.66291898e+00 -3.09546439e-01]
 [ 1.09237501e+00 -5.51181877e-01  3.26133022e-01]
 [-3.50949051e-02  6.32297956e-01 -1.25111358e+00]
 [ 2.57894756e-01 -3.38549022e-01  9.24027019e-01]
 [-3.26203772e-01 -4.41260445e-01 -1.84902136e-01]
 [-2.14468267e+00  2.21920456e-02 -5.22723021e-01]
 [-2.86238337e-01  1.55103288e-01  1.04900923e+00]
 [ 3.11022806e-01 -1.92816372e+00 -7.04343691e-01]
 [-8.70738939e-01  3.38946590e-01 -1.40846130e+00]
 [-4.76921641e-01 -7.35834472e-01 -1.55662917e+00]
 [ 4.73165345e-01  4.04999278e-01  6.06009951e-01]
 [ 2.46635466e+00  1.45631445e+00 -1.28042935e+00]
 [-7.60040329e-01  3.86382754e-03  1.75479418e+00]
 [ 8.26884776e-01  6.62296511e-01 -2.08192941e+00]
 [-4.49090933e-01 -4.99292605e-01  1.69645637e+00]
 [-1.92651549e+00 -9.84313501e-01  2.11017467e-01]
 [ 6.31715152e-01 -1.81558568e-01 -9.67131119e-02]
 [-7.64500416e-02 -4.61708008e-02 -5.44919087e-01]
 [ 2.45728876e+00  1.63628588e+00  3.99136114e-01]
 [ 5.36236208e-02  1.15073939e-02 -3.76347024e-02]
 [-3.40690140e-01  9.07319152e-01  1.10330188e+00]
 [ 2.95762795e-01 -1.55006435e-01  1.14227649e-01]
 [-1.66478790e+00 -1.67417865e+00  1.50301761e-01]
 [ 1.46003937e+00  1.45270203e+00 -3.63612212e-01]
 [ 5.24778329e-01  9.27573835e-01 -5.69456237e-02]
 [ 9.04601457e-01 -5.77570645e-01  3.07801769e-01]
 [-6.60306925e-01  3.78872773e-01 -1.71016839e+00]
 [ 6.96105457e-01  5.19243473e-01 -1.34818542e+00]
 [ 5.34529167e-02 -5.04869636e-01  7.43264094e-01]
 [-9.62345235e-01 -1.97443238e-01  1.70865438e-01]
 [ 2.08637001e+00  1.23155303e+00 -1.83983336e-01]
 [ 1.95613418e-01 -7.03759229e-01  1.84339331e-02]
 [-7.49521819e-01  3.84775509e-01  3.47581705e-01]
 [ 1.58799266e-02  1.85539870e-01 -5.39759680e-01]
 [-5.01362808e-01 -9.84800087e-01 -7.78304725e-01]
 [-1.87095957e+00 -4.69076203e-01  1.95845255e-01]
 [-3.73940825e-01 -1.09520588e+00 -9.78372778e-01]
 [-5.75774249e-01 -5.21228392e-02  4.08252756e-01]
 [ 9.71092958e-02 -1.93594256e-01 -1.70258360e+00]
 [-9.32835118e-02 -4.55949341e-01  1.02915564e+00]
 [ 9.88845848e-01  1.58956491e+00  4.72597482e-01]
 [-1.12247320e+00 -1.08050865e+00  2.56029734e-01]
 [-7.00058386e-02 -1.97203024e-02  9.82690984e-01]
 [ 1.18067587e+00  1.34623795e+00  1.66547444e+00]
 [-1.71919232e+00 -1.77628379e+00  1.01437007e+00]
 [ 9.82120132e-02  8.88259938e-01 -1.84087423e+00]
 [ 1.84009656e+00  6.30147201e-02 -1.27957697e+00]
 [-1.60684355e+00 -4.56231071e-01 -6.24818578e-01]
 [-1.91321015e-01  6.03589308e-01  2.60910502e-02]
 [ 2.77835229e-01 -1.74870032e+00  5.17659020e-01]
 [ 1.13336699e+00  1.46283292e+00 -7.25743813e-01]
 [-2.07701785e+00 -3.02576877e-01  1.86766764e-01]
 [-1.30014633e+00 -1.44642405e+00 -7.55382932e-01]
 [ 8.66451342e-01  7.04648882e-01 -6.11517803e-01]
 [ 5.49483208e-01 -2.49977791e-01 -1.40666110e+00]
 [ 5.12670209e-01  5.45681767e-01 -9.23233246e-01]
 [ 9.28672535e-01  1.56025056e-01 -1.35168461e+00]
 [-9.88873018e-01  1.17709871e-01 -9.75873253e-01]
 [-2.76545379e-01 -2.70877651e-01  1.05364180e+00]
 [ 3.63533634e-01  2.76048888e-01 -9.49398889e-01]
 [-1.20610800e+00 -9.46220949e-01  2.63238206e+00]
 [ 2.35778263e+00  1.45475498e+00  4.93317901e-01]
 [ 3.38760169e-01  4.06590355e-01  1.84836124e-01]
 [-8.85614898e-01 -5.39537633e-01 -8.58357780e-01]
 [ 8.15788567e-02  1.17524575e-01  7.00309879e-01]
 [-3.01392941e-01 -4.24365667e-01 -5.75637826e-01]
 [ 1.29378080e+00  1.52248065e+00  1.22009815e-01]
 [ 3.37846048e-01  3.24738416e-01  2.56008454e+00]
 [-5.65446383e-01 -1.25511997e+00 -9.60598997e-02]
 [ 1.10759226e+00  1.53431963e+00  1.14927333e+00]
 [-1.32901305e-01 -4.74419906e-01 -7.03176425e-01]
 [ 1.13471664e+00 -1.57376453e-01 -3.49884905e-02]
 [ 1.79104294e+00  2.03245350e+00  1.77080064e+00]
 [-2.02846267e-01 -6.27663298e-01 -6.26967058e-01]
 [-1.18907911e+00  1.56650287e-01  1.81244856e+00]
 [-4.90754451e-01 -5.26645612e-01  7.07751935e-01]
 [-5.79066226e-01  1.76361239e-01 -5.62466776e-01]
 [ 3.99470949e-01 -7.36436337e-01  6.32407739e-01]
 [ 9.52155840e-02 -9.23714332e-05  9.72554450e-01]
 [ 8.73646615e-01  7.45605694e-01  6.21809962e-01]
 [-6.33081761e-01 -8.58523846e-01 -1.57022472e+00]
 [ 8.32835992e-01  1.23377645e+00 -7.27137176e-01]
 [ 1.10904476e+00  1.43045258e+00 -2.47518636e-01]
 [ 7.38573631e-01 -1.33645119e+00 -7.44334291e-02]
 [ 1.22111856e+00  3.48730548e+00  6.20672098e-01]
 [ 6.09955569e-01  9.79050604e-02  1.77701001e-01]
 [-7.36992958e-01 -1.06261821e+00 -1.33534436e+00]
 [-1.83314404e+00 -3.32679108e-01  3.80197851e-01]
 [ 1.28154277e+00  1.20493343e+00  6.10585745e-01]
 [-3.40151605e-01 -1.22318353e+00  5.59790448e-01]
 [ 1.16876372e+00  6.04377561e-01  1.08078073e+00]
 [ 5.68918719e-01  2.47993567e-02  8.33922155e-01]
 [ 6.94378519e-01 -2.53504865e-01  4.59180079e-01]
 [-1.30966722e+00  1.62655119e-01 -7.01657115e-02]
 [-2.27851097e+00 -2.05508760e+00 -1.66096093e+00]
 [-6.07270460e-01  1.06613070e-01  4.29618219e-01]
 [ 1.55156572e+00  4.10507193e-01  2.07687687e-01]

In [38]:
# 3. Compute Moment Matrices (Cross-products)
# M_00 = Variance of short-run changes
# M_11 = Variance of long-run lagged levels
# M_01 / M_10: Covariance between short-run changes and long run levels.
M_00 = (dZ.T @ dZ) / T_effective
M_11 = (Z_lag.T @ Z_lag) / T_effective
M_01 = (dZ.T @ Z_lag) / T_effective
M_10 = M_01.T

print(f"M_00, M_11, M_01 and M_10 are as follows:")
print(M_00, M_11, M_01, M_10)
print(M_00.shape)

M_00, M_11, M_01 and M_10 are as follows:
[[ 1.41290285  0.67311506 -0.00655059]
 [ 0.67311506  0.97267709  0.05131293]
 [-0.00655059  0.05131293  1.03673309]] [[79.10558135 63.62950556 -5.5509043 ]
 [63.62950556 51.60085275 -4.41781241]
 [-5.5509043  -4.41781241 15.74730922]] [[-0.56493366 -0.31271112 -0.42362823]
 [-0.11917812 -0.38591492 -0.43547854]
 [ 0.35970307  0.32860012 -0.51172585]] [[-0.56493366 -0.11917812  0.35970307]
 [-0.31271112 -0.38591492  0.32860012]
 [-0.42362823 -0.43547854 -0.51172585]]
(3, 3)

In [54]:
# 4. Solve Johansen's Generalized Eigenvalue Problem
# We solve: | \lambda * M_11 - M_10 * (M_00^-1) * M_01 | = 0
M_00_inv = np.linalg.inv(M_00)
A = M_10 @ M_00_inv @ M_01
B = M_11
print(f"M_00_inv is: {M_00_inv}")
print(f"A is: {A}")
print(f"B is: {B}")

# Compute generalized eigenvalues and eigenvectors 
eigenvalues, eigenvectors = eig(A, B)
print(f"eigenvalues, eigenvectors are:\n {eigenvalues},\n {eigenvectors}")

# Real components only, then sort descending by eigenvalue strength
idx = np.argsort(eigenvalues.real)[::-1]
eigenvalues = eigenvalues.real[idx]
eigenvectors = eigenvectors.real[:,idx] # to rearrange the eigenvectors based on the sorting of the eigenvalues computed earlier.
print(f"idx is: {idx}")
print(f"eigenvalues is:\n {eigenvalues}")
print(f"eigenvectors is:\n {eigenvectors}")

M_00_inv is: [[ 1.05777482 -0.73427448  0.04302633]
 [-0.73427448  1.54049244 -0.08088591]
 [ 0.04302633 -0.08088591  0.96884372]]
A is: [[ 0.37539851  0.1863545  -0.04933069]
 [ 0.1863545   0.27192556  0.01256588]
 [-0.04933069  0.01256588  0.44736033]]
B is: [[79.10558135 63.62950556 -5.5509043 ]
 [63.62950556 51.60085275 -4.41781241]
 [-5.5509043  -4.41781241 15.74730922]]
eigenvalues, eigenvectors are:
 [0.51321233+0.j 0.00395371+0.j 0.02821164+0.j],
 [[-0.62803251 -0.72063358  0.22865848]
 [ 0.77818428 -0.69331036 -0.20032219]
 [ 0.00209368  0.00282546  0.95267325]]
idx is: [0 2 1]
eigenvalues is:
 [0.51321233 0.02821164 0.00395371]
eigenvectors is:
 [[-0.62803251  0.22865848 -0.72063358]
 [ 0.77818428 -0.20032219 -0.69331036]
 [ 0.00209368  0.95267325  0.00282546]]

In [65]:
print(f"--- Step 1: Johansen Sorted Eigenvalues ---")
for i, lam in enumerate(eigenvalues):
    print(f"Eigenvalue \\lambda_{i+1}: {lam:.4f}")

--- Step 1: Johansen Sorted Eigenvalues ---
Eigenvalue \lambda_1: 0.5132
Eigenvalue \lambda_2: 0.0282
Eigenvalue \lambda_3: 0.0040

In [73]:
# 5. Extract the Cointegrating Vector (Beta)
# the first eigenvector corresponding to the largest eigenvalue forms our main equilibrium vector
beta_1 = eigenvectors[:,0]
print(beta_1)

# Normalize the vector relative to the first variable for easy reading.
beta_1_normalized = beta_1 / beta_1[0]
print(beta_1_normalized)

print(f"\n--- Step 2: Cointegrating Vector (\\u03b2_1)---")
print(f"Normalized \\u03b2 vector: {beta_1_normalized}")
print(f"Long-run stationary relation: ({beta_1_normalized[0]:.2f} * z1) + ({beta_1_normalized[1]:.2f} * z2) + ({beta_1_normalized[2]:.2f} * z3) = Stationary Equilibrium")

# 6. Calculate Speed of adjustment (\u03b1)
# \u03b1 = M_01 * \u03b2 * (\u03b2' * M_11 * \u03b2)^-1
alpha_1 = M_01 @ beta_1 / (beta_1.T @ M_11 @ beta_1)
print("\n-- Step 3: Speed of Adjustment (\\uo3b1) ---")
for i, alp in enumerate(alpha_1):
    print(f"Economy variable z{i+1} correction speed: {alp:.4f}")

[-0.62803251  0.77818428  0.00209368]
[ 1.         -1.2390828  -0.00333372]

--- Step 2: Cointegrating Vector (\u03b2_1)---
Normalized \u03b2 vector: [ 1.         -1.2390828  -0.00333372]
Long-run stationary relation: (1.00 * z1) + (-1.24 * z2) + (-0.00 * z3) = Stationary Equilibrium

-- Step 3: Speed of Adjustment (\uo3b1) ---
Economy variable z1 correction speed: 0.4340
Economy variable z2 correction speed: -0.8885
Economy variable z3 correction speed: 0.1128